'use client';

import { useMemo, useState } from 'react';
import { ArrowRight, Check, CirclePlay, RotateCcw, ShieldCheck, Wrench } from 'lucide-react';
import { Button } from '@/components/ui/button';

const loopSteps=[['接收任务','输入：总结本地学习笔记；输出：目标与约束'],['分析任务','识别需要读取资料、保留来源且不能修改文件'],['制定计划','先定位笔记，再读取，最后核对来源并总结'],['选择工具','从允许集合中选择只读 read_note'],['调用工具','参数通过 Schema、路径范围与只读权限检查'],['接收结果','得到结构化内容和来源路径'],['判断完成','检查是否读到正文、是否保留来源、是否需要继续'],['输出结果','生成总结；若证据不足则明确报告而非猜测']];
export function AgentLoopDemo(){const[index,setIndex]=useState(-1);const done=index===loopSteps.length-1;return <Demo title="Agent 工作循环 · 本地确定性演示" description="每次点击推进一个真实状态；没有网络请求，也不会执行外部工具。"><div className="demo-progress" aria-label={`已完成 ${Math.max(0,index+1)} / ${loopSteps.length} 步`}>{loopSteps.map((step,i)=><button key={step[0]} className={i===index?'active':i<index?'done':''} onClick={()=>setIndex(i)}><span>{i<index?<Check/>:i+1}</span><small>{step[0]}</small></button>)}</div><div className="demo-stage" aria-live="polite">{index<0?<><CirclePlay/><div><strong>等待开始</strong><p>任务：读取本地 PDF 学习资料并生成带来源总结。</p></div></>:<><span className="demo-stage-index">{index+1}</span><div><strong>{loopSteps[index][0]}</strong><p>{loopSteps[index][1]}</p></div></>}</div><div className="flex gap-2"><Button onClick={()=>setIndex(done?0:index+1)}>{index<0?'开始执行':done?'重新执行':'下一步'}</Button><Button variant="outline" onClick={()=>setIndex(-1)}><RotateCcw/>重置</Button></div></Demo>}

const tools={read_note:{description:'读取允许目录中的 Markdown，纯只读。',schema:'{ path: string, max_chars: integer | null }',args:'{ path: "notes/agent.md", max_chars: 2000 }',result:'{ ok: true, title: "Agent", chars: 684 }',use:'Agent 将正文作为证据，并保留来源路径。'},calculate:{description:'执行确定性四则运算。',schema:'{ expression: string }',args:'{ expression: "0.95 * 0.90 * 0.98" }',result:'{ ok: true, value: 0.8379 }',use:'Agent 用结果说明端到端可靠性近似值。'},write_note:{description:'写入笔记，会产生副作用，必须审批。',schema:'{ path: string, content: string, idempotency_key: string }',args:'{ path: "notes/result.md", content: "...", idempotency_key: "demo-01" }',result:'{ status: "approval_required" }',use:'Agent 暂停并向用户展示具体目标与内容摘要。'}};
export function ToolCallDemo(){const[name,setName]=useState<keyof typeof tools>('read_note');const[stage,setStage]=useState(0);const tool=tools[name];const labels=['选择','验证 Schema','检查权限','执行','验证结果','交回 Agent'];return <Demo title="Tool 调用 · 参数、审批与结果" description="切换工具会改变 Schema、权限流程与实际演示结果。"><div className="demo-tabs">{Object.keys(tools).map(key=><button key={key} className={name===key?'active':''} onClick={()=>{setName(key as keyof typeof tools);setStage(0)}}>{key}</button>)}</div><div className="tool-demo-grid"><Info label="工具描述" value={tool.description}/><Info label="参数 Schema" value={tool.schema}/><Info label="输入参数" value={tool.args}/><Info label="结果" value={stage>=4?tool.result:'等待执行…'}/></div><div className="demo-pipeline">{labels.map((label,i)=><button key={label} className={i===stage?'active':i<stage?'done':''} onClick={()=>setStage(i)}>{label}</button>)}</div><p className="demo-explanation"><Wrench/> {stage<2?'模型可以提出调用，但 Schema 校验由宿主执行。':name==='write_note'&&stage>=2?'写工具在执行前进入审批；模型输出不是授权。':stage<4?'只读工具通过最小权限检查后执行。':tool.use}</p><Button onClick={()=>setStage(Math.min(labels.length-1,stage+1))} disabled={stage===labels.length-1}>推进调用<ArrowRight/></Button></Demo>}

const roles={agent:['组织目标与状态','决定下一步并判断完成','组合 Skill、Tool 与 MCP'],skill:['提供可复用流程与专业规范','可包含 references、scripts、assets','不一定直接执行外部动作'],tool:['执行一个具体动作','有输入输出 Schema、权限与错误','可能只读，也可能产生副作用'],mcp:['连接 Client 与外部 Server','统一发现 Tool、Resource、Prompt','不是 Agent，也不是具体业务动作']};
export function CapabilityComparisonDemo(){const[selected,setSelected]=useState<keyof typeof roles>('agent');return <Demo title="Agent、Skill、Tool、MCP · 组合关系" description="点击角色查看它提供什么，并观察读取本地 PDF 的职责链。"><div className="role-map">{Object.keys(roles).map((key,i)=><button key={key} className={selected===key?'active':''} onClick={()=>setSelected(key as keyof typeof roles)}><strong>{key.toUpperCase()}</strong><span>{i===0?'安排任务':i===1?'规定流程':i===2?'读取 PDF':'连接文档服务'}</span></button>)}</div><div className="definition-callout"><h3>{selected.toUpperCase()} 的职责</h3><ul>{roles[selected].map(item=><li key={item}>— {item}</li>)}</ul></div><div className="pdf-example"><span>模型理解意图</span><ArrowRight/><span>Agent 安排</span><ArrowRight/><span>Skill 规定阅读流程</span><ArrowRight/><span>Tool 读取</span><ArrowRight/><span>MCP 可提供连接</span></div></Demo>}

const flow=[['用户任务','自然语言目标与约束'],['Agent','决定需要读取外部资料'],['MCP Client','连接、发现并过滤允许能力'],['MCP Server','声明并实现 Tool / Resource / Prompt'],['Tool 或 Resource','执行受控动作或返回上下文'],['返回结果','JSON-RPC result 或 error'],['Agent 继续处理','验证证据与完成条件'],['最终回答','带来源输出或明确失败']];
export function McpFlowDemo(){const[index,setIndex]=useState(0);return <Demo title="MCP 数据流 · 可点击协议路径" description="选择任一层查看输入输出。当前推荐 stdio 或 Streamable HTTP；旧 HTTP+SSE 仅用于迁移兼容。"><div className="mcp-flow">{flow.map((item,i)=><button key={item[0]} className={index===i?'active':''} onClick={()=>setIndex(i)}><span>{item[0]}</span>{i<flow.length-1&&<ArrowRight/>}</button>)}</div><div className="demo-stage"><ShieldCheck/><div><strong>{flow[index][0]}</strong><p>{flow[index][1]}</p></div></div><div className="transport-status"><span><i className="current"/>stdio · 当前</span><span><i className="current"/>Streamable HTTP · 当前</span><span><i className="deprecated"/>HTTP+SSE · 已弃用</span></div></Demo>}

export function SingleMultiDemo(){const[mode,setMode]=useState<'single'|'multi'>('single');const data=useMemo(()=>mode==='single'?{title:'单 Agent',nodes:['一个 Agent','读取资料','分析','输出'],pros:['状态简单','协调开销低'],cost:['专业上下文较大','复杂任务易拥挤']}:{title:'Manager + 专业 Agent',nodes:['Manager','检索 Agent','分析 Agent','Manager 汇总'],pros:['角色专业化','独立子任务可并行'],cost:['更多调用与延迟','需处理交接、冲突和追踪']},[mode]);return <Demo title="单 Agent / 多 Agent 对照" description="多 Agent 只有在分工收益大于协调成本时才更合适。"><div className="demo-tabs"><button className={mode==='single'?'active':''} onClick={()=>setMode('single')}>单 Agent</button><button className={mode==='multi'?'active':''} onClick={()=>setMode('multi')}>多 Agent</button></div><div className="agent-network">{data.nodes.map((node,i)=><span key={node}>{node}{i<data.nodes.length-1&&<ArrowRight/>}</span>)}</div><div className="tool-demo-grid"><Info label={`${data.title} · 优势`} value={data.pros.join('；')}/><Info label={`${data.title} · 额外成本`} value={data.cost.join('；')}/></div></Demo>}

export function AIInteractiveDemo({kind}:{kind?:string}){if(kind==='agent-loop')return <AgentLoopDemo/>;if(kind==='tool-call')return <ToolCallDemo/>;if(kind==='capability-comparison')return <CapabilityComparisonDemo/>;if(kind==='mcp-flow')return <McpFlowDemo/>;if(kind==='single-multi')return <SingleMultiDemo/>;return null}
function Demo({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section className="ai-demo"><div className="ai-demo-heading"><p className="eyebrow">本地交互演示</p><h2>{title}</h2><p>{description}</p></div>{children}</section>}
function Info({label,value}:{label:string;value:string}){return <div className="demo-info"><small>{label}</small><code>{value}</code></div>}
