import { AlertTriangle,ArrowDown,Braces,Database,MessageSquareText,Sigma,TerminalSquare } from 'lucide-react';
import type { CodeExample } from '@/lib/long-form-content';
import { CodeBlock } from '@/components/code-block';
import { InlineMath } from '@/components/math';

const knownVariables:Record<string,string>={X:'完整特征矩阵，每行一个样本、每列一个特征。',y:'目标标签或连续目标值。',X_train:'训练特征，只允许它参与预处理器和模型的 fit。',X_test:'测试特征，只用于最终 transform、predict 和评价。',y_train:'与 X_train 对齐的训练目标。',y_test:'与 X_test 对齐的测试目标。',model:'组合预处理和估计器的模型对象。',scaler:'保存训练集缩放参数的转换器。',mean:'训练特征逐列均值。',std:'训练特征逐列标准差。',alpha:'当前学习率，控制每次参数更新的步长。',loss:'当前预测与目标之间的损失值。',gradient:'损失对参数的局部变化率。',w:'模型权重或当前待优化参数。',b:'偏置项。',y_pred:'模型对输入产生的预测结果。',prob:'模型输出的正类概率。',scores:'交叉验证各折的评价分数。'};
function lineRange(source:string,chunk:string){const all=source.split('\n');const first=chunk.split('\n')[0];const start=Math.max(0,all.findIndex((line)=>line===first));return`${start+1}–${start+chunk.split('\n').length} 行`}
function describeChunk(chunk:string,index:number,provided:string[]){if(/^\s*(from|import)\s/m.test(chunk))return'导入当前步骤需要的数值计算、预处理、模型或评价工具。依赖集中写在代码开头，便于复现。';if(/train_test_split/.test(chunk))return'按固定协议切分训练与测试数据；此处的数据边界决定后续哪些样本可以参与 fit。';if(/mean\(|std\(|mean\s*=|std\s*=/.test(chunk))return'只从训练数据逐列计算均值与标准差，对应标准化公式中的 μ 和 σ。';if(/fit_transform|\.fit\(/.test(chunk))return'调用 fit 学习训练数据中的参数；若在 Pipeline 中，预处理器与模型会按顺序拟合。';if(/\.transform|\.predict|\.score/.test(chunk))return'复用已经学到的状态处理未见数据；这里不能再次 fit，否则会产生数据泄漏。';if(/gradient|dw|db|backward/.test(chunk))return'计算损失对参数的梯度，对应数学表达中的 ∇J；梯度只给出局部变化方向。';if(/loss|criterion|mean\(.*\*\*2/.test(chunk))return'计算当前预测误差，把模型表现压缩成可优化的标量损失。';if(/optimizer\.step|-=|\+=/.test(chunk))return'按学习率和梯度更新参数。步长过小会缓慢，过大会越过最低点并震荡或发散。';if(/print\(/.test(chunk))return'输出中间参数、形状或最终指标，用于核对代码是否符合预期。';return provided[index]??'执行当前代码段，并把得到的状态传给下一步。'}
function extractVariables(source:string){return Object.entries(knownVariables).filter(([name])=>new RegExp(`\\b${name}\\b`).test(source)).slice(0,8)}
function mathLinks(source:string){const links:{latex:string;text:string}[]=[];if(/mean|std|StandardScaler/.test(source))links.push({latex:'z=\\frac{x-\\mu}{\\sigma}',text:'减去训练均值并除以训练标准差，对应代码中的 mean/std 或 StandardScaler。'});if(/gradient|dw|db|optimizer\.step|-=/.test(source))links.push({latex:'\\theta_{t+1}=\\theta_t-\\alpha\\nabla J(\\theta_t)',text:'参数更新由当前梯度与学习率共同决定。'});if(/loss|mean.*\*\*2/.test(source))links.push({latex:'J=\\frac{1}{n}\\sum_i(y_i-\\hat y_i)^2',text:'平方误差代码对应均方损失。'});return links}
function commonErrors(source:string,conceptPitfalls:string[]){const errors=[...conceptPitfalls];if(/StandardScaler|mean|std/.test(source))errors.unshift('不要在测试集上调用 fit 或 fit_transform；测试集只能复用训练参数。');if(/shape|reshape|X_train|X_test/.test(source))errors.push('确认样本轴、特征轴以及 X 与 y 的第一维完全对应。');return[...new Set(errors)]}

export function CodeExamplePanel({example,index,conceptPitfalls}:{example:CodeExample;index:number;conceptPitfalls:string[]}){const filename=`example_${String(index+1).padStart(2,'0')}.py`;const chunks=example.source.trim().split(/\n\s*\n/).filter(Boolean);const variables=extractVariables(example.source);const links=mathLinks(example.source);const errors=commonErrors(example.source,conceptPitfalls);return <article className="code-example-stack"><div className="mb-4"><p className="eyebrow">示例 {index+1}</p><h3 className="mt-1 text-lg font-semibold text-foreground">{example.title}</h3></div><CodeBlock language={example.language} source={example.source} title={example.title} filename={filename} purpose={example.purpose}/><div className="code-analysis"><div className="analysis-heading"><MessageSquareText size={18}/><div><h4>代码解析</h4><p>解析始终位于完整代码下方，并按实际代码段逐项对应。</p></div></div><AnalysisCard icon={<Database/>} title="输入数据与任务"><p>{example.purpose}</p>{variables.length>0&&<dl className="variable-grid">{variables.map(([name,meaning])=><div key={name}><dt><code>{name}</code></dt><dd>{meaning}</dd></div>)}</dl>}</AnalysisCard><div className="space-y-3">{chunks.map((chunk,chunkIndex)=><AnalysisCard key={`${chunkIndex}-${chunk}`} icon={<Braces/>} title={`Step ${chunkIndex+1} · ${lineRange(example.source,chunk)}`}><p>{describeChunk(chunk,chunkIndex,example.explanation)}</p><pre className="analysis-snippet"><code>{chunk}</code></pre></AnalysisCard>)}</div>{links.length>0&&<AnalysisCard icon={<Sigma/>} title="代码与数学原理"><div className="space-y-3">{links.map((item)=><div key={item.latex}><InlineMath latex={item.latex}/><p className="mt-1">{item.text}</p></div>)}</div></AnalysisCard>}<AnalysisCard icon={<TerminalSquare/>} title="预期输出或运行结果"><p>{example.expectedOutput}</p></AnalysisCard><AnalysisCard icon={<AlertTriangle/>} title={`常见错误 · ${errors.length} 条`}><ul className="space-y-2">{errors.map((item)=><li key={item} className="flex gap-2"><ArrowDown className="mt-1 size-3.5 rotate-[-45deg] shrink-0 text-[#c7a66a]"/><span>{item}</span></li>)}</ul></AnalysisCard></div></article>}
function AnalysisCard({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <section className="analysis-card"><div className="analysis-card-icon">{icon}</div><div className="min-w-0"><h5>{title}</h5><div className="mt-2 text-sm leading-7 text-muted-foreground">{children}</div></div></section>}
