'use client';

import Link from 'next/link';
import { Bookmark,CheckCircle2,ListTree } from 'lucide-react';
import type { Category,Concept } from '@/lib/content';
import { getConceptHref,sortConcepts } from '@/lib/concept-utils';
import { useLearning } from '@/components/learning-store';
import { ConceptSortControl } from '@/components/concept-sort-control';
import { Button } from '@/components/ui/button';
import { Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle,SheetTrigger } from '@/components/ui/sheet';

export function DesktopConceptDirectory({category,concepts,currentSlug}:{category:Category;concepts:Concept[];currentSlug:string}){return <aside className="concept-directory hidden xl:block" aria-label={`${category.title}概念目录`}><DirectoryContent category={category} concepts={concepts} currentSlug={currentSlug}/></aside>}
export function MobileConceptDirectory({category,concepts,currentSlug}:{category:Category;concepts:Concept[];currentSlug:string}){return <div className="mb-4 xl:hidden"><Sheet><SheetTrigger render={<Button variant="outline" className="w-full justify-between"/>}><span className="flex items-center gap-2"><ListTree/>当前目录 · {category.title}</span><span className="text-muted-foreground">{concepts.length} 项</span></SheetTrigger><SheetContent side="left" className="w-[88vw] max-w-sm gap-0 border-[#343434] bg-[#1c1c1c] p-0"><SheetHeader className="border-b border-border px-5 py-4"><SheetTitle>{category.title}</SheetTitle><SheetDescription>绿色勾选表示已学习，状态保存在当前浏览器</SheetDescription></SheetHeader><div className="min-h-0 flex-1 overflow-y-auto p-3"><DirectoryContent category={category} concepts={concepts} currentSlug={currentSlug}/></div></SheetContent></Sheet></div>}
function DirectoryContent({category,concepts,currentSlug}:{category:Category;concepts:Concept[];currentSlug:string}){const{bookmarks,learned,sortMode}=useLearning();const ordered=sortConcepts(concepts,bookmarks,sortMode);const saved=new Set(bookmarks);const completed=new Set(learned);return <><div className="border-b border-border px-2 pb-3"><p className="eyebrow">{category.shortTitle} 目录</p><h2 className="mt-1 text-sm font-semibold text-foreground">{category.title}</h2><p className="mt-1 text-xs text-muted-foreground">{completed.size} 已学习 · {concepts.length} 个概念</p><ConceptSortControl compact/></div><nav className="concept-list">{ordered.map((concept)=>{const isLearned=completed.has(concept.slug);return <Link key={concept.slug} href={getConceptHref(concept)} aria-current={concept.slug===currentSlug?'page':undefined} data-learned={isLearned?'true':'false'} className="concept-list-link"><span className="min-w-0 flex-1 truncate">{concept.title}</span>{isLearned&&<span className="learned-directory-state" aria-label="已学习"><CheckCircle2/>已学习</span>}{saved.has(concept.slug)&&<Bookmark className="size-3 shrink-0 fill-current text-primary" aria-label="已收藏"/>}<span className={`difficulty difficulty-${concept.difficulty}`}>{concept.difficulty??'进阶'}</span></Link>})}</nav></>}
