'use client';
import {useMemo,useState} from 'react';import {ArrowRight,BrainCircuit,Database,Network,Play,RotateCcw,Target} from 'lucide-react';import {Button} from '@/components/ui/button';
const actions=[[-1,0],[1,0],[0,-1],[0,1]];const arrows=['↑','↓','←','→'];const key=(r:number,c:number)=>`${r},${c}`;
function train(kind:'q'|'sarsa',episodes:number,alpha:number,epsilon:number,cliff=false){const rows=cliff?4:4,cols=cliff?12:5,goal=[rows-1,cols-1],start=[rows-1,0],blocked=new Set(cliff?[]:['1,2','2,2']);const Q=Array.from({length:rows*cols},()=>[0,0,0,0]);const rewards:number[]=[];let seed=17;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};const idx=(r:number,c:number)=>r*cols+c;const choose=(s:number)=>rand()<epsilon?Math.floor(rand()*4):Q[s].indexOf(Math.max(...Q[s]));const move=(pos:number[],a:number)=>{let nr=Math.max(0,Math.min(rows-1,pos[0]+actions[a][0])),nc=Math.max(0,Math.min(cols-1,pos[1]+actions[a][1]));if(blocked.has(key(nr,nc))){nr=pos[0];nc=pos[1]}if(cliff&&nr===rows-1&&nc>0&&nc<cols-1)return{pos:start,reward:-100,done:false};const done=nr===goal[0]&&nc===goal[1];return{pos:[nr,nc],reward:done?10:-1,done}};let lastPath:number[][]=[];for(let ep=0;ep<episodes;ep++){let pos=[...start],s=idx(...pos as [number,number]),a=choose(s),total=0;const path=[...[] as number[][],[...pos]];for(let t=0;t<(cliff?120:60);t++){const out=move(pos,a),ns=idx(...out.pos as [number,number]),na=choose(ns);const next=out.done?0:kind==='q'?Math.max(...Q[ns]):Q[ns][na];Q[s][a]+=alpha*(out.reward+0.95*next-Q[s][a]);total+=out.reward;pos=out.pos;s=ns;a=na;path.push([...pos]);if(out.done)break}rewards.push(total);if(ep===episodes-1)lastPath=path}return{Q,rewards,path:lastPath,rows,cols,blocked,goal,start}}
function Panel({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section className="rl-demo"><div className="rl-demo-head"><p className="eyebrow">本地确定性交互</p><h2>{title}</h2><p>{description}</p></div>{children}</section>}
export function GridWorldDemo(){const[episodes,setEpisodes]=useState(80),[alpha,setAlpha]=useState(.2),[epsilon,setEpsilon]=useState(.2);const result=useMemo(()=>train('q',episodes,alpha,epsilon),[episodes,alpha,epsilon]);return <Panel title="GridWorld Q-Learning" description="调整训练轮数、学习率和探索率，Q 表与策略箭头会重新计算。"><Controls values={[['训练轮数',episodes,20,400,20,setEpisodes],['learning rate',alpha,.05,.8,.05,setAlpha],['epsilon',epsilon,0,.8,.05,setEpsilon]]}/><Grid result={result}/><div className="rl-metrics"><Metric label="最终 reward" value={result.rewards.at(-1)?.toFixed(1)??'—'}/><Metric label="平均 reward" value={(result.rewards.reduce((a,b)=>a+b,0)/result.rewards.length).toFixed(2)}/><Metric label="起点最大 Q" value={Math.max(...result.Q[(result.rows-1)*result.cols]).toFixed(2)}/></div><p className="rl-note">每格显示当前贪心动作和最大 Q；障碍不可进入，目标奖励 +10，每步 −1。提高 epsilon 会增加探索，也会让有限训练下的策略更抖动。</p></Panel>}
export function QSarsaDemo(){const[episodes,setEpisodes]=useState(300),q=useMemo(()=>train('q',episodes,.2,.1,true),[episodes]),s=useMemo(()=>train('sarsa',episodes,.2,.1,true),[episodes]);return <Panel title="Q-Learning 与 SARSA · Cliff Walking" description="同一悬崖环境和随机序列下，对比 off-policy 贪心目标与 on-policy 实际下一动作。"><Controls values={[["训练轮数",episodes,50,800,50,setEpisodes]]}/><div className="rl-compare"><Path title="Q-Learning" result={q}/><Path title="SARSA" result={s}/></div><Curve a={q.rewards} b={s.rewards}/><p className="rl-note">Q-Learning 倾向学习贴近悬崖的最短贪心路径；SARSA 会把 epsilon-greedy 的探索风险计入目标，通常更保守。有限轮次下结果仍会随参数变化。</p></Panel>}
export function DQNDemo(){const[step,setStep]=useState(0);const nodes=[['状态输入','4×84×84 frame stack'],['Online Network','输出每个动作 Q'],['Replay Buffer','随机 mini-batch'],['Target Network','生成稳定 TD target'],['DQN Loss','Huber(Q, target)'],['参数更新','只更新 Online']];return <Panel title="DQN 训练结构" description="逐步查看 Replay、Online、Target 与 loss 的数据流。"><div className="dqn-flow">{nodes.map((n,i)=><button key={n[0]} className={step===i?'active':''} onClick={()=>setStep(i)}><span>{i+1}</span><strong>{n[0]}</strong>{i<nodes.length-1&&<ArrowRight/>}</button>)}</div><div className="rl-stage"><Network/><div><strong>{nodes[step][0]}</strong><p>{nodes[step][1]}</p></div></div><Button onClick={()=>setStep((step+1)%nodes.length)}><Play/>下一阶段</Button></Panel>}
export function PolicyGradientDemo(){const[theta,setTheta]=useState(0),[sample,setSample]=useState(0.37);const p=1/(1+Math.exp(-theta)),action=sample<p?'向右':'向左',reward=action==='向右'?1:-1,grad=(action==='向右'?1-p:-p)*reward;return <Panel title="Policy Gradient 概率策略" description="策略参数改变动作概率；固定采样数让变化可复现。"><Controls values={[["策略参数 θ",theta,-4,4,.1,setTheta],["采样数 u",sample,.01,.99,.01,setSample]]}/><div className="prob-bars"><Bar label="P(向右)" value={p}/><Bar label="P(向左)" value={1-p}/></div><div className="rl-metrics"><Metric label="采样动作" value={action}/><Metric label="轨迹 reward" value={String(reward)}/><Metric label="∂logπ × reward" value={grad.toFixed(3)}/></div><p className="rl-note">正回报会沿梯度提高已采样动作概率；负回报则降低。概率策略保留探索，熵正则可进一步阻止过早塌缩。</p></Panel>}
export function PPODemo(){const[ratio,setRatio]=useState(1.35),[adv,setAdv]=useState(1),[clip,setClip]=useState(.2);const unclipped=ratio*adv,cr=Math.max(1-clip,Math.min(1+clip,ratio)),clipped=cr*adv,obj=Math.min(unclipped,clipped);return <Panel title="PPO 裁剪目标" description="调整 probability ratio、advantage 和 clip range，观察代理目标何时被截断。"><Controls values={[["ratio",ratio,.4,1.8,.01,setRatio],["advantage",adv,-2,2,.1,setAdv],["clip ε",clip,.05,.5,.05,setClip]]}/><div className="ppo-axis"><div className="ppo-safe" style={{left:`${((1-clip-.4)/1.4)*100}%`,width:`${(2*clip/1.4)*100}%`}}/><i style={{left:`${((ratio-.4)/1.4)*100}%`}}/><span>0.4</span><span>安全更新区 [{(1-clip).toFixed(2)}, {(1+clip).toFixed(2)}]</span><span>1.8</span></div><div className="rl-metrics"><Metric label="未裁剪目标" value={unclipped.toFixed(3)}/><Metric label="裁剪后目标" value={clipped.toFixed(3)}/><Metric label="PPO 取值" value={obj.toFixed(3)}/></div><p className="rl-note">正 advantage 时，ratio 超过上界不会继续获得更高代理收益；负 advantage 时裁剪方向不同，minimum 仍构造保守目标。</p></Panel>}
export function DPOGRPODemo(){const[beta,setBeta]=useState(.1),[group,setGroup]=useState([1,.2,.8,-.2]);const pc=-1.2,pr=-2,rc=-1.4,rr=-1.8,logit=beta*((pc-pr)-(rc-rr)),dpo=-Math.log(1/(1+Math.exp(-logit)));const mean=group.reduce((a,b)=>a+b,0)/group.length,std=Math.sqrt(group.reduce((a,b)=>a+(b-mean)**2,0)/group.length)||1,advantages=group.map(x=>(x-mean)/std);return <Panel title="DPO 与 GRPO 数据流" description="DPO 使用 chosen/rejected 偏好对；GRPO 使用同一 prompt 的输出组和相对奖励。"><Controls values={[["DPO beta",beta,.05,1,.05,setBeta]]}/><div className="preference-grid"><div><h3>DPO · 离线偏好对</h3><article className="chosen"><strong>chosen</strong><span>“分步骤解释并给出来源”</span><code>policy −1.2 / ref −1.4</code></article><article><strong>rejected</strong><span>“只给结论”</span><code>policy −2.0 / ref −1.8</code></article><Metric label="DPO loss" value={dpo.toFixed(4)}/></div><div><h3>GRPO · 在线输出组</h3>{group.map((reward,i)=><label key={i}>输出 {i+1}<input type="range" min={-1} max={1.5} step={.1} value={reward} onChange={e=>setGroup(group.map((v,j)=>j===i?Number(e.target.value):v))}/><span>r={reward.toFixed(1)} / A={advantages[i].toFixed(2)}</span></label>)}<Metric label="组均值" value={mean.toFixed(3)}/></div></div><p className="rl-note">DPO 不需要传统在线 RL rollout；GRPO 对同一 prompt 采样一组输出、评分并组内标准化，原始设计不需要独立 Value Model。</p></Panel>}
const algo=[['Q-Learning','Value','off','离散','否','否'],['SARSA','Value','on','离散','否','否'],['DQN','Deep Value','off','离散','是','是'],['REINFORCE','Policy','on','两者','否','否'],['Actor-Critic','A-C','on','两者','否','否'],['DDPG/TD3/SAC','A-C','off','连续','是','是'],['PPO','A-C','on','两者','rollout','否'],['GRPO','Policy','on','文本','组采样','reference'],['DPO','Preference','离线','文本','偏好对','reference']];
export function AlgorithmComparisonDemo(){return <Panel title="算法能力矩阵" description="先按学习数据、策略归属和动作空间缩小选择范围。"><div className="rl-table"><table><thead><tr><th>算法</th><th>类别</th><th>策略</th><th>动作</th><th>Replay/数据</th><th>Target/Ref</th></tr></thead><tbody>{algo.map(row=><tr key={row[0]}>{row.map(x=><td key={x}>{x}</td>)}</tr>)}</tbody></table></div></Panel>}
export function RLInteractiveDemo({kind}:{kind?:string}){if(kind==='gridworld')return <GridWorldDemo/>;if(kind==='q-sarsa')return <QSarsaDemo/>;if(kind==='dqn')return <DQNDemo/>;if(kind==='policy-gradient')return <PolicyGradientDemo/>;if(kind==='ppo')return <PPODemo/>;if(kind==='dpo-grpo')return <DPOGRPODemo/>;if(kind==='algorithm-comparison')return <AlgorithmComparisonDemo/>;return null}
function Controls({values}:{values:any[][]}){return <div className="rl-controls">{values.map(([label,value,min,max,step,setter])=><label key={label}><span>{label}<b>{Number(value).toFixed(Number(step)<1?2:0)}</b></span><input type="range" value={value} min={min} max={max} step={step} onChange={e=>setter(Number(e.target.value))}/></label>)}</div>}
function Grid({result}:{result:ReturnType<typeof train>}){const path=new Set(result.path.map(p=>key(p[0],p[1])));return <div className="grid-world" style={{gridTemplateColumns:`repeat(${result.cols},1fr)`}}>{Array.from({length:result.rows*result.cols},(_,i)=>{const r=Math.floor(i/result.cols),c=i%result.cols,q=result.Q[i],goal=r===result.goal[0]&&c===result.goal[1],start=r===result.start[0]&&c===result.start[1],blocked=result.blocked.has(key(r,c));return <div key={i} className={`${goal?'goal ':''}${blocked?'blocked ':''}${path.has(key(r,c))?'path ':''}`}><strong>{blocked?'■':goal?'G':start?'S':arrows[q.indexOf(Math.max(...q))]}</strong><small>{blocked?'障碍':Math.max(...q).toFixed(2)}</small></div>})}</div>}
function Path({title,result}:{title:string;result:ReturnType<typeof train>}){return <div><h3>{title}</h3><Grid result={result}/><p>最终 {result.rewards.at(-1)?.toFixed(0)} / 平均 {(result.rewards.reduce((a,b)=>a+b,0)/result.rewards.length).toFixed(1)}</p></div>}
function Curve({a,b}:{a:number[];b:number[]}){const smooth=(x:number[])=>x.map((_,i)=>x.slice(Math.max(0,i-19),i+1).reduce((p,c)=>p+c,0)/Math.min(20,i+1));const aa=smooth(a),bb=smooth(b),min=Math.min(...aa,...bb),max=Math.max(...aa,...bb),pts=(x:number[])=>x.map((v,i)=>`${i/(x.length-1)*100},${90-(v-min)/(max-min||1)*80}`).join(' ');return <svg className="rl-curve" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={pts(aa)} className="q"/><polyline points={pts(bb)} className="sarsa"/></svg>}
function Metric({label,value}:{label:string;value:string}){return <div className="rl-metric"><small>{label}</small><strong>{value}</strong></div>}
function Bar({label,value}:{label:string;value:number}){return <div><span>{label}<b>{(value*100).toFixed(1)}%</b></span><i><em style={{width:`${value*100}%`}}/></i></div>}

