'use client';

import { useState } from 'react';
import { Slider } from '@/components/ui/slider';
import { BlockMath,InlineMath } from '@/components/math';

export function StandardizationDemo(){const[x,setX]=useState(80);const[mean,setMean]=useState(60);const[std,setStd]=useState(8.2);const z=(x-mean)/std;return <section className="interactive-demo" aria-labelledby="standardization-demo-title"><p className="eyebrow">交互图形</p><h2 id="standardization-demo-title" className="mt-2 text-xl font-semibold">从原始值到 Z-score</h2><p className="mt-2 text-sm leading-7 text-muted-foreground">拖动原始值和训练集统计量，观察同一个 <InlineMath latex="x"/> 如何映射到标准差坐标。这里的 <InlineMath latex="\\mu"/> 与 <InlineMath latex="\\sigma"/> 代表已经由训练集拟合完成的参数。</p><div className="mt-6 grid gap-6 lg:grid-cols-[260px_minmax(0,1fr)]"><div className="space-y-5"><Control label="原始值 x" value={x.toFixed(1)}><Slider value={[x]} min={20} max={110} step={1} onValueChange={(v)=>setX(Array.isArray(v)?v[0]:v)}/></Control><Control label="训练均值 μ" value={mean.toFixed(1)}><Slider value={[mean]} min={35} max={85} step={1} onValueChange={(v)=>setMean(Array.isArray(v)?v[0]:v)}/></Control><Control label="训练标准差 σ" value={std.toFixed(1)}><Slider value={[std]} min={2} max={20} step={.2} onValueChange={(v)=>setStd(Array.isArray(v)?v[0]:v)}/></Control></div><div className="rounded-xl border border-border bg-[#141414] p-5"><BlockMath latex={`z=\\frac{${x.toFixed(1)}-${mean.toFixed(1)}}{${std.toFixed(1)}}=${z.toFixed(3)}`}/><NumberLine label="原始尺度" min={20} max={110} value={x} ticks={[20,40,60,80,100]}/><NumberLine label="标准化尺度" min={-5} max={5} value={z} ticks={[-4,-2,0,2,4]}/><div className="mt-5 grid grid-cols-3 gap-2 text-center"><Metric label="x" value={x.toFixed(1)}/><Metric label="μ / σ" value={`${mean.toFixed(1)} / ${std.toFixed(1)}`}/><Metric label="z" value={z.toFixed(3)}/></div></div></div><div className="mt-6 grid gap-3 md:grid-cols-3"><Note title="滑动条改变什么">原始值改变样本位置；均值移动中心；标准差改变统一尺子的刻度大小。</Note><Note title="为什么只能用训练参数">若验证或测试值参与均值、标准差计算，评价数据的分布信息会泄漏到预处理过程。</Note><Note title="如何理解结果">正值表示高于训练均值，负值表示低于训练均值，绝对值表示相距多少个训练标准差。</Note></div></section>}

function Control({label,value,children}:{label:string;value:string;children:React.ReactNode}){return <div><div className="mb-2 flex justify-between"><label className="text-sm text-foreground">{label}</label><output className="font-mono text-xs text-primary">{value}</output></div>{children}</div>}
function NumberLine({label,min,max,value,ticks}:{label:string;min:number;max:number;value:number;ticks:number[]}){const pos=Math.max(0,Math.min(100,((value-min)/(max-min))*100));return <div className="mt-6"><div className="mb-2 flex justify-between text-xs text-muted-foreground"><span>{label}</span><span>当前：{value.toFixed(3)}</span></div><div className="relative h-10"><div className="absolute inset-x-0 top-4 h-px bg-[#555]"/><div className="absolute top-1 h-7 w-0.5 bg-primary" style={{left:`${pos}%`}}/><div className="absolute top-0 size-2 -translate-x-1/2 rounded-full bg-primary" style={{left:`${pos}%`}}/>{ticks.map((tick)=>{const left=((tick-min)/(max-min))*100;return <span key={tick} className="absolute top-5 -translate-x-1/2 text-[10px] text-[#777]" style={{left:`${left}%`}}>{tick}</span>})}</div></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-[#1e1e1e] p-2"><span className="block text-[10px] text-muted-foreground">{label}</span><strong className="mt-1 block font-mono text-sm">{value}</strong></div>}
function Note({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-lg border-l-2 border-primary bg-[#1d1d1d] p-4"><h3 className="text-sm font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{children}</p></div>}
