import type { LongFormConcept } from './long-form-core';

export interface AILongFormConcept extends LongFormConcept {
  subcategory:string; importance:string[]; learningObjectives:string[]; workflow:string[];
  inputs:string[]; outputs:string[]; expectedOutput:string; interactiveDemo?:string;
  securityRisks:string[]; performanceNotes:string[]; sourceUrls:string[]; versionDate:string;
  entityType:'theory'|'model'|'agent'|'skill'|'tool'|'mcp'|'comparison'; capabilities:string[];
  permissions:string[]; inputsSchema?:string; outputsSchema?:string; transport?:string[];
  executionEnvironment:string; approvalRequired:boolean; readOnly:boolean;
  failureModes:string[]; trustBoundary:string[]; commonQuestions:{question:string;answer:string}[];
}

type Seed={slug:string;title:string;difficulty:'入门'|'进阶'|'挑战';subcategory:string;entityType:AILongFormConcept['entityType'];summary:string;definition:string;background:string;intuition:string;principles:string[];steps:string[];inputs:string[];outputs:string[];applications:string[];pitfalls:string[];prerequisites:string[];related:string[];formula?:{label:string;expression:string;description:string};code?:{title:string;language:string;purpose:string;source:string;explanation:string[];expectedOutput:string};sourceUrls?:string[];sourceSections?:string[];security?:string[];performance?:string[];interactiveDemo?:string;capabilities?:string[];permissions?:string[];transport?:string[];executionEnvironment?:string;approvalRequired?:boolean;readOnly?:boolean;failureModes?:string[];trustBoundary?:string[]};

const accessed='2026-08-30';
const openaiAgents='https://openai.github.io/openai-agents-js/';
const openaiTools='https://developers.openai.com/api/docs/guides/function-calling';
const openaiMcp='https://developers.openai.com/api/docs/guides/tools-connectors-mcp';
const codexSkills='https://learn.chatgpt.com/docs/build-skills';
const mcpSpec='https://modelcontextprotocol.io/specification/2026-07-28';

const localLoop=`from dataclasses import dataclass\n\n@dataclass\nclass StepResult:\n    observation: str\n    done: bool\n\ndef search_notes(topic: str) -> StepResult:\n    notes = {"Agent": "Agent 组织模型、状态与工具来完成目标。"}\n    text = notes.get(topic, "本地资料中没有结果")\n    return StepResult(text, topic in notes)\n\ndef run_agent(task: str, max_steps: int = 4) -> str:\n    state = {"task": task, "step": 0, "observations": []}\n    while state["step"] < max_steps:\n        state["step"] += 1\n        result = search_notes("Agent")\n        state["observations"].append(result.observation)\n        if result.done:\n            return f"第 {state['step']} 步完成：{result.observation}"\n    return "达到步数上限，安全停止"\n\nprint(run_agent("解释 Agent"))`;


function make(seed: Seed): AILongFormConcept {
  const reliability = seed.slug === 'agent-reliability';
  const code = seed.code ?? (seed.slug === 'agent-loop' ? {
    title: '有停止条件的本地工作循环', language: 'Python' as const,
    purpose: '观察任务状态、工具返回和最大步数如何共同决定循环何时结束。',
    source: localLoop,
    explanation: ['工具返回观察结果和完成标记。', '循环保留历史观察，完成后立即返回；未完成时受最大步数限制。', '这是确定性的循环骨架，不包含模型推理或自主规划。'],
    expectedOutput: '第 1 步完成：Agent 组织模型、状态与工具来完成目标。',
  } : undefined);
  return {
    id: seed.slug, slug: seed.slug, title: seed.title,
    category: 'artificial-intelligence', difficulty: seed.difficulty,
    subcategory: seed.subcategory, entityType: seed.entityType, summary: seed.summary,
    importance: [],
    learningObjectives: [`能说明${seed.title}解决什么问题，以及何时适用。`, `能解释为什么“${seed.pitfalls[0]}”是误区。`],
    definition: [seed.definition], background: [seed.background], intuition: [seed.intuition],
    corePrinciple: seed.principles,
    formulas: reliability ? [{
      label: '串行流程的联合成功概率',
      expression: String.raw`P(A\cap B\cap C)=P(A)\,P(B\mid A)\,P(C\mid A\cap B)`,
      description: 'A、B、C 分别表示规划、执行、验收三个环节达标。公式描述三者同时达标的概率，是条件概率的链式法则，不要求各环节独立。实际任务成功必须另有明确验收标准，不能把模型自报“通过”当作真实成功。',
    }] : seed.formula ? [seed.formula] : [],
    variableDefinitions: reliability ? [
      { symbol: 'A', meaning: '规划满足任务约束。' },
      { symbol: 'B', meaning: '执行按约定正确完成。' },
      { symbol: 'C', meaning: '结果满足预先定义的验收条件。' },
      { symbol: 'P(B|A)', meaning: '在规划达标的样本中，执行达标的比例。' },
      { symbol: 'P(C|A∩B)', meaning: '在规划和执行都达标的样本中，验收达标的比例。' },
    ] : [],
    numericalExample: reliability ? {
      title: '从同一批任务统计端到端通过率',
      given: ['以下数字仅为教学假设，不是实测数据。', '1000 个任务中，950 个规划达标；其中 855 个执行达标；最后 838 个通过验收。'],
      steps: ['规划达标比例为 950 / 1000。', '在规划达标的任务中，执行达标比例为 855 / 950。', '在前两步都达标的任务中，验收达标比例为 838 / 855。', '三者相乘，得到 838 / 1000 = 83.8%。'],
      result: '这批假设任务的联合通过率为 83.8%，不需要假设三个环节相互独立。',
      comparison: ['不能直接相乘三个来自不同样本的总体通过率。', '线上评估还应按任务类型和失败原因分组，检查验收标准是否可靠。'],
    } : undefined,
    algorithmSteps: seed.steps, workflow: seed.steps, inputs: seed.inputs, outputs: seed.outputs,
    codeExamples: code ? [code as AILongFormConcept['codeExamples'][number]] : [],
    codeExplanation: code?.explanation ?? [], expectedOutput: code?.expectedOutput ?? '',
    applications: seed.applications, pitfalls: seed.pitfalls,
    securityRisks: seed.security ?? [], performanceNotes: seed.performance ?? [],
    prerequisites: seed.prerequisites, relatedConcepts: seed.related,
    interactiveDemo: seed.interactiveDemo,
    sourceDocuments: [], sourceSections: [], sourceUrls: seed.sourceUrls ?? [], versionDate: accessed,
    extensionNotes: [], capabilities: seed.capabilities ?? seed.applications,
    permissions: seed.permissions ?? [], inputsSchema: seed.inputs.join('；'), outputsSchema: seed.outputs.join('；'),
    transport: seed.transport, executionEnvironment: seed.executionEnvironment ?? '',
    approvalRequired: seed.approvalRequired ?? false, readOnly: seed.readOnly ?? true,
    failureModes: seed.failureModes ?? [], trustBoundary: seed.trustBoundary ?? [], commonQuestions: [],
  };
}
const seeds:Seed[]=[
{slug:'ai-overview',title:'人工智能是什么',difficulty:'入门',subcategory:'理论基础',entityType:'theory',summary:'从理性行动、任务环境与可验证目标理解人工智能，而不是把 AI 等同于单一模型。',definition:'人工智能研究和构建能够感知环境、表示信息、推理或学习，并采取行动以实现目标的系统。',background:'AI 同时包含符号推理、搜索规划、统计学习、生成模型和智能体系统，不同路线解决的问题与证据标准不同。',intuition:'AI 像一套解决问题的工程学：先定义“什么算完成”，再选择表示、算法、模型与行动机制。',principles:['任务必须先被表示为可观察输入、内部状态、候选行动与成功标准。','理性并不要求永远正确，而是在有限信息与资源下选择预期效用较高的行动。','生成结果需要由评测、约束或外部事实验证，流畅度不是正确性的充分证据。'],steps:['定义任务环境与用户目标','确定可观察信息和行动范围','选择规则、搜索、学习或生成方法','执行并收集反馈','按验收标准评估和改进'],inputs:['任务描述','环境观察','约束与成功标准'],outputs:['预测、计划、生成内容或环境行动'],applications:['辅助决策','自动化工作流','感知与生成系统'],pitfalls:['把 AI 等同于聊天机器人','没有先定义成功标准','把拟人化描述当成机制解释'],prerequisites:['概率与逻辑基础'],related:['state-space-search','knowledge-representation','intelligent-agent'],sourceUrls:['https://plato.stanford.edu/entries/artificial-intelligence/',openaiAgents]},
{slug:'ai-history',title:'人工智能发展历史',difficulty:'入门',subcategory:'理论基础',entityType:'theory',summary:'沿符号主义、统计学习、深度学习与基础模型理解 AI 方法为何更替并相互融合。',definition:'AI 历史是问题表示、计算资源、数据规模与学习算法共同演进的历史。',background:'早期系统依赖规则与搜索，随后统计学习强调从数据估计，深度学习推进表示学习，基础模型又把通用生成能力带入工具化系统。',intuition:'每一波 AI 浪潮都不是把旧方法清零，而是在新的资源条件下重新组合表示、搜索和学习。',principles:['能力提升通常来自算法、数据、算力和评测的共同变化。','技术低谷常由承诺超过可验证能力、数据或计算条件不足造成。','现代 Agent 仍会使用经典搜索、规划、状态和反馈思想。'],steps:['按年代标记代表性方法','比较各时期的核心假设','记录成功任务与失败边界','把历史概念连接到现代系统'],inputs:['年代','代表论文和系统','当时的计算与数据条件'],outputs:['技术路线时间线','方法之间的继承关系'],applications:['理解技术选择','避免把旧思想包装成全新概念'],pitfalls:['只记年份不理解因果','把路线更替写成单线胜利史'],prerequisites:['人工智能是什么'],related:['ai-overview','symbolic-connectionist-behaviorist','generative-ai']},
{slug:'ai-ml-dl-relationship',title:'AI、机器学习与深度学习的关系',difficulty:'入门',subcategory:'理论基础',entityType:'model',summary:'用集合与职责边界区分 AI、机器学习、深度学习和生成模型。',definition:'机器学习是 AI 的一类数据驱动方法，深度学习是机器学习中使用多层神经网络进行表示学习的方法族。',background:'现实项目往往把规则、检索、机器学习模型和人工审批组合在一起，仅靠集合关系无法描述完整系统。',intuition:'AI 是目标领域，机器学习是从数据学习的方法，深度学习是其中一组模型技术。',principles:['AI 系统可以完全不使用机器学习，例如规则系统和经典搜索。','深度学习模型仍需要数据、损失、优化与评测。','Agent 是系统组织方式，不是与机器学习平行的一种训练算法。'],steps:['识别任务目标','判断是否需要从数据学习','判断表示是否需要深层网络','补充规则、工具与验证'],inputs:['任务需求','数据条件','可解释性与延迟要求'],outputs:['方法族选择与组合架构'],applications:['技术路线选择','学习路径规划'],pitfalls:['把三个词互换使用','认为深度模型天然具备 Agent 能力'],prerequisites:['人工智能是什么'],related:['machine-learning-overview','neural-networks','agent-architecture']},
{slug:'symbolic-connectionist-behaviorist',title:'符号主义、连接主义与行为主义',difficulty:'入门',subcategory:'理论基础',entityType:'theory',summary:'比较显式规则、分布式表示和基于交互行为三种经典 AI 视角。',definition:'符号主义强调可组合符号与推理，连接主义强调网络中的分布式表示，行为主义强调智能由感知—行动闭环涌现。',background:'三种路线对“知识在哪里、如何获得、如何验证”给出不同答案，现代系统常混合使用。',intuition:'规则像手册，神经网络像从例子中形成的直觉，行为系统像通过环境反馈练习出来的技能。',principles:['符号方法便于表达约束但知识获取成本高。','连接主义善于从数据学习表示但内部机制不天然透明。','行为主义把环境反馈和行动效果放在中心。'],steps:['确定知识是否可显式编码','评估可用数据和反馈','选择一种主路线','用其他路线补足约束或适应性'],inputs:['规则知识','训练数据','环境反馈'],outputs:['规则推理、模型预测或行为策略'],applications:['混合智能系统','机器人','知识增强生成'],pitfalls:['把三者看成互斥阵营','用哲学标签代替工程分析'],prerequisites:['AI 发展历史'],related:['knowledge-representation','neural-networks','agent-environment']},
{slug:'intelligent-agent',title:'智能体（Agent）',difficulty:'入门',subcategory:'Agent',entityType:'agent',summary:'Agent 以目标为导向，在状态和约束下循环理解、规划、行动、观察与判断完成。',definition:'在本课程中，Agent 是把模型、指令、状态、工具、控制循环与安全边界组织起来完成任务的系统。OpenAI Agents SDK 将 Agent 描述为配有 instructions、tools 与 handoffs 的 LLM。',background:'普通对话只产生一次回复；开放任务需要读取新信息、执行动作、检查结果，并在未完成时继续。Agent 为这类多步闭环提供结构。',intuition:'模型像会思考和表达的大脑，Agent 像负责把目标推进到结果的项目负责人；工具是它能使用的具体能力。',principles:['输入进入循环后先形成当前状态；规划可以显式列出，也可以体现在下一步工具选择中。','行动产生观察，观察必须写回状态，随后由完成条件决定输出、继续或安全停止。','Agent 与工作流并非对立：固定流程更可控，模型驱动选择更灵活；生产系统常组合两者。','聊天机器人可以只生成文本；Agent 的关键差异在于能够在边界内采取动作并基于结果继续。'],steps:['接收任务并提取目标与约束','理解上下文，建立或更新状态','制定可验证的短计划','从允许集合选择工具或行动','调用并记录参数、审批与结果','验证观察是否可信且满足完成条件','完成则输出；否则更新计划继续','达到步数、时间或权限边界时安全停止'],inputs:['用户任务','系统与开发者指令','会话状态','工具描述及权限'],outputs:['最终回答','结构化结果','工具调用记录','停止或升级人工的原因'],applications:['研究与资料整理','代码与文档工作流','客服分流与受控业务操作'],pitfalls:['把无限循环当成自主性','没有停止条件和结果验证','把工具返回内容自动提升为系统指令','把 Agent 与模型、工作流混为一谈'],prerequisites:['ai-overview','environment-state-action-goal'],related:['agent-architecture','agent-loop','llm-and-agent','tools','single-vs-multi-agent'],interactiveDemo:'agent-loop',sourceUrls:[openaiAgents,'https://openai.github.io/openai-agents-js/guides/agents/','https://openai.github.io/openai-agents-js/guides/running-agents/'],sourceSections:['Agents SDK / Overview','Agents / Composition patterns','Running agents / Agent loop'],capabilities:['状态管理','工具调用','结果判断','委派与 Handoff'],permissions:['仅暴露任务所需工具','写操作和敏感数据需审批'],approvalRequired:true,readOnly:false},
{slug:'environment-state-action-goal',title:'环境、状态、动作与目标',difficulty:'入门',subcategory:'Agent',entityType:'agent',summary:'用环境、可观察状态、候选动作和完成条件描述 Agent 任务。',definition:'环境是 Agent 可观察并可能改变的外部世界；状态是当前决策所需信息；动作是允许执行的操作；目标定义成功。',background:'如果没有清楚状态和目标，Agent 可能重复动作、误判完成或把中间结果当成最终结果。',intuition:'像导航：地图与道路是环境，当前位置是状态，转弯是动作，到达地址是目标。',principles:['状态应包含决策所需且允许保存的信息。','动作集合同时是能力边界和安全边界。','目标必须可检查，最好有明确的完成谓词和失败条件。'],steps:['列出环境中的对象','定义可观察字段','定义允许动作及副作用','写出完成、失败与停止条件'],inputs:['观察','历史状态','用户目标'],outputs:['下一动作','更新后的状态','完成判断'],applications:['Agent 设计','强化学习问题建模'],pitfalls:['状态缺失关键信息','目标无法验证','动作没有副作用说明'],prerequisites:['ai-overview'],related:['intelligent-agent','agent-state-memory','agent-loop']},
{slug:'search-planning-decision',title:'搜索、规划与决策',difficulty:'入门',subcategory:'理论基础',entityType:'theory',summary:'区分枚举路径的搜索、生成行动序列的规划与在不确定性下选择行动的决策。',definition:'搜索探索候选状态，规划构造达到目标的行动序列，决策依据价值、风险和约束选择当前行动。',background:'Agent 的“计划”并不自动保证可执行；必须与真实动作集合、环境反馈和成本模型对齐。',intuition:'搜索像看多条路线，规划像写旅行步骤，决策像结合时间与风险选一条现在要走的路。',principles:['搜索需要状态、后继函数和目标测试。','规划还需要动作前置条件和效果。','不确定决策需比较期望收益、风险和信息价值。'],steps:['定义状态与动作','生成候选方案','估计成本和风险','执行一小步并重规划'],inputs:['状态空间','行动模型','目标与成本'],outputs:['候选路径','计划','当前决策'],applications:['任务规划','工具选择','机器人导航'],pitfalls:['规划脱离真实工具能力','忽略搜索空间爆炸'],prerequisites:['state-space-search'],related:['agent-planning','tool-selection-filtering','markov-decision-process']},
{slug:'agent-architecture',title:'Agent 基本结构',difficulty:'进阶',subcategory:'Agent',entityType:'agent',summary:'把模型、指令、上下文、状态、工具、运行器、护栏和追踪组织成可测试结构。',definition:'Agent 架构说明每个组件的职责、数据流、信任边界与停止控制，而不只是画一个“LLM + Tools”框。',background:'任务复杂后，提示词、工具和历史都塞入一个调用会导致上下文膨胀、权限模糊和难以定位错误。',intuition:'像软件架构：模型不是整个应用，运行器负责调度，工具适配外部世界，状态存储当前事实，护栏与日志负责控制和诊断。',principles:['职责分离让模型决策、应用状态和外部副作用可以分别测试。','工具描述与 Schema 构成模型可见接口，真正授权仍由应用在执行前检查。','追踪应覆盖每次模型生成、工具调用、Handoff、护栏结果与停止原因。'],steps:['定义 Agent 指令和输出契约','配置最小工具集','设计状态所有权','加入审批与护栏','定义追踪字段和评测集'],inputs:['指令','上下文','工具定义','应用状态'],outputs:['运行轨迹','最终输出','错误或审批中断'],applications:['生产 Agent 架构','可观测工作流'],pitfalls:['把授权写在提示词里就认为安全','状态归属不清','没有追踪敏感数据策略'],prerequisites:['intelligent-agent','tools'],related:['agent-loop','agent-state-memory','tracing-observability','guardrails-prompt-injection'],sourceUrls:[openaiAgents,'https://openai.github.io/openai-agents-js/guides/tracing/']},
{slug:'llm-and-agent',title:'大语言模型与 Agent',difficulty:'进阶',subcategory:'Agent',entityType:'agent',summary:'模型负责推断和生成，Agent 系统负责上下文、工具、循环、状态和结果控制。',definition:'LLM 是根据输入生成输出的模型；Agent 是围绕模型建立的目标驱动运行系统。',background:'把模型回答误当成已经执行，会造成“说完成了但没有动作”的可靠性缺口。',intuition:'LLM 能提出下一步，Agent 运行器才决定是否允许、如何执行、如何记录以及是否继续。',principles:['模型输出是候选决策，不是权限凭证。','工具执行结果要作为新观察返回模型或确定性控制器。','最终完成状态应由可验证结果而非语言自信判断。'],steps:['模型接收状态','产生回答或工具请求','运行器验证并执行','结果回填','判断继续或结束'],inputs:['提示与上下文','工具 Schema'],outputs:['文本、结构化输出或工具调用意图'],applications:['区分模型评测与系统评测'],pitfalls:['把幻觉当成工具执行结果','忽略运行器责任'],prerequisites:['generative-ai','intelligent-agent'],related:['agent-loop','tool-calling','agent-evaluation']},
{slug:'prompt-instructions-context',title:'Prompt、指令与上下文',difficulty:'进阶',subcategory:'Agent',entityType:'agent',summary:'区分任务输入、持久行为规则和运行时上下文，并建立优先级与注入边界。',definition:'Prompt 是送入模型的信息集合；指令规定行为与约束；上下文提供当前任务所需事实、历史和工具结果。',background:'把所有文字视为同等可信，会让网页、文件或工具结果中的恶意指令覆盖应用目标。',intuition:'指令像工作守则，上下文像手头资料；资料可以被引用，但不应改写工作守则。',principles:['不同来源应保留 provenance 与信任级别。','只加载当前决策需要的上下文，减少冲突与成本。','不可信内容中的命令应作为数据处理，不自动执行。'],steps:['分离系统规则与用户目标','选择相关上下文','标记来源与权限','生成后验证输出契约'],inputs:['系统指令','用户输入','检索与工具结果'],outputs:['结构化模型输入','可审计来源'],applications:['提示设计','RAG','安全边界'],pitfalls:['提示词堆叠','忽略间接提示注入'],prerequisites:['llm-and-agent'],related:['agent-state-memory','retrieval-augmented-generation','guardrails-prompt-injection']},
{slug:'agent-state-memory',title:'Agent 状态与记忆',difficulty:'进阶',subcategory:'Agent',entityType:'agent',summary:'区分当前运行状态、会话历史、长期记忆与外部事实源。',definition:'状态是一次决策需要的当前数据；记忆是跨步骤或跨会话保留并可检索的信息。',background:'无限累积完整对话会增加成本和冲突，也可能长期保存不应保留的敏感信息。',intuition:'状态像工作台，短期记忆像本次任务笔记，长期记忆像经过筛选的档案库。',principles:['每类状态必须有所有者、生命周期和删除策略。','摘要会丢信息，关键事实需结构化保存并带来源。','记忆写入比读取风险更高，应验证内容与授权。'],steps:['定义状态 Schema','确定保存周期','写入前验证和去敏','检索时按任务过滤','完成后清理临时状态'],inputs:['会话事件','工具结果','用户允许保存的信息'],outputs:['当前状态快照','受控记忆条目'],applications:['长任务连续性','个性化'],pitfalls:['把聊天历史等同于记忆','保存敏感信息无过期策略'],prerequisites:['prompt-instructions-context'],related:['agent-loop','tracing-observability']},
{slug:'tool-calling',title:'工具调用',difficulty:'进阶',subcategory:'Tool',entityType:'tool',summary:'模型提出结构化工具调用，应用负责验证、授权、执行并返回结果。',definition:'工具调用是一种控制循环：模型依据工具描述生成名称与参数，宿主应用执行真实函数，再把结果返回模型。',background:'模型本身不能因为输出了一段 JSON 就自动拥有文件、网络或业务系统权限。',intuition:'模型填写申请单，应用检查申请、执行操作并给回执；申请单不是操作本身。',principles:['模型选择工具与参数，应用保留最终执行权。','Schema 约束形状，业务验证约束语义和权限。','工具结果要有成功、失败和可重试状态，避免自然语言猜测。'],steps:['向模型暴露最小工具描述','接收名称与参数','验证 Schema 和业务权限','必要时请求审批','执行并记录幂等键','返回结构化结果','由 Agent 使用结果继续'],inputs:['工具名','参数对象','调用者与授权上下文'],outputs:['结构化结果','错误分类','审计记录'],applications:['读取文件','查询数据','受控业务操作'],pitfalls:['把 Schema 当授权','无幂等性地重试写操作','把错误字符串当成功结果'],prerequisites:['llm-and-agent'],related:['function-calling','tools','tool-selection-filtering'],interactiveDemo:'tool-call',sourceUrls:[openaiTools,'https://openai.github.io/openai-agents-js/guides/tools/'],sourceSections:['Function calling / How it works','Function calling / Strict mode','Agents SDK / Tools'],approvalRequired:true,readOnly:false},
{slug:'function-calling',title:'函数工具与参数 Schema',difficulty:'进阶',subcategory:'Tool',entityType:'tool',summary:'用 JSON Schema 描述函数输入，使模型能生成可验证的结构化参数。',definition:'函数工具是由名称、描述、输入参数 Schema 和执行实现构成的工具接口。',background:'自由文本参数容易遗漏字段、类型错误或混入额外值；严格 Schema 可提前发现结构问题。',intuition:'它像一份机器可读表单：字段、类型、枚举和必填项都明确。',principles:['OpenAI 当前函数调用文档建议启用 strict 模式。','严格模式要求对象关闭 additionalProperties，并把所有 properties 列入 required；可空字段用包含 null 的类型表达。','Schema 只验证结构，路径范围、额度、身份和业务规则仍需应用验证。'],steps:['定义名称和使用描述','编写 JSON Schema','开启严格模式','解析模型参数','执行语义与权限校验','调用函数并返回结构化结果'],inputs:['JSON Schema','模型生成参数'],outputs:['验证后的参数或结构化错误'],applications:['API 适配','结构化查询','本地函数调用'],pitfalls:['description 模糊','漏写 additionalProperties:false','把可选字段从 required 中删除而不使用 null'],prerequisites:['tool-calling','JSON 基础'],related:['tools','mcp-overview'],sourceUrls:[openaiTools],code:{title:'严格函数工具的参数 Schema',language:'JSON',purpose:'展示 OpenAI 当前文档推荐的 strict JSON Schema 约束；仅作静态示例。',source:`{\n  "type": "function",\n  "name": "read_note",\n  "description": "读取允许目录中的一份 Markdown 笔记",\n  "strict": true,\n  "parameters": {\n    "type": "object",\n    "properties": {\n      "path": {"type": "string"},\n      "max_chars": {"type": ["integer", "null"]}\n    },\n    "required": ["path", "max_chars"],\n    "additionalProperties": false\n  }\n}`,explanation:['type 和 name 标识函数工具。','parameters 使用 JSON Schema；strict:true 要求完整且封闭的对象结构。','max_chars 用 null 表达可选语义，但仍位于 required。'],expectedOutput:'模型工具调用参数只能包含 path 与 max_chars；结构不合法时应拒绝执行。'}},
{slug:'retrieval-augmented-generation',title:'检索增强生成（RAG）',difficulty:'进阶',subcategory:'模型与 Agent',entityType:'model',summary:'先从受控知识源检索证据，再让模型依据证据生成并保留来源。',definition:'RAG 把查询、检索、重排、上下文组装和生成结合，以降低仅依赖模型参数记忆的事实风险。',background:'模型训练数据可能过时或不含私有资料，检索允许在回答时引入当前文档。',intuition:'先查书再作答，而不是只凭记忆。',principles:['检索召回决定模型能看到什么。','分块和重排影响证据完整性。','生成阶段应区分证据内容与其中潜在指令。'],steps:['解析查询','检索候选片段','重排与去重','组装带来源上下文','生成并核对引用'],inputs:['用户问题','文档索引'],outputs:['证据片段','带来源回答'],applications:['知识库问答','文档助手'],pitfalls:['检索不到仍强行回答','引用与结论不对应'],prerequisites:['prompt-instructions-context'],related:['knowledge-representation','guardrails-prompt-injection']},
{slug:'agent-loop',title:'Agent 工作循环',difficulty:'进阶',subcategory:'Agent',entityType:'agent',summary:'用“理解—计划—行动—观察—判断”循环推进任务，并受停止条件约束。',definition:'Agent loop 是运行器重复执行模型决策、工具调用与结果反馈，直到产生最终输出、错误、审批中断或达到限制。',background:'一次模型调用无法处理依赖外部结果的多步任务；循环把每个新结果变成下一步决策的证据。',intuition:'像做实验：提出下一步、动手、观察、判断，再决定继续还是结束。',principles:['每轮必须消费新信息或缩小未完成范围，否则可能空转。','终止条件至少包括任务完成、最大步数、超时、不可恢复错误和权限拒绝。','工具结果需要验证后才能更新完成状态。'],steps:['接收任务','分析任务','制定计划','选择工具','调用工具','接收工具结果','判断是否完成','输出结果或继续'],inputs:['当前状态','工具列表','上一步观察'],outputs:['工具调用、状态更新或最终输出'],applications:['多步研究','本地自动化'],pitfalls:['没有最大步数','重复调用同一工具','把“看起来完成”当作验收'],prerequisites:['intelligent-agent','tool-calling'],related:['agent-architecture','tracing-observability','agent-error-handling'],interactiveDemo:'agent-loop'},
{slug:'single-vs-multi-agent',title:'单 Agent 与多 Agent',difficulty:'进阶',subcategory:'Agent',entityType:'comparison',summary:'比较一个 Agent 统一处理与多个专业 Agent 分工的收益、成本和控制方式。',definition:'单 Agent 由一个活动决策主体完成流程；多 Agent 把任务分给多个具有不同指令或工具的 Agent。',background:'多 Agent 能缩小每个角色的上下文，却会增加路由、状态同步、延迟、成本和失败组合。',intuition:'单人完成沟通少；团队分工专业，但需要负责人、交接标准与共享记录。',principles:['只有任务可清晰分解且专业化收益大于协调成本时才应增加 Agent。','并行适合相互独立的子任务；存在数据依赖的步骤应顺序执行。','Manager 保留最终控制，Handoff 则把会话控制转给专家。'],steps:['评估任务是否可分解','定义每个角色的输入输出','选择 Manager、Handoff 或并行','聚合并验证结果','记录跨 Agent 轨迹'],inputs:['主任务','角色定义','共享或隔离状态'],outputs:['子任务结果','聚合答案','交接记录'],applications:['研究分工','多领域客服'],pitfalls:['为展示复杂度而多 Agent','多个 Agent 共享过多敏感上下文'],prerequisites:['intelligent-agent'],related:['manager-pattern','handoffs','agents-as-tools','agent-orchestration'],interactiveDemo:'single-multi',sourceUrls:['https://openai.github.io/openai-agents-js/guides/multi-agent/']},
{slug:'agent-error-handling',title:'Agent 错误处理',difficulty:'进阶',subcategory:'Agent',entityType:'agent',summary:'把可重试、需修正、需审批和不可恢复错误分类处理。',definition:'Agent 错误处理是从模型、工具、网络、权限和验证失败中恢复或安全停止的策略。',background:'盲目重试会重复副作用，吞掉错误会让 Agent 用缺失结果继续生成。',intuition:'先判断是临时堵车、地址填错、权限不足还是道路永久关闭，再决定重试、改参、请人或停止。',principles:['错误必须结构化分类并保留原始原因。','只对瞬时且幂等的操作做有限退避重试。','写操作重试需要幂等键或执行前查重。'],steps:['捕获错误','分类瞬时/输入/权限/业务/未知','决定重试、修正、审批或停止','记录次数与最终原因'],inputs:['错误类型','调用参数','重试计数'],outputs:['恢复结果或明确失败'],applications:['可靠 Agent 运行器'],pitfalls:['无限重试','隐藏错误细节','写操作无幂等键'],prerequisites:['agent-loop','tools'],related:['agent-reliability','tracing-observability']},
{slug:'agent-evaluation',title:'Agent 评估',difficulty:'进阶',subcategory:'Agent',entityType:'agent',summary:'同时评估最终答案、过程轨迹、工具选择、安全边界和资源消耗。',definition:'Agent 评估用代表性任务集和可检查标准衡量端到端系统，而不只评价单次语言输出。',background:'最终文本可能看似正确但调用了错误工具、泄露数据或消耗过多步骤。',intuition:'不仅看项目交付物，还检查过程是否合规、证据是否真实、成本是否可接受。',principles:['任务级成功率与步骤级诊断指标同时需要。','评测集应包含正常、边界、对抗和权限拒绝案例。','版本、模型、工具和提示变化都需回归评测。'],steps:['定义任务与评分规则','保存基线轨迹','运行代表性评测集','分析失败步骤','修改后回归'],inputs:['任务集','期望结果','轨迹'],outputs:['成功率、错误分类、成本与延迟'],applications:['发布门槛','回归测试'],pitfalls:['只看主观好不好','评测数据泄漏到开发提示'],prerequisites:['agent-loop','model-evaluation'],related:['tracing-observability','guardrails-prompt-injection']},
{slug:'agent-security',title:'Agent 安全边界',difficulty:'进阶',subcategory:'Agent',entityType:'agent',summary:'用最小权限、信任分层、审批和结果校验限制 Agent 的可行动范围。',definition:'安全边界决定什么输入可信、哪些工具可见、谁能批准、哪些数据可读写以及失败时如何隔离。',background:'Agent 会把自然语言连接到真实动作，因此提示注入、越权和副作用风险高于纯文本问答。',intuition:'即使负责人很聪明，也只能拿到当前工作需要的钥匙；开保险柜仍需第二个人确认。',principles:['提示中的禁止语不能替代真正的权限检查。','读取与写入工具应分离，敏感动作默认审批。','外部内容永远不应自动获得指令权限。'],steps:['画出信任边界','按任务过滤工具','执行前校验身份与范围','敏感动作审批','结果验证和审计'],inputs:['身份','任务范围','工具权限'],outputs:['允许、拒绝或待审批'],applications:['企业 Agent','本地文件助手'],pitfalls:['默认开放全部工具','日志记录敏感正文'],prerequisites:['agent-architecture'],related:['guardrails-prompt-injection','mcp-security','tool-selection-filtering']},
{slug:'agent-orchestration',title:'Agent 编排',difficulty:'挑战',subcategory:'Agent',entityType:'agent',summary:'选择确定性代码、Manager、Handoff、Agents as Tools 或并行方式组织多个能力。',definition:'编排定义控制权、任务拆分、状态传递、聚合和失败处理。',background:'把所有分支都交给模型会降低可预测性；把所有路径硬编码又会失去开放任务适应性。',intuition:'固定铁路适合稳定路线，智能调度适合需求变化；关键枢纽仍要用明确规则。',principles:['高风险边界使用确定性代码。','Manager 适合统一最终输出；Handoff 适合专家接管对话。','组合模式时必须定义控制权何时转移和如何返回。'],steps:['识别确定性与开放决策','选择编排模式','定义交接载荷','限制共享状态','聚合与验证'],inputs:['任务图','Agent 能力','成本与风险约束'],outputs:['执行图','最终负责人','失败回退路径'],applications:['多 Agent 系统'],pitfalls:['控制权循环转移','子任务契约含糊'],prerequisites:['single-vs-multi-agent'],related:['manager-pattern','handoffs','agents-as-tools'],sourceUrls:['https://openai.github.io/openai-agents-js/guides/multi-agent/']},
{slug:'handoffs',title:'Handoff',difficulty:'挑战',subcategory:'Agent',entityType:'agent',summary:'把当前对话控制权从分流 Agent 转交给专业 Agent。',definition:'在 OpenAI Agents SDK 中，Handoff 作为模型可见的类函数工具，但调用后进入专门的交接路径，由目标 Agent 接管后续对话。',background:'当专家需要直接与用户交流、使用自己的指令和工具时，交接比让主管代为转述更自然。',intuition:'前台确认问题类型后把电话真正转给专家，而不是每句话都通过前台中转。',principles:['Handoff 与 agent.asTool() 不同：前者转移控制，后者由 Manager 保持控制。','交接输入 Schema 传递模型在交接时决定的元数据，不等同于应用上下文。','授权依赖参数时，应在 onHandoff 开始处、任何副作用之前检查。'],steps:['分流 Agent 识别领域','生成交接调用与必要载荷','应用验证目标和权限','目标 Agent 接管上下文','目标 Agent 产生最终输出'],inputs:['目标 Agent','交接参数','过滤后的历史'],outputs:['新的活动 Agent','交接轨迹'],applications:['客服分流','多语言专家'],pitfalls:['把 Handoff 当普通函数工具','未过滤不必要历史','在授权前产生副作用'],prerequisites:['agent-orchestration'],related:['agents-as-tools','manager-pattern'],sourceUrls:['https://openai.github.io/openai-agents-js/guides/handoffs/']},
{slug:'agents-as-tools',title:'Agents as Tools',difficulty:'挑战',subcategory:'Agent',entityType:'agent',summary:'把专业 Agent 包装成主管 Agent 可调用的工具，主管保持对话控制并汇总结果。',definition:'Agents as Tools 让一个 Agent 作为另一个 Agent 的函数工具运行，用于有边界的专业子任务。',background:'有时专家只需要返回材料，不应接管用户对话；主管还要统一格式、规则和最终判断。',intuition:'负责人把分析任务交给专家，专家交回报告，但最终由负责人向用户汇报。',principles:['Manager 始终拥有最终回答责任。','子 Agent 输入应收窄为必要任务，输出应有明确契约。','嵌套运行增加延迟与成本，需要追踪父子关系。'],steps:['定义专业 Agent','包装为具名工具','主管选择并调用','专家返回结果','主管验证并汇总'],inputs:['边界明确的子任务'],outputs:['供主管使用的专业结果'],applications:['研究摘要','领域分析'],pitfalls:['子 Agent 直接承担最终责任','输出契约不明确'],prerequisites:['agent-orchestration'],related:['manager-pattern','handoffs'],sourceUrls:['https://openai.github.io/openai-agents-js/guides/tools/']},
{slug:'manager-pattern',title:'Manager Pattern',difficulty:'挑战',subcategory:'Agent',entityType:'agent',summary:'由一个主管 Agent 持有会话、调用专业 Agent 工具并组合最终输出。',definition:'Manager Pattern 是 Agents as Tools 的系统级使用方式，主管集中施加格式、护栏和汇总策略。',background:'统一责任有利于结果一致性，但主管可能成为上下文、成本和错误聚合瓶颈。',intuition:'总编分派记者调查不同主题，最后自己核对并编辑成一篇文章。',principles:['主管需知道每个专家的能力边界。','专家结果必须带证据和失败状态。','共享护栏不能替代每个高风险工具自己的校验。'],steps:['主管拆分任务','选择一个或多个专家','收集结构化结果','检查冲突与证据','输出最终答案'],inputs:['用户任务','专家工具目录'],outputs:['统一最终答案'],applications:['多领域研究'],pitfalls:['主管上下文膨胀','重复调用专家'],prerequisites:['agents-as-tools'],related:['agent-orchestration','tracing-observability']},
{slug:'tool-selection-filtering',title:'Tool Selection 与 Tool Filtering',difficulty:'挑战',subcategory:'Tool',entityType:'tool',summary:'用描述帮助模型选对工具，用过滤和策略确保只暴露当前任务允许的工具。',definition:'Selection 是模型在可见工具中选择；Filtering 是应用在模型看到之前按身份、任务和风险缩小集合。',background:'工具越多，选择成本与误调用概率越高；隐藏不允许工具比仅在提示中说“不要用”更可靠。',intuition:'菜单说明帮助点菜，门禁决定哪些房间根本不会出现在可进入列表。',principles:['工具名和描述要区分用途与返回形状。','过滤必须发生在可信应用层。','Remote MCP 可用 allowed_tools 缩小导入集合；敏感动作结合 require_approval。'],steps:['按身份和任务生成允许集合','提供清晰描述','模型选择工具','执行层再次授权','记录选择与拒绝'],inputs:['全部工具目录','用户权限','当前任务'],outputs:['最小可见工具集'],applications:['大型工具库','MCP 集成'],pitfalls:['向模型暴露全部写工具','描述高度相似'],prerequisites:['tools','mcp-overview'],related:['agent-security','mcp-security'],sourceUrls:[openaiMcp,'https://openai.github.io/openai-agents-js/guides/context/']},
{slug:'tracing-observability',title:'Agent Tracing 与可观测性',difficulty:'挑战',subcategory:'Agent',entityType:'agent',summary:'记录任务、Agent、轮次、模型生成、工具、Handoff、护栏和错误的因果轨迹。',definition:'Tracing 用层级 span 还原一次 Agent 运行发生了什么；可观测性再结合指标与日志判断质量、成本和异常。',background:'最终答案不足以解释错在模型、工具、路由、权限还是状态。',intuition:'像快递轨迹，每次交接、处理和异常都有时间与责任节点。',principles:['OpenAI Agents SDK 当前默认追踪 run、agent、turn、generation、function、guardrail 与 handoff 等事件。','敏感输入输出应可选择不进入追踪。','trace id、工具调用 id 和业务幂等键应能关联。'],steps:['定义 workflow 名称','记录层级 span','附加版本、耗时和状态','脱敏敏感字段','用失败案例回放'],inputs:['运行事件','时间与标识','安全过滤策略'],outputs:['轨迹树','延迟、错误与成本指标'],applications:['故障定位','Agent 评测'],pitfalls:['只写自然语言日志','追踪泄露敏感数据'],prerequisites:['agent-architecture'],related:['agent-evaluation','agent-reliability'],sourceUrls:['https://openai.github.io/openai-agents-js/guides/tracing/']},
{slug:'guardrails-prompt-injection',title:'Guardrails 与 Prompt Injection',difficulty:'挑战',subcategory:'安全',entityType:'agent',summary:'在输入、输出和工具执行边界验证内容，并把外部指令视为不可信数据。',definition:'Guardrail 是阻止或转换不符合策略的输入、输出或工具调用的确定性/模型化检查；Prompt Injection 是不可信内容试图改变 Agent 指令或诱导越权。',background:'单纯提醒模型“忽略恶意内容”不能提供强安全保证，尤其在工具能产生副作用时。',intuition:'护栏像安检和权限网关，不是贴在墙上的“请勿进入”。',principles:['OpenAI Agents SDK 区分 input、output 和 function tool guardrails，作用边界不同。','工具护栏不自动覆盖 Handoff 或所有托管工具，应逐类确认。','审批发生前后都可能需要校验，且外部副作用不可被事后护栏撤销。'],steps:['标记不可信来源','执行前输入与权限校验','敏感动作审批','执行后输出校验','记录拒绝原因'],inputs:['用户输入','外部内容','工具参数和结果'],outputs:['允许、拒绝、替换或人工升级'],applications:['文件与网页 Agent','业务写操作'],pitfalls:['把护栏当万能沙箱','只检查最终文本'],prerequisites:['agent-security'],related:['mcp-security','tool-selection-filtering'],sourceUrls:['https://openai.github.io/openai-agents-js/guides/guardrails/']},
{slug:'codex-skills',title:'Skill 与 Codex Skills',difficulty:'进阶',subcategory:'Skill',entityType:'skill',summary:'Skill 用可复用的说明、参考资料和可选脚本，让 Agent 稳定遵循一类任务流程。',definition:'OpenAI 当前文档将 Skill 描述为包含 instructions、resources 与 optional scripts 的能力包；Codex 以包含 SKILL.md 的目录组织 Skill。',background:'把长流程反复粘进 Prompt 难以维护、测试和版本化；Skill 把稳定方法从一次性任务输入中分离。',intuition:'Prompt 是这次工作的请求，Skill 是一本会在合适任务中启用的作业手册。Tool 是手里的器械，MCP 是连接外部器械和资料的协议。',principles:['SKILL.md 必含 name 与 description 元数据以及完整指令。','目录可含 scripts/、references/、assets/，以及可选 agents/openai.yaml。','Skills 使用渐进式披露：先加载名称与描述，命中任务后再读取完整 SKILL.md，相关资源按需读取。','Skill 默认是指导流程，不必直接执行外部动作；它可以说明何时及如何使用 Tool。','Skill 应聚焦一个工作，写清输入输出，测试触发边界并随变更维护版本。'],steps:['确定一个稳定且可复用的工作','写清触发范围与不适用范围','在 SKILL.md 编写可执行步骤','把长资料放 references','仅把确定性或外部操作放 scripts','准备模板到 assets','用正反例测试触发与结果','记录版本和兼容性'],inputs:['任务描述','Skill 元数据','按需加载的参考资料'],outputs:['Agent 应遵循的流程','可选脚本或资产产生的结果'],applications:['文档制作流程','代码审查规范','本地数据处理'],pitfalls:['把 Skill 当成 Tool','description 太宽导致误触发','所有参考资料一次加载','脚本没有输入验证'],prerequisites:['prompt-instructions-context','tools'],related:['tools','mcp-overview','agent-skill-tool-mcp-comparison'],interactiveDemo:'capability-comparison',sourceUrls:[codexSkills,'https://agentskills.io/'],sourceSections:['Build skills / Skill structure','How ChatGPT and Codex use skills','Best practices'],executionEnvironment:'ChatGPT 或 Codex 的 Skill 运行环境；本页仅静态展示',readOnly:true,code:{title:'最小 SKILL.md 与目录结构',language:'Markdown',purpose:'展示当前 OpenAI 文档所述的必需文件、渐进加载资源和清晰触发描述。',source:`my-skill/\n├─ SKILL.md\n├─ references/\n│  └─ checklist.md\n├─ scripts/\n│  └─ validate.py\n└─ assets/\n   └─ report-template.md\n\n---\nname: local-report-review\ndescription: Review a local report against the supplied checklist. Use only when a report file is provided.\n---\n\n1. Read the report and identify its format.\n2. Load references/checklist.md only when checking coverage.\n3. Run scripts/validate.py only after validating the input path.\n4. Return findings, evidence, and unresolved questions.`,explanation:['name 和 description 用于发现与匹配。','正文给出命令式步骤和明确输入输出。','references、scripts、assets 按需使用，不应无条件全部加载。'],expectedOutput:'Agent 在匹配的报告审查任务中读取完整 SKILL.md，并按需加载检查表或运行验证脚本。'}},
{slug:'tools',title:'Tools：能力、Schema 与执行边界',difficulty:'进阶',subcategory:'Tool',entityType:'tool',summary:'Tool 把读取、计算或行动封装成有名称、输入、输出、权限和错误契约的能力。',definition:'Tool 是 Agent 可以请求调用、由宿主或服务执行的具体能力。它可以是内置工具、函数工具、API、本地文件/搜索/代码/计算工具，或另一个 Agent。',background:'模型训练参数无法自动访问最新数据或真实系统；工具连接外部能力，同时引入权限、副作用和失败处理。',intuition:'Skill 是操作手册，Tool 是真正完成动作的仪器；说明书不会自己钻孔，电钻也不会决定项目流程。',principles:['完整工具契约包含名称、描述、输入 Schema、输出 Schema、错误、权限、超时和副作用。','调用过程为选择—参数生成—验证—审批—执行—结果验证—反馈。','重试必须区分只读、幂等写入与非幂等副作用。','日志记录调用 id、工具版本、参数摘要、审批、耗时和结果状态。'],steps:['定义单一职责工具','编写输入输出 Schema','标记只读或写入与权限','执行前验证和审批','设置超时与有限重试','返回结构化成功或错误','验证结果并记录日志'],inputs:['工具名','结构化参数','授权与调用上下文'],outputs:['结构化数据','副作用确认','可分类错误'],applications:['内置搜索','函数与 API','本地文件','代码与数学计算','Agent as Tool'],pitfalls:['自然语言描述代替 Schema','错误没有分类','写操作无审批和幂等性','工具结果未经验证'],prerequisites:['llm-and-agent'],related:['tool-calling','function-calling','mcp-overview','codex-skills'],interactiveDemo:'tool-call',sourceUrls:[openaiTools,'https://openai.github.io/openai-agents-js/guides/tools/'],permissions:['每次调用按身份与资源重新授权','敏感或写入操作默认审批'],approvalRequired:true,readOnly:false},
{slug:'mcp-overview',title:'MCP：统一连接工具与上下文',difficulty:'进阶',subcategory:'MCP',entityType:'mcp',summary:'Model Context Protocol 用标准消息和能力协商连接宿主、Client 与提供 Tool、Resource、Prompt 的 Server。',definition:'MCP 全称 Model Context Protocol。它规定 Client 与 Server 如何发现和调用能力，不等同于某个具体工具、API 或 Agent。',background:'每个应用都为每个数据源手写连接器会形成 N×M 集成；协议把发现、调用和内容类型标准化。',intuition:'MCP 像通用插座规范：Server 提供插口后的工具与资料，Client 负责连接，Agent 决定何时使用；插座本身不替你完成任务。',principles:['MCP Server 可提供 Tool、Resource 与 Prompt；当前官方规范中三者控制方式不同。','Client 管理连接、能力发现、请求与响应，并把允许的能力交给宿主应用。','普通 API 是某服务的业务接口；MCP 在其上提供面向模型/Agent 的统一发现与调用约定。','函数调用定义应用内工具接口；MCP 可从独立 Server 动态提供工具和资源。','Skill 描述工作方法；MCP 描述通信与能力暴露。'],steps:['用户任务进入 Agent','Agent 查看 Client 暴露的允许能力','MCP Client 与 Server 协商并发现能力','Agent 选择 Tool 或请求 Resource','Client 发送协议请求','Server 执行并返回结构化结果','Agent 验证结果并继续或完成'],inputs:['Server 地址或本地进程配置','协议请求','授权信息'],outputs:['工具列表','资源或 Prompt 元数据','调用结果或协议错误'],applications:['本地文件服务','远程业务服务','统一工具目录'],pitfalls:['把 MCP 当 Agent','默认信任任意 Server','暴露全部写工具','混淆 Streamable HTTP 中使用 SSE 与旧 HTTP+SSE 传输'],prerequisites:['tools','client-server-basics'],related:['mcp-client-server','mcp-transports','mcp-security','agent-skill-tool-mcp-comparison'],interactiveDemo:'mcp-flow',sourceUrls:[openaiMcp,mcpSpec,'https://modelcontextprotocol.io/specification/2026-07-28/server'],sourceSections:['OpenAI / MCP and Connectors','MCP 2026-07-28 / Server primitives','MCP / Transports'],transport:['stdio（本地子进程）','Streamable HTTP（当前标准远程传输）','旧 HTTP+SSE（已弃用，仅兼容迁移）'],approvalRequired:true,readOnly:false},
{slug:'mcp-client-server',title:'MCP Client、Server、Tool、Resource 与 Prompt',difficulty:'进阶',subcategory:'MCP',entityType:'mcp',summary:'拆分 MCP 各角色及发现、请求、响应和控制权。',definition:'Client 位于宿主应用中并连接 Server；Server 暴露 Tool、Resource 与 Prompt；Tool 执行动作，Resource 提供上下文，Prompt 提供可参数化模板。',background:'把所有 MCP 能力都叫“工具”会忽略资源读取、用户选择 Prompt 和不同权限模型。',intuition:'Client 像前台，Server 像服务柜台；Tool 是办理业务，Resource 是可查资料，Prompt 是预制申请模板。',principles:['当前 MCP 规范把 Tools 描述为模型控制、Resources 为应用控制、Prompts 为用户控制的教学性控制层次。','能力发现先于调用，Client 可以过滤 Server 宣告的集合。','Server 宣告能力不等于用户已授权每次调用。'],steps:['建立连接与能力协商','列出 tools/resources/prompts','按任务与权限过滤','发出带 id 的请求','接收 result 或 error','把结果交回宿主'],inputs:['JSON-RPC 请求','能力与参数'],outputs:['JSON-RPC 响应','内容块或错误'],applications:['插件式能力接入'],pitfalls:['Server 宣告即自动授权','工具、资源和 Prompt 混用'],prerequisites:['mcp-overview'],related:['mcp-transports','mcp-security'],sourceUrls:[mcpSpec,'https://modelcontextprotocol.io/specification/2026-07-28/server']},
{slug:'mcp-transports',title:'MCP 传输：stdio、Streamable HTTP 与旧 SSE',difficulty:'挑战',subcategory:'MCP',entityType:'mcp',summary:'按本地进程与远程 HTTP 场景选择当前传输，并明确旧 HTTP+SSE 的弃用状态。',definition:'传输规定 Client 与 Server 如何承载协议消息；它不改变 Tool、Resource、Prompt 的语义。',background:'MCP 早期 HTTP+SSE 方案已被 Streamable HTTP 替代，旧教程若不标日期会误导新实现。',intuition:'同一份协议消息可以走本地管道或网络公路，但路线、认证和攻击面不同。',principles:['stdio 由 Client 启动本地 Server 子进程，通过标准输入输出交换消息。','Streamable HTTP 是当前远程标准；2026-07-28 规范进一步转向无状态核心和基于请求的交互。','旧 HTTP+SSE 自 2025-03-26 被 Streamable HTTP 替代，2026-07-28 官方说明其正式弃用并提供一年迁移窗口。','OpenAI Responses API 当前 Remote MCP 文档仍说明兼容 Streamable HTTP 或 HTTP/SSE；新实现应优先 Streamable HTTP，兼容不等于推荐。'],steps:['判断本地还是远程','本地优先评估 stdio','远程使用当前 Streamable HTTP','配置认证与来源校验','旧 Server 仅在迁移期兼容'],inputs:['协议消息','进程管道或 HTTPS 请求'],outputs:['协议响应或流式事件'],applications:['本地开发','远程 MCP 服务'],pitfalls:['把 SSE 事件流等同于旧 HTTP+SSE 传输','新项目继续采用旧双端点设计'],prerequisites:['mcp-overview'],related:['mcp-client-server','mcp-security'],sourceUrls:[openaiMcp,'https://modelcontextprotocol.io/specification/2026-07-28/basic/transports','https://blog.modelcontextprotocol.io/posts/2026-07-28/'],sourceSections:['MCP 2026-07-28 / Transports','MCP 2026-07-28 release / Deprecations'],transport:['stdio：当前','Streamable HTTP：当前推荐','HTTP+SSE：已弃用，迁移兼容'],performance:['stdio 启动简单但受本机进程生命周期影响。','远程 HTTP 需要处理网络延迟、认证、重试与速率限制。']},
{slug:'mcp-security',title:'MCP 权限、安全与信任',difficulty:'挑战',subcategory:'MCP',entityType:'mcp',summary:'把 Server、能力发现、工具调用、资源内容和远程认证分别置于明确的信任边界。',definition:'MCP 安全不是协议连接成功后的附加项，而是 Server 选择、工具过滤、最小权限、审批、结果校验和审计的组合。',background:'远程 Server 可能返回恶意内容或随时间改变工具行为；写工具还可能造成不可逆副作用。',intuition:'接上扩展坞不代表里面每个设备都可信，更不代表每次写入都无需确认。',principles:['OpenAI Remote MCP 指南强调只连接受信任 Server，并对敏感动作使用 require_approval 与 allowed_tools。','只读和写入能力应分离标记；最小权限同时限制工具集合与资源范围。','Server 返回的文本是数据，不应自动成为高优先级指令。','审批必须显示具体工具、目标和参数，不能只问“是否允许继续”。'],steps:['验证 Server 来源与所有者','发现后按 allowlist 过滤工具','对读取限定路径/数据范围','写操作逐次审批','校验结果和副作用','记录调用与撤销/恢复信息'],inputs:['Server 身份','工具元数据','调用参数','用户授权'],outputs:['允许、拒绝或待审批','审计记录'],applications:['远程 MCP','企业数据连接'],pitfalls:['信任未知 Server','require_approval 设为 never 后暴露写工具','工具列表变化不审查'],prerequisites:['mcp-overview','agent-security'],related:['tool-selection-filtering','guardrails-prompt-injection'],sourceUrls:[openaiMcp,'https://modelcontextprotocol.io/specification/2026-07-28/basic/security_best_practices'],approvalRequired:true,readOnly:false,permissions:['Server allowlist','工具 allowlist','资源级最小权限','敏感动作逐次审批']},
{slug:'local-mcp-server',title:'本地 MCP Server',difficulty:'挑战',subcategory:'MCP',entityType:'mcp',summary:'通过 stdio 或本机 Streamable HTTP 暴露受限的本地工具与资源。',definition:'本地 MCP Server 是在用户机器上运行、由 Client 连接的 MCP 服务进程。',background:'本地部署避免把资料发送给远程服务，但仍可能读写本机文件，权限边界同样重要。',intuition:'它像只在电脑内部开放的服务窗口，距离近不等于权限无限。',principles:['stdio Server 的 stdout 只能输出协议消息，日志应写 stderr。','启动参数和工作目录必须明确，避免继承过宽环境。','只暴露白名单目录与必要工具，写操作单独审批。'],steps:['定义只读工具','限制根目录','启动 stdio Server','Client 连接并列出工具','验证调用与关闭进程'],inputs:['本地进程命令','允许目录'],outputs:['本地工具和资源'],applications:['本地文档读取','开发工具'],pitfalls:['把整个磁盘作为根目录','stdout 混入日志破坏协议'],prerequisites:['mcp-client-server','mcp-transports'],related:['mcp-security','tools'],sourceUrls:['https://openai.github.io/openai-agents-js/guides/mcp/',mcpSpec],executionEnvironment:'本地子进程或 localhost',approvalRequired:true,readOnly:true},
{slug:'agent-skill-tool-mcp-comparison',title:'Agent、Skill、Tool、MCP 的区别',difficulty:'进阶',subcategory:'核心对照',entityType:'comparison',summary:'用职责、流程、行动、连接、权限和复用方式辨析四个常被混用的概念。',definition:'Agent 组织目标与行动；Skill 提供可复用流程和专业规范；Tool 执行具体动作；MCP 以协议连接 Client 与外部能力。',background:'四者可以组合，但不构成固定产品层级；不同平台的实现细节必须回到各自官方文档。',intuition:'读取本地 PDF 时：模型理解意图，Agent 安排任务，Skill 规定阅读和总结流程，PDF Tool 读取文件，MCP 可把外部文件服务统一提供给 Agent。',principles:['Agent：解决“谁推进任务并判断完成”。','Skill：解决“这类任务应遵循什么流程和资料”。','Tool：解决“具体动作如何执行并返回结果”。','MCP：解决“宿主如何用统一协议发现和调用外部能力”。','模型是上述系统的推断与生成组件，但不自动拥有工具权限。'],steps:['模型理解用户要求','Agent 根据目标组织步骤','匹配 Skill 并加载流程','选择 PDF 读取 Tool','若工具由 MCP Server 提供，则经 Client 调用','验证读取结果','Agent 按 Skill 生成带来源总结'],inputs:['用户任务','Skill 说明','Tool Schema','MCP 能力目录'],outputs:['受控执行轨迹','最终总结'],applications:['架构沟通','能力选型','安全审查'],pitfalls:['把 Skill 当成可执行 API','把 MCP 当成 Agent','认为 Tool Schema 自动授权','认为 Plugin 与 Skill 完全同义'],prerequisites:['intelligent-agent','codex-skills','tools','mcp-overview'],related:['agent-architecture','local-mcp-server'],interactiveDemo:'capability-comparison',sourceUrls:[codexSkills,openaiTools,openaiMcp,openaiAgents,mcpSpec],sourceSections:['OpenAI Build skills','OpenAI Function calling','OpenAI MCP and Connectors','OpenAI Agents SDK'],capabilities:['概念对照','本地 PDF 示例','职责边界检查']},
{slug:'agent-reliability',title:'Agent 可靠性与可观测性',difficulty:'挑战',subcategory:'Agent',entityType:'agent',summary:'通过契约、限制、幂等、评测、追踪和人工升级提高端到端任务成功率。',definition:'可靠性是系统在正常与异常条件下持续满足明确验收标准，并能解释和恢复失败的能力。',background:'模型、工具、网络、状态和权限都是独立失败源，端到端可靠性通常低于任一局部组件分数。',intuition:'可靠系统不只“通常能做”，还知道什么时候不能做、失败在哪里以及如何安全重试。',principles:['每个边界都使用结构化输入输出契约。','限制步数、时间、成本和副作用。','离线评测、线上追踪和人工反馈形成闭环。'],steps:['定义 SLO 与验收集','为工具添加超时和幂等','记录完整轨迹','注入故障测试','分析并回归'],inputs:['评测任务','运行轨迹','故障事件'],outputs:['成功率、恢复率、延迟与错误预算'],applications:['生产 Agent'],pitfalls:['只测顺利路径','把重试当万能恢复'],prerequisites:['agent-evaluation','tracing-observability'],related:['agent-error-handling','agent-security']}
];

export const aiLongForms:AILongFormConcept[]=seeds.map(make);
