export type {
  Category,
  CategorySlug,
  Concept,
  Difficulty,
} from './content-base';
export { categories, categoryMap } from './content-base';
import type { Concept } from './content-base';
import { concepts as baseConcepts } from './content-base';
import { expandedConcepts } from './expanded-content';
import { documentConcepts } from './long-form-content';

const mlPath = [
  'machine-learning-overview',
  'supervised-learning',
  'classification-vs-regression',
  'unsupervised-learning',
  'semi-and-self-supervised-learning',
  'dataset-shapes',
  'training-prediction-generalization',
  'train-validation-test-split',
  'ml-project-lifecycle',
  'underfitting-overfitting',
  'scalars-vectors-matrices',
  'dot-product-weighted-sum',
  'mean-variance-standard-deviation',
  'probability-and-thresholds',
  'conditional-probability-bayes',
  'euclidean-distance',
  'gradient-descent',
  'mse-rmse',
  'cross-entropy',
  'gini-impurity',
  'bias-variance-learning-curves',
  'numpy-data-operations',
  'preprocessing-fit-transform-boundary',
  'data-quality-audit',
  'missing-value-imputation',
  'categorical-encoding',
  'numerical-standardization',
  'min-max-scaling',
  'robust-scaling-and-outliers',
  'learning-rate-selection',
  'gradient-descent-convergence',
  'class-imbalance',
  'feature-construction',
  'skewed-and-cyclical-features',
  'future-information-leakage',
  'feature-selection',
  'sklearn-pipeline-column-transformer',
  'data-preprocessing',
  'feature-engineering',
  'linear-regression',
  'logistic-regression',
  'regularization-l1-l2',
  'linear-model-interpretation',
  'linear-model-scope',
  'knn',
  'naive-bayes',
  'support-vector-machines',
  'model-family-comparison',
  'decision-trees',
  'bagging',
  'random-forest',
  'adaboost',
  'gradient-boosting-trees',
  'bagging-vs-boosting',
  'tree-feature-importance',
  'kmeans-and-silhouette',
  'hierarchical-clustering',
  'dbscan',
  'principal-component-analysis',
  'unsupervised-evaluation',
  'pca-clustering',
  'evaluation-design',
  'confusion-matrix',
  'classification-metrics',
  'regression-metrics',
  'baseline-models',
  'hyperparameter-search',
  'data-leakage',
  'error-analysis',
  'model-evaluation',
  'l1-regularization',
  'proximal-gradient-soft-thresholding',
  'lasso-regression',
  'l1-logistic-regression',
  'elastic-net',
  'overfitting-diagnosis',
  'unsupervised-overfitting',
  'overfitting-regularization',
  'cross-validation',
  'cross-validation-splitters',
  'group-cross-validation',
  'time-series-cross-validation',
  'cv-pipeline-leakage',
  'cross-validation-scoring',
  'nested-cross-validation',
  'cross-val-predict',
  'cross-validation-reporting',
  'end-to-end-ml-project',
  'sklearn-model-persistence',
  'inference-input-contract',
  'model-monitoring-and-drift',
  'digits-ml-project',
  'digits-model-comparison',
  'digits-error-analysis',
  'digits-project-delivery',
  'ml-experiment-reporting',
];
const learningPath = [
  'ai-overview',
  'state-space-search',
  'knowledge-representation',
  'generative-ai',
  ...mlPath,
  'pytorch-tensors-modules',
  'artificial-neuron',
  'neural-networks',
  'activation-functions',
  'data-pipeline',
  'epoch-batch-iteration',
  'loss-functions',
  'backpropagation',
  'gradient-initialization',
  'normalization',
  'optimizers-schedulers',
  'dl-evaluation-imbalance',
  'deep-learning-regularization',
  'convolutional-neural-networks',
  'residual-networks',
  'transfer-learning',
  'detection-segmentation',
  'embeddings-sequences',
  'rnn-lstm-gru',
  'transformer',
  'deep-generative-models',
  'training-engineering',
  'model-debugging',
  'model-saving-inference',
  'agent-environment',
  'state-action-reward',
  'markov-decision-process',
  'q-learning',
  'policy-gradient',
];
const order = new Map(learningPath.map((slug, index) => [slug, index]));
const merged = new Map<string, Concept>();
for (const item of [...baseConcepts, ...expandedConcepts, ...documentConcepts])
  merged.set(item.slug, item);
export const concepts: Concept[] = [...merged.values()].sort(
  (a, b) => (order.get(a.slug) ?? 999) - (order.get(b.slug) ?? 999),
);
export const conceptMap = Object.fromEntries(
  concepts.map((item) => [item.slug, item]),
) as Record<string, Concept>;
export const getConceptsByCategory = (category: string) =>
  concepts.filter((item) => item.category === category);
