import { deep, type DeepLearningLongFormConcept } from './deep-learning-types';
const n = (
  title: string,
  given: string[],
  steps: string[],
  result: string,
  comparison: string[] = [],
) => ({ title, given, steps, result, comparison });
const base = (
  slug: string,
  title: string,
  file: string,
  sections: string[],
  formula: string,
  code: string,
  related: string[],
  pitfalls: string[],
  summary: string,
  principle: string,
): DeepLearningLongFormConcept =>
  deep({
    slug,
    title,
    subcategory:
      file.startsWith('18') || file.startsWith('19')
        ? '序列与 Transformer'
        : file.startsWith('20') ||
            file.startsWith('21') ||
            file.startsWith('22')
          ? '视觉进阶'
          : file.startsWith('23')
            ? '生成模型'
            : '训练工程',
    difficulty: '进阶',
    summary,
    definition: summary,
    background: `${title}是该文档中连接数据表示、训练目标和工程实现的核心主题。`,
    importance: [
      `掌握${title}的输入输出与训练边界`,
      '能够用 PyTorch 代码验证公式和形状',
    ],
    objectives: [
      '解释核心机制',
      '手算一个主要形状或公式',
      '运行完整示例并排查错误',
    ],
    intuition: `把${title}理解为数据在模型中的一套明确变换，而不是只记一个类名。`,
    principle,
    details:
      '实现时必须同时检查 shape、dtype、mask 或模式切换，并用验证集而不是测试集选择配置。',
    formula,
    formulaDescription: `${title}的核心数学表达。`,
    variables: [
      { symbol: 'N', meaning: 'batch size' },
      { symbol: 'D/H', meaning: '特征或隐藏维度' },
    ],
    numeric: n(
      `${title}数值/形状检查`,
      ['N=8', 'D=64'],
      ['按公式或模块逐步计算', '核对输出 shape'],
      '输出保持 batch 维并符合任务头约定',
    ),
    steps: [
      '确认输入与目标',
      '建立最小模块',
      '随机张量前向',
      '计算损失',
      '反向与更新',
      '验证与错误分析',
    ],
    code,
    codeNotes: [
      '代码显式标注输入和输出',
      '使用框架稳定实现',
      '结果通过 shape 或数值检查',
    ],
    expected: '打印与页面说明一致的张量形状或损失。',
    applications: [title, '教学与项目基线'],
    pitfalls,
    prerequisites: ['PyTorch Tensor', '神经网络训练循环'],
    related,
    file,
    sections,
    questions: [
      {
        question: `${title}最先检查什么？`,
        answer: '先检查输入输出 shape、dtype 和数据边界。',
      },
      { question: '何时使用测试集？', answer: '全部设计锁定后最终评估。' },
    ],
  });
export const deepLearningAdvanced: DeepLearningLongFormConcept[] = [
  base(
    'recurrent-neural-network',
    '循环神经网络 RNN',
    '18_RNN_LSTM与GRU.md',
    ['§1 状态', '§3 RNN 单元', '§4 输出形式', '§5 BPTT'],
    'h_t=\\tanh(W_{xh}x_t+W_{hh}h_{t-1}+b)',
    `rnn=nn.RNN(64,128,batch_first=True)\nx=torch.randn(8,20,64)\nout,h=rnn(x)\nprint(out.shape,h.shape)`,
    ['rnn-lstm-gru', 'lstm', 'gru'],
    ['长依赖梯度消失', 'padding 更新状态', 'batch_first 误解'],
    'RNN 用共享循环单元和隐藏状态把历史信息传向后续时间步。',
    '同一参数跨时间共享，BPTT 沿状态链反向传播。',
  ),
  base(
    'lstm',
    'LSTM',
    '18_RNN_LSTM与GRU.md',
    ['§6 LSTM', '§8 PyTorch', '§11 packing'],
    'c_t=f_t\\odot c_{t-1}+i_t\\odot g_t,\\quad h_t=o_t\\odot\\tanh(c_t)',
    `lstm=nn.LSTM(64,128,batch_first=True)\nx=torch.randn(8,20,64)\nout,(h,c)=lstm(x)\nprint(out.shape,h.shape,c.shape)`,
    ['recurrent-neural-network', 'gru', 'sequence-padding-and-masks'],
    ['忘记 c_n', 'output[:,-1] 取 padding', '以为永不梯度消失'],
    'LSTM 用输入门、遗忘门、输出门和细胞状态缓解长距离依赖训练。',
    '门值是连续软控制，细胞状态提供更直接的信息通路。',
  ),
  base(
    'gru',
    'GRU',
    '18_RNN_LSTM与GRU.md',
    ['§7 GRU', '§8 PyTorch'],
    'h_t=(1-z_t)\\odot n_t+z_t\\odot h_{t-1}',
    `gru=nn.GRU(64,128,batch_first=True)\nx=torch.randn(8,20,64)\nout,h=gru(x)\nprint(out.shape,h.shape)`,
    ['recurrent-neural-network', 'lstm'],
    ['门公式命名方向混淆', '认为总优于 LSTM', 'padding 未处理'],
    'GRU 用重置门和更新门在旧状态与新候选之间平滑选择。',
    'GRU 状态更简洁，参数与计算通常少于 LSTM，但优劣需验证。',
  ),
  base(
    'rnn-lstm-gru',
    'RNN、LSTM 与 GRU 总览',
    '18_RNN_LSTM与GRU.md',
    ['§2 形状', '§5 梯度', '§8–16 PyTorch 与变长序列'],
    'output:[N,L,directions\\cdot H],\\quad h_n:[layers\\cdot directions,N,H]',
    `x=torch.randn(8,20,64)\nfor cls in (nn.RNN,nn.GRU,nn.LSTM):\n    model=cls(64,128,batch_first=True)\n    result=model(x);print(cls.__name__,result[0].shape)`,
    ['recurrent-neural-network', 'lstm', 'gru'],
    ['双向用于在线预测', 'h_n 维度错', '跨样本复用状态'],
    '三类循环网络共享时间参数，但状态结构和长依赖能力不同。',
    '选择取决于序列长度、速度、在线约束和验证结果。',
  ),
  base(
    'attention',
    '缩放点积注意力',
    '19_注意力机制与Transformer.md',
    ['§2 QKV', '§3 缩放点积', '§4 自/交叉注意力'],
    'Attention(Q,K,V)=softmax(QK^T/\\sqrt{d_k}+M)V',
    `q=torch.randn(2,5,8);k=torch.randn(2,5,8);v=torch.randn(2,5,8)\ns=q@k.transpose(-2,-1)/(8**.5)\nw=s.softmax(-1);out=w@v\nprint(s.shape,out.shape)`,
    ['multi-head-attention', 'transformer-masks', 'transformer'],
    ['Softmax 轴错', '忘除 sqrt(dk)', 'Softmax 后 mask'],
    '注意力让每个 Query 直接按匹配程度读取所有允许的 Value。',
    '先算分数、屏蔽禁止位置、对 Key 维 Softmax，再加权 Value。',
  ),
  base(
    'multi-head-attention',
    '多头注意力',
    '19_注意力机制与Transformer.md',
    ['§7 多头注意力', '§8 手写模块'],
    'd_h=D/H,\\quad MultiHead=Concat(head_1,...,head_H)W^O',
    `mha=nn.MultiheadAttention(256,8,batch_first=True)\nx=torch.randn(4,20,256)\ny,w=mha(x,x,x)\nprint(y.shape,w.shape)`,
    ['attention', 'transformer'],
    ['D 不能整除头数', '换轴后错误 view', '把头解释为固定语法'],
    '多头注意力在多个投影子空间并行建立关系并合并回模型维度。',
    '每头维度 D/H，分数典型为 [N,H,Lq,Lk]。',
  ),
  base(
    'transformer-masks',
    'Transformer Mask',
    '19_注意力机制与Transformer.md',
    ['§5 padding/causal mask', '§14 目标右移', '§16 形状表'],
    'M_{ij}=0\\;allowed,\\quad M_{ij}=-\\infty\\;blocked',
    `L=5\ncausal=torch.triu(torch.ones(L,L,dtype=torch.bool),diagonal=1)\nvalid=torch.tensor([[1,1,1,0,0]],dtype=torch.bool)\nkey_padding=~valid\nprint(causal.shape,key_padding.shape)`,
    ['sequence-padding-and-masks', 'attention', 'transformer'],
    ['valid/padding 方向反', 'mask 轴错', '所有 Key 被屏蔽', '生成忘 causal'],
    'Mask 防止读取 padding 或未来标签，是序列模型正确性的边界条件。',
    '禁止位置必须在 Softmax 前屏蔽；训练生成还需目标右移。',
  ),
  base(
    'transformer',
    'Transformer',
    '19_注意力机制与Transformer.md',
    ['§9 位置编码', '§10 编码器层', '§12 三类架构', '§17 复杂度'],
    'FFN(x)=W_2\\phi(W_1x+b_1)+b_2,\\quad cost=O(L^2)',
    `layer=nn.TransformerEncoderLayer(256,8,1024,batch_first=True,norm_first=True)\nx=torch.randn(4,20,256)\ny=layer(x)\nprint(y.shape)`,
    [
      'attention',
      'multi-head-attention',
      'transformer-masks',
      'layer-normalization',
    ],
    ['没有位置表示', 'padding 参与池化', '架构与预训练权重不匹配'],
    'Transformer 由注意力、前馈网络、残差、归一化和位置表示组成。',
    '注意力负责位置间通信，FFN 逐位置变换，全局注意力长度成本为二次。',
  ),
  base(
    'residual-networks',
    '残差连接与现代 CNN',
    '20_残差连接与现代CNN.md',
    ['§2 深度退化', '§3 残差公式', '§4 1×1', '§5–7 现代结构'],
    'y=F(x)+shortcut(x)',
    `block=nn.Sequential(nn.Conv2d(64,128,3,stride=2,padding=1),nn.BatchNorm2d(128))\nshortcut=nn.Conv2d(64,128,1,stride=2)\nx=torch.randn(8,64,32,32)\nprint(block(x).shape,shortcut(x).shape)`,
    ['convolutional-neural-networks', 'gradient-initialization'],
    ['两分支形状不同', '把相加写拼接', '层越深一定越准'],
    '残差连接提供信息与梯度捷径，使深层网络更容易优化。',
    '形状变化时用 1×1 stride 投影匹配主分支。',
  ),
  base(
    'transfer-learning',
    '迁移学习与微调',
    '21_迁移学习与微调.md',
    ['§1 迁移学习', '§3 策略', '§5–7 冻结与 BN', '§9 阶段框架'],
    '\\theta_{backbone}\\leftarrow\\theta_{pretrained},\\quad lr_{backbone}<lr_{head}',
    `for p in model.parameters():p.requires_grad=False\nin_features=model.fc.in_features\nmodel.fc=nn.Linear(in_features,5)\noptimizer=torch.optim.AdamW(model.fc.parameters(),lr=1e-3)`,
    ['residual-networks', 'batch-normalization', 'optimizers-schedulers'],
    ['先换头再全冻结', '解冻未入 optimizer', '预处理不匹配', 'BN 统计未管理'],
    '迁移学习复用预训练表示，固定特征、全量微调或逐步解冻。',
    '新头通常较大学习率，预训练层较小；权重预处理是模型资产。',
  ),
  base(
    'detection-segmentation',
    '目标检测与图像分割',
    '22_目标检测与图像分割.md',
    ['§1 任务', '§2 张量', '§5 损失', '§6–8 IoU/NMS/mAP', '§9–10 PyTorch'],
    'IoU=|A\\cap B|/|A\\cup B|',
    `def iou(a,b):\n    x1=max(a[0],b[0]);y1=max(a[1],b[1]);x2=min(a[2],b[2]);y2=min(a[3],b[3])\n    inter=max(0,x2-x1)*max(0,y2-y1)\n    return inter/((a[2]-a[0])*(a[3]-a[1])+(b[2]-b[0])*(b[3]-b[1])-inter)\nprint(iou([0,0,4,4],[2,2,6,6]))`,
    ['convolutional-neural-networks', 'transfer-learning'],
    ['框格式混用', '只变图不变标注', 'mask 双线性插值', '测试调 NMS'],
    '检测预测类别/框，分割预测像素；评价需 IoU、AP/mAP 或 mIoU。',
    '数据标注格式、同步增强和评估协议比模型名字更先确认。',
  ),
  base(
    'vae',
    '变分自编码器 VAE',
    '23_生成模型_VAE_GAN与扩散模型.md',
    ['§4 VAE'],
    'z=\\mu+\\sigma\\odot\\epsilon,\\quad L=L_{recon}+\\beta L_{KL}',
    `mu=torch.zeros(8,32);logvar=torch.zeros(8,32)\nstd=torch.exp(.5*logvar);z=mu+std*torch.randn_like(std)\nprint(z.shape)`,
    ['deep-generative-models', 'diffusion-models'],
    ['logvar 当 std', 'KL/recon reduction 不一致', 'β 过大潜变量失效'],
    'VAE 用概率潜空间、重参数化和 KL 正则支持从先验采样。',
    '编码器输出 mu/logvar，随机性移到 epsilon，使梯度可传播。',
  ),
  base(
    'gan',
    '生成对抗网络 GAN',
    '23_生成模型_VAE_GAN与扩散模型.md',
    ['§5 GAN'],
    '\\min_G\\max_D\\ E[\\log D(x)]+E[\\log(1-D(G(z)))]',
    `z=torch.randn(16,64)\nfake=generator(z)\nreal_logits=discriminator(real)\nfake_logits=discriminator(fake.detach())\nloss_d=bce(real_logits,torch.ones_like(real_logits))+bce(fake_logits,torch.zeros_like(fake_logits))`,
    ['deep-generative-models', 'vae'],
    ['D 更新忘 detach', 'G 更新错误 detach', '只看 loss', '模式崩溃'],
    'GAN 由生成器与判别器交替对抗，采样快但训练可能不稳定。',
    '判别器更新隔离生成器梯度；生成器更新必须通过判别器反传。',
  ),
  base(
    'diffusion-models',
    '扩散模型',
    '23_生成模型_VAE_GAN与扩散模型.md',
    ['§6 扩散'],
    'x_t=\\sqrt{\\bar\\alpha_t}x_0+\\sqrt{1-\\bar\\alpha_t}\\epsilon',
    `t=torch.randint(0,alpha_bar.numel(),(x0.size(0),),device=x0.device)\nnoise=torch.randn_like(x0)\na=alpha_bar[t].view(-1,1,1,1)\nxt=a.sqrt()*x0+(1-a).sqrt()*noise\nloss=F.mse_loss(denoiser(xt,t),noise)`,
    ['deep-generative-models', 'vae'],
    ['系数不 reshape', 'alpha/beta 混淆', '训练采样参数化不匹配', '忘时间步'],
    '扩散模型学习不同时间步去噪，从噪声多步生成样本。',
    '训练常预测加入噪声，采样必须使用匹配调度与参数化。',
  ),
  base(
    'deep-generative-models',
    'AE、VAE、GAN 与扩散模型',
    '23_生成模型_VAE_GAN与扩散模型.md',
    ['§1–2 总览', '§3 AE', '§4 VAE', '§5 GAN', '§6 Diffusion'],
    'generation\\ objective\\ depends\\ on\\ model\\ family',
    `x=torch.rand(16,1,28,28)\nx_hat,z=autoencoder(x)\nloss=F.mse_loss(x_hat,x);loss.backward()\nprint(x_hat.shape,z.shape)`,
    ['vae', 'gan', 'diffusion-models'],
    ['AE 重建好即能随机采样', '输出范围不匹配', '不同 loss 横比'],
    '生成模型学习重建、潜分布、对抗或去噪目标，采样过程各不相同。',
    '必须分别记录损失组成、固定采样条件并评价质量与多样性。',
  ),
  base(
    'deep-learning-directions',
    '深度学习方向地图',
    '24_深度学习其他方向概览.md',
    ['§1 层级', '§3–9 各方向', '§10–14 选择与路线'],
    'model+training\\ paradigm+problem\\ setting+application',
    `directions=['GNN','self-supervised','multimodal','deep RL','audio','time series','recommendation']\nfor name in directions:print(name)`,
    ['deep-generative-models', 'transformer', 'agent-environment'],
    ['看到序列就 Transformer', '忽略简单基线', '数据量等于独立样本'],
    '区分模型家族、训练范式、问题设定和应用领域，再按数据结构选择路线。',
    '该页严格作为文档方向地图，不把概览内容伪装成完整专题。',
  ),
  base(
    'automatic-mixed-precision',
    '自动混合精度 AMP',
    '25_训练工程实践_GPU混合精度复现与检查点.md',
    ['§7 AMP', '§8 裁剪'],
    'scaled\\ loss=s\\cdot L,\\quad g=\\nabla(sL)/s',
    `use_amp=device.type=='cuda'\nscaler=torch.amp.GradScaler('cuda',enabled=use_amp)\nwith torch.amp.autocast('cuda',enabled=use_amp):loss=criterion(model(x),y)\nscaler.scale(loss).backward();scaler.step(optimizer);scaler.update()`,
    ['training-engineering', 'gradient-clipping'],
    ['整个模型强制 float16', '裁剪前不 unscale', 'NaN 不关闭 AMP 定位'],
    'AMP 为适合操作选择低精度，并用 GradScaler 缓解 float16 梯度下溢。',
    '它可能省显存和提速，但效果依赖硬件，异常时应关闭定位。',
  ),
  base(
    'training-engineering',
    '可靠训练工程',
    '25_训练工程实践_GPU混合精度复现与检查点.md',
    ['§1–6 设备复现数据', '§7–17 AMP/检查点', '§18–23 性能'],
    'reliable=code+data+config+state+metrics',
    `checkpoint={'epoch':epoch,'model':model.state_dict(),'optimizer':optimizer.state_dict(),'scheduler':scheduler.state_dict(),'best':best}\ntorch.save(checkpoint,'checkpoint.pt')`,
    ['automatic-mixed-precision', 'model-debugging', 'model-saving-inference'],
    [
      '只保存最后模型',
      '恢复漏 optimizer',
      'batch loss 平均有偏',
      '只设一个 seed',
    ],
    '训练工程让实验正确、可恢复、可比较、可复现。',
    '保存模型、优化器、调度器、scaler、进度与配置；先正确再性能优化。',
  ),
  base(
    'model-debugging',
    '深度学习模型调试',
    '26_深度学习模型调试指南.md',
    ['§1 顺序', '§3 极小 batch', '§4–14 shape/梯度/NaN', '§15–22 排查'],
    'debug:data\\to shape\\to loss\\to grad\\to update\\to tiny\\ batch',
    `x,y=next(iter(loader));print(x.shape,x.dtype,y.shape,y.dtype)\nlogits=model(x);loss=criterion(logits,y);loss.backward()\nfor name,p in model.named_parameters():print(name,p.grad is None)`,
    ['training-engineering', 'pytorch-autograd'],
    ['先换大模型', '静默广播', '随意 detach', 'retain_graph 掩盖错误'],
    '调试按数据、shape/dtype、前向损失、梯度、参数更新、极小 batch 和曲线顺序。',
    '拟合 8–32 个样本是最有价值的综合检查之一。',
  ),
  base(
    'model-saving-inference',
    '模型保存、加载、推理与部署',
    '27_模型保存加载推理与部署.md',
    ['§2–7 state_dict', '§8–16 推理', '§17–22 部署监控'],
    'artifact=configuration+state\\_dict+preprocess+labels',
    `artifact={'model_config':config,'model_state_dict':model.state_dict(),'class_names':names,'preprocess':prep}\ntorch.save(artifact,'model.pt')\nloaded=torch.load('model.pt',map_location='cpu',weights_only=True)`,
    ['training-engineering', 'inference-input-contract'],
    [
      '只保存权重',
      '忘 eval',
      '预处理不一致',
      '类别映射丢失',
      '加载不可信 pickle',
    ],
    '模型资产包括结构配置、权重、预处理、类别映射、版本和评估范围。',
    '推理同时使用 eval 与 inference_mode；保存/加载后用固定样本做一致性测试。',
  ),
  base(
    'mnist-end-to-end-project',
    '端到端 MNIST CNN 项目',
    '28_端到端项目_MNIST手写数字分类.md',
    ['§1 项目', '§5–10 数据模型', '§12–15 训练验证测试', '§16–23 推理分析'],
    '[N,1,28,28]\\to[N,10],\\quad L=CrossEntropy(logits,y)',
    `model=MNISTCNN().to(device)\ntrain_metrics=train_one_epoch(model,train_loader,criterion,optimizer,device)\nval_metrics=evaluate(model,val_loader,criterion,device)\nif val_metrics['loss']<best:torch.save(model.state_dict(),'best.pt')`,
    [
      'convolutional-neural-networks',
      'training-engineering',
      'model-saving-inference',
    ],
    ['首批不检查', '测试参与调参', '保存最后非最佳', '训练前 Softmax'],
    'MNIST 项目连接数据、CNN、训练、验证最佳检查点、测试、错误样本和单样本推理。',
    '输入 [N,1,28,28]，输出 10 logits；验证选择最佳，测试最终一次。',
  ),
];
