import type { LearningResource } from './resources';

// Reviewed public references; descriptions and exercises are written for this site.
export const additionalResources: LearningResource[] = [
  {
    id: 'ai-effective-workflows',
    title: 'Agent 与工作流：何时增加自主性',
    type: '技术文章',
    category: 'artificial-intelligence',
    subcategory: 'Agent 架构',
    summary:
      '比较固定工作流与自主 Agent，结合路由、并行和停止条件选择实现方式。',
    author: 'Anthropic',
    platform: 'Anthropic',
    difficulty: '进阶',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://www.anthropic.com/engineering/building-effective-agents',
    conceptSlugs: ['agent-architecture', 'agent-loop', 'single-vs-multi-agent'],
    prerequisites: ['LLM 基础'],
    tags: ['Agent 架构', '技术文章', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '文章中的模式仍可用于学习；具体 SDK 接口以当前文档为准。',
  },
  {
    id: 'ai-tool-design-evals',
    title: '为 Agent 设计可用的工具',
    type: '技术文章',
    category: 'artificial-intelligence',
    subcategory: '工具设计',
    summary:
      '从工具命名、参数、返回信息和评测任务入手，减少误调用并提高可诊断性。',
    author: 'Anthropic',
    platform: 'Anthropic',
    difficulty: '进阶',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://www.anthropic.com/engineering/writing-tools-for-agents',
    conceptSlugs: ['tools', 'function-calling', 'tool-selection-filtering'],
    prerequisites: ['LLM 基础'],
    tags: ['工具设计', '技术文章', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '适合配合一个只读工具做小规模对照实验。',
  },
  {
    id: 'ai-contextual-retrieval',
    title: 'Contextual Retrieval：检索上下文与重排',
    type: '技术文章',
    category: 'artificial-intelligence',
    subcategory: 'RAG',
    summary:
      '解释分块丢失语境的问题，以及结合上下文、关键词检索和重排的处理思路。',
    author: 'Anthropic',
    platform: 'Anthropic',
    difficulty: '进阶',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://www.anthropic.com/engineering/contextual-retrieval',
    conceptSlugs: [
      'retrieval-augmented-generation',
      'prompt-instructions-context',
    ],
    prerequisites: ['LLM 基础'],
    tags: ['RAG', '技术文章', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '文中效果来自特定实验，不能直接视为自己数据上的收益。',
  },
  {
    id: 'ai-agent-evals-practice',
    title: 'Agent 评测：任务、轨迹与结果',
    type: '技术文章',
    category: 'artificial-intelligence',
    subcategory: '评测',
    summary:
      '梳理任务、试验、评分器与运行轨迹，帮助区分最终结果和工具执行过程。',
    author: 'Anthropic',
    platform: 'Anthropic',
    difficulty: '进阶',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents',
    conceptSlugs: [
      'agent-evaluation',
      'tracing-observability',
      'agent-reliability',
    ],
    prerequisites: ['LLM 基础'],
    tags: ['评测', '技术文章', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '建议自建包含失败案例的小型评测集。',
  },
  {
    id: 'ai-hf-agents-course',
    title: 'Hugging Face AI Agents Course',
    type: '代码教程',
    category: 'artificial-intelligence',
    subcategory: 'Agent 入门',
    summary:
      '通过课程单元和实践介绍 Agent、工具及常见框架，适合从概念走向小项目。',
    author: 'Hugging Face',
    platform: 'Hugging Face',
    difficulty: '入门',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://huggingface.co/learn/agents-course/en/unit0/introduction',
    conceptSlugs: ['intelligent-agent', 'agent-loop', 'tools'],
    prerequisites: ['LLM 基础'],
    tags: ['Agent 入门', '代码教程', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '课程材料免费；部分模型调用或托管实践可能需要账号或额度。',
  },
  {
    id: 'ai-langgraph-stateful',
    title: 'LangGraph：有状态 Agent 工作流',
    type: 'GitHub 仓库',
    category: 'artificial-intelligence',
    subcategory: '状态与编排',
    summary: '通过开源图式编排实现持久化执行、人机协作与有状态工作流。',
    author: 'LangChain',
    platform: 'GitHub',
    difficulty: '进阶',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://github.com/langchain-ai/langgraph',
    conceptSlugs: [
      'agent-state-memory',
      'agent-orchestration',
      'agent-error-handling',
    ],
    prerequisites: ['LLM 基础'],
    tags: ['状态与编排', 'GitHub 仓库', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '本地示例需要安装依赖；连接模型服务时可能产生费用。',
    github: {
      purpose: '通过开源图式编排实现持久化执行、人机协作与有状态工作流。',
      primaryLanguage: 'Python / TypeScript',
      includesDatasetOrExperiments: true,
      requiresExtraEnvironment: true,
    },
  },
  {
    id: 'ml-common-pitfalls',
    title: 'scikit-learn 常见陷阱与推荐实践',
    type: '官方文档',
    category: 'machine-learning',
    subcategory: '数据泄漏',
    summary: '通过错误与正确示例解释预处理一致性、数据泄漏和随机状态管理。',
    author: 'scikit-learn developers',
    platform: 'scikit-learn',
    difficulty: '入门',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://scikit-learn.org/stable/common_pitfalls.html',
    conceptSlugs: [
      'cv-pipeline-leakage',
      'feature-selection',
      'numerical-standardization',
    ],
    prerequisites: ['Python', '训练与测试划分'],
    tags: ['数据泄漏', '官方文档', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '先读数据泄漏章节，再把预处理放入 Pipeline。',
  },
  {
    id: 'ml-cv-guide',
    title: '交叉验证与划分器选择指南',
    type: '官方文档',
    category: 'machine-learning',
    subcategory: '交叉验证',
    summary:
      '对比普通、分层、分组和时间序列划分，说明验证方案与数据结构的关系。',
    author: 'scikit-learn developers',
    platform: 'scikit-learn',
    difficulty: '进阶',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://scikit-learn.org/stable/modules/cross_validation.html',
    conceptSlugs: [
      'cross-validation',
      'time-series-cross-validation',
      'nested-cross-validation',
    ],
    prerequisites: ['Python', '训练与测试划分'],
    tags: ['交叉验证', '官方文档', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '示例中的随机划分不适用于所有时间或群组数据。',
  },
  {
    id: 'ml-metrics-guide',
    title: '分类与回归指标计算指南',
    type: '官方文档',
    category: 'machine-learning',
    subcategory: '评估指标',
    summary: '集中查阅混淆矩阵、F1、回归误差和评分接口，适合手算后核对实现。',
    author: 'scikit-learn developers',
    platform: 'scikit-learn',
    difficulty: '入门',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://scikit-learn.org/stable/modules/model_evaluation.html',
    conceptSlugs: ['classification-metrics', 'mse-rmse', 'model-evaluation'],
    prerequisites: ['Python', '训练与测试划分'],
    tags: ['评估指标', '官方文档', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '注意正类约定、平均方式以及零分母处理。',
  },
  {
    id: 'ml-permutation-guide',
    title: 'Permutation Importance 与相关特征',
    type: '官方文档',
    category: 'machine-learning',
    subcategory: '模型解释',
    summary:
      '解释置换重要性的计算与局限，特别是模型质量和特征相关性对解释的影响。',
    author: 'scikit-learn developers',
    platform: 'scikit-learn',
    difficulty: '进阶',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://scikit-learn.org/stable/modules/permutation_importance.html',
    conceptSlugs: ['feature-selection', 'model-evaluation'],
    prerequisites: ['Python', '训练与测试划分'],
    tags: ['模型解释', '官方文档', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '重要性描述模型在给定数据和指标上的依赖，不是因果效应。',
  },
  {
    id: 'ml-calibration-guide',
    title: '概率校准与可靠性曲线',
    type: '官方文档',
    category: 'machine-learning',
    subcategory: '概率预测',
    summary: '理解概率可信度、校准曲线及校准器训练数据的独立性。',
    author: 'scikit-learn developers',
    platform: 'scikit-learn',
    difficulty: '进阶',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://scikit-learn.org/stable/modules/calibration.html',
    conceptSlugs: ['probability-and-thresholds', 'classification-metrics'],
    prerequisites: ['Python', '训练与测试划分'],
    tags: ['概率预测', '官方文档', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '分类正确率高不代表预测概率已经校准。',
  },
  {
    id: 'ml-imbalanced-learn',
    title: 'imbalanced-learn：不平衡数据实践',
    type: 'GitHub 仓库',
    category: 'machine-learning',
    subcategory: '类别不平衡',
    summary:
      '提供过采样、欠采样及兼容 scikit-learn 的流水线，便于比较不平衡处理策略。',
    author: 'imbalanced-learn developers',
    platform: 'GitHub',
    difficulty: '进阶',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://github.com/scikit-learn-contrib/imbalanced-learn',
    conceptSlugs: ['class-imbalance', 'cv-pipeline-leakage'],
    prerequisites: ['Python', '训练与测试划分'],
    tags: ['类别不平衡', 'GitHub 仓库', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '重采样应限定在训练折内部，保留验证和测试的自然分布。',
    github: {
      purpose:
        '提供过采样、欠采样及兼容 scikit-learn 的流水线，便于比较不平衡处理策略。',
      primaryLanguage: 'Python',
      includesDatasetOrExperiments: true,
      requiresExtraEnvironment: true,
    },
  },
  {
    id: 'dl-autograd-basics',
    title: 'PyTorch 自动微分入门',
    type: '代码教程',
    category: 'deep-learning',
    subcategory: '梯度与计算图',
    summary:
      '学习计算图、requires_grad、反向传播和停止梯度，适合定位梯度链路问题。',
    author: 'PyTorch contributors',
    platform: 'PyTorch',
    difficulty: '入门',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://docs.pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html',
    conceptSlugs: ['pytorch-autograd', 'backpropagation'],
    prerequisites: ['Python', '线性代数'],
    tags: ['梯度与计算图', '代码教程', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '先用可手算的标量函数检查导数。',
  },
  {
    id: 'dl-optimization-loop',
    title: 'PyTorch 优化循环教程',
    type: '代码教程',
    category: 'deep-learning',
    subcategory: '训练循环',
    summary:
      '按步骤构建训练和评估循环，理解损失、梯度清零、反向传播和参数更新。',
    author: 'PyTorch contributors',
    platform: 'PyTorch',
    difficulty: '入门',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://docs.pytorch.org/tutorials/beginner/basics/optimization_tutorial.html',
    conceptSlugs: ['neural-network-training-loop', 'optimizers-schedulers'],
    prerequisites: ['Python', '线性代数'],
    tags: ['训练循环', '代码教程', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '建议先在 CPU 和小数据上核对训练步骤。',
  },
  {
    id: 'dl-transfer-tutorial',
    title: '计算机视觉迁移学习实战',
    type: '代码教程',
    category: 'deep-learning',
    subcategory: '迁移学习',
    summary: '比较预训练网络微调与固定特征提取，展示训练过程和分类头替换。',
    author: 'PyTorch contributors',
    platform: 'PyTorch',
    difficulty: '进阶',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://docs.pytorch.org/tutorials/beginner/transfer_learning_tutorial.html',
    conceptSlugs: ['transfer-learning', 'batch-normalization'],
    prerequisites: ['Python', '线性代数'],
    tags: ['迁移学习', '代码教程', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '需要下载示例数据和模型权重；留意冻结参数与训练模式的区别。',
  },
  {
    id: 'dl-sdpa-tutorial',
    title: '缩放点积注意力与 SDPA',
    type: '代码教程',
    category: 'deep-learning',
    subcategory: 'Transformer',
    summary:
      '用 PyTorch 学习缩放点积注意力、掩码及实现差异，并观察性能测量方法。',
    author: 'PyTorch contributors',
    platform: 'PyTorch',
    difficulty: '进阶',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://docs.pytorch.org/tutorials/intermediate/scaled_dot_product_attention_tutorial.html',
    conceptSlugs: ['transformer', 'sequence-padding-and-masks'],
    prerequisites: ['Python', '线性代数'],
    tags: ['Transformer', '代码教程', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '基础公式可在 CPU 学习；部分性能示例需要兼容 GPU。',
  },
  {
    id: 'dl-3b1b-neural-networks',
    title: '3Blue1Brown：神经网络是什么',
    type: '视频',
    category: 'deep-learning',
    subcategory: '神经网络直觉',
    summary:
      '以手写数字识别为例，通过动画和配套讲解理解神经元、权重、偏置与网络分层。',
    author: 'Grant Sanderson',
    platform: '3Blue1Brown',
    difficulty: '入门',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://www.3blue1brown.com/lessons/neural-networks/',
    conceptSlugs: ['neural-networks', 'artificial-neuron'],
    prerequisites: ['Python', '线性代数'],
    tags: ['神经网络直觉', '视频', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '提供视频与图文解释；可沿页面导航继续学习梯度下降与反向传播。',
  },
  {
    id: 'dl-d2l-chinese',
    title: '动手学深度学习：中文在线版',
    type: '书籍',
    category: 'deep-learning',
    subcategory: '中文系统课程',
    summary: '结合数学、图解与代码学习线性网络、卷积、序列模型和注意力。',
    author: '阿斯顿·张、李沐、扎卡里·C. 立顿、亚历山大·J. 斯莫拉',
    platform: 'D2L',
    difficulty: '入门',
    language: '中文',
    duration: null,
    isFree: true,
    url: 'https://zh.d2l.ai/',
    conceptSlugs: [
      'neural-networks',
      'dropout',
      'batch-normalization',
      'sequence-padding-and-masks',
    ],
    prerequisites: ['Python', '线性代数'],
    tags: ['中文系统课程', '书籍', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '中文在线正文免费；运行示例前核对所选框架及依赖版本。',
  },
  {
    id: 'rl-gym-basic-usage',
    title: 'Gymnasium 环境交互入门',
    type: '官方文档',
    category: 'reinforcement-learning',
    subcategory: '环境接口',
    summary: '从 reset、step、动作空间与观测空间开始编写可检查的环境交互循环。',
    author: 'Farama Foundation',
    platform: 'Gymnasium',
    difficulty: '入门',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://gymnasium.farama.org/introduction/basic_usage/',
    conceptSlugs: ['agent-environment', 'state-action-reward'],
    prerequisites: ['Python', '概率基础'],
    tags: ['环境接口', '官方文档', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '先用随机策略验证环境接口；渲染可单独开启。',
  },
  {
    id: 'rl-gym-time-limits',
    title: '终止、截断与 Bootstrap',
    type: '官方文档',
    category: 'reinforcement-learning',
    subcategory: '训练边界',
    summary:
      '区分任务自然终止和外部时间限制，正确处理 TD 目标及 episode 重置。',
    author: 'Farama Foundation',
    platform: 'Gymnasium',
    difficulty: '进阶',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://gymnasium.farama.org/tutorials/gymnasium_basics/handling_time_limits/',
    conceptSlugs: ['td-learning', 'q-learning', 'agent-environment'],
    prerequisites: ['Python', '概率基础'],
    tags: ['训练边界', '官方文档', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '不要把所有 episode 结束都直接当作没有未来回报。',
  },
  {
    id: 'rl-sb3-training-tips',
    title: 'Stable-Baselines3 训练与评测建议',
    type: '官方文档',
    category: 'reinforcement-learning',
    subcategory: '实验设计',
    summary: '整理环境检查、独立评测、动作归一化和算法选择等实践要点。',
    author: 'Stable-Baselines3 contributors',
    platform: 'Stable-Baselines3',
    difficulty: '进阶',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html',
    conceptSlugs: ['rl-evaluation-reproducibility', 'rl-algorithm-comparison'],
    prerequisites: ['Python', '概率基础'],
    tags: ['实验设计', '官方文档', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '掌握基础后再调参，记录种子和实际环境步数。',
  },
  {
    id: 'rl-sb3-repository',
    title: 'Stable-Baselines3 算法实现',
    type: 'GitHub 仓库',
    category: 'reinforcement-learning',
    subcategory: '算法基线',
    summary:
      '提供基于 PyTorch 的强化学习算法实现，可用于搭建 PPO、DQN 等可复现基线。',
    author: 'DLR-RM 与 Stable-Baselines3 contributors',
    platform: 'GitHub',
    difficulty: '进阶',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://github.com/DLR-RM/stable-baselines3',
    conceptSlugs: ['ppo', 'dqn', 'actor-critic'],
    prerequisites: ['Python', '概率基础'],
    tags: ['算法基线', 'GitHub 仓库', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '不同算法适用的动作空间不同，使用前核对支持表。',
    github: {
      purpose:
        '提供基于 PyTorch 的强化学习算法实现，可用于搭建 PPO、DQN 等可复现基线。',
      primaryLanguage: 'Python',
      includesDatasetOrExperiments: true,
      requiresExtraEnvironment: true,
    },
  },
  {
    id: 'rl-hf-q-learning',
    title: 'Hugging Face Q-Learning 图解',
    type: '代码教程',
    category: 'reinforcement-learning',
    subcategory: '表格型方法',
    summary: '逐步解释 Q 表、时序差分目标和离策略学习，适合手算更新后再编程。',
    author: 'Hugging Face',
    platform: 'Hugging Face',
    difficulty: '入门',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://huggingface.co/learn/deep-rl-course/en/unit2/q-learning',
    conceptSlugs: [
      'q-learning',
      'on-vs-off-policy',
      'exploration-exploitation',
    ],
    prerequisites: ['Python', '概率基础'],
    tags: ['表格型方法', '代码教程', '新增'],
    recommendationLevel: 'A',
    lastVerifiedAt: '2026-09-22',
    notes: '结合小型离散环境理解更新，不直接推广为连续动作算法。',
  },
  {
    id: 'rl-berkeley-cs285',
    title: 'Berkeley 深度强化学习课程',
    type: '视频课程',
    category: 'reinforcement-learning',
    subcategory: '系统进阶',
    summary:
      '课程主页提供讲义、录像与作业入口，覆盖策略梯度、价值方法和模型学习。',
    author: 'UC Berkeley',
    platform: 'UC Berkeley',
    difficulty: '挑战',
    language: '英语',
    duration: null,
    isFree: true,
    url: 'https://rail.eecs.berkeley.edu/deeprlcourse/',
    conceptSlugs: ['policy-gradient', 'actor-critic', 'model-free-vs-based'],
    prerequisites: ['Python', '概率基础'],
    tags: ['系统进阶', '视频课程', '新增'],
    recommendationLevel: 'B',
    lastVerifiedAt: '2026-09-22',
    notes: '按主页的学期导航选择完整课程；先准备概率、优化与深度学习基础。',
  },
];
