import type { StageQuestionInput } from './stage-test.ts';

/**
 * Curated stage-test question bank.
 *
 * Rules every entry must follow:
 * 1. The prompt states a concrete question; it is never "please complete a
 *    single-choice question about X".
 * 2. Objective entries have exactly one checkable answer set. `accept` contains
 *    equivalent spellings (Chinese/ASCII, LaTeX, unit variants) only.
 * 3. Free explanations use `concept-explanation`/`code-reading` and carry a
 *    `referenceAnswer`. They are shown for self-assessment and are never scored
 *    by string comparison.
 * 4. Every answer must be verifiable against the concept text in
 *    `lib/content-base.ts` / `lib/expanded-content.ts`.
 */
export const questionBank: Record<string, StageQuestionInput[]> = {
  // ---------------------------------------------------------------- 机器学习基础
  'supervised-learning': [
    {
      id: 'supervised-learning-q1',
      type: 'single-choice',
      prompt: '监督学习的训练数据必须包含哪两部分？',
      options: [
        '带标签样本的输入与目标',
        '只有输入特征',
        '环境的奖励信号',
        '一张有向图',
      ],
      correctOptions: ['带标签样本的输入与目标'],
      conceptSlug: 'supervised-learning',
      explanation: '监督学习从“题目—答案”对中学习输入到目标的映射。',
    },
    {
      id: 'supervised-learning-q2',
      type: 'multiple-choice',
      prompt: '下列关于监督学习的说法，哪些正确？',
      options: [
        '训练目标是最小化训练样本上的平均损失',
        '训练集准确率高就说明泛化一定好',
        '标签质量会限制模型能达到的上限',
        '在新数据上的表现才反映泛化',
      ],
      correctOptions: [
        '训练目标是最小化训练样本上的平均损失',
        '标签质量会限制模型能达到的上限',
        '在新数据上的表现才反映泛化',
      ],
      conceptSlug: 'supervised-learning',
      explanation: '训练集分数只反映拟合程度，泛化必须在未见数据上评估。',
    },
    {
      id: 'supervised-learning-q3',
      type: 'true-false',
      prompt:
        '判断：监督学习的目标是让训练集损失尽可能小，所以训练集准确率越高越好。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'supervised-learning',
      explanation: '只压低训练损失会记住噪声，评价标准是未见数据上的表现。',
    },
  ],
  'unsupervised-learning': [
    {
      id: 'unsupervised-learning-q1',
      type: 'single-choice',
      prompt: '无监督学习与监督学习最根本的区别是什么？',
      options: [
        '训练数据没有人工标签',
        '不需要任何算法',
        '不能处理数值特征',
        '一定比监督学习准确',
      ],
      correctOptions: ['训练数据没有人工标签'],
      conceptSlug: 'unsupervised-learning',
      explanation: '无监督学习只依据数据本身的结构、距离或分布发现规律。',
    },
    {
      id: 'unsupervised-learning-q2',
      type: 'true-false',
      prompt: '判断：K-Means 输出的簇编号可以直接当作真实类别编号来比较。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'unsupervised-learning',
      explanation: '簇编号是任意标识，编号置换不改变聚类结果。',
    },
    {
      id: 'unsupervised-learning-q3',
      type: 'multiple-choice',
      prompt: '使用 K-Means 时，下列哪些做法是必要的或有帮助的？',
      options: [
        '先统一各特征尺度',
        '指定簇的数量 K',
        '为每个样本提供人工标签',
        '检查簇是否具有业务含义',
      ],
      correctOptions: [
        '先统一各特征尺度',
        '指定簇的数量 K',
        '检查簇是否具有业务含义',
      ],
      conceptSlug: 'unsupervised-learning',
      explanation:
        'K-Means 依赖距离，需要尺度一致与 K 值选择；聚类不需要标签。',
    },
  ],
  'linear-regression': [
    {
      id: 'linear-regression-q1',
      type: 'single-choice',
      prompt: '线性回归用什么标准选择权重与偏置？',
      options: [
        '最小化预测值与真实值的平方误差之和',
        '最大化训练集准确率',
        '最大化簇间距离',
        '最小化模型参数量',
      ],
      correctOptions: ['最小化预测值与真实值的平方误差之和'],
      conceptSlug: 'linear-regression',
      explanation: '最小二乘法选择使平方误差之和最小的参数。',
    },
    {
      id: 'linear-regression-q2',
      type: 'formula-fill',
      prompt: '写出线性回归的预测表达式（用 w、x、b 表示）。',
      accept: [
        'y=w^Tx+b',
        'y=wᵀx+b',
        'y=wx+b',
        '\\hat y = w^T x + b',
        'w^Tx+b',
        'y=xw+b',
      ],
      conceptSlug: 'linear-regression',
      explanation: '预测值是特征的加权和加上偏置。',
    },
    {
      id: 'linear-regression-q3',
      type: 'true-false',
      prompt: '判断：线性回归系数显著说明特征与目标之间存在因果关系。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'linear-regression',
      explanation: '相关性不等于因果，系数只描述给定数据下的线性关联。',
    },
  ],
  'overfitting-regularization': [
    {
      id: 'overfitting-regularization-q1',
      type: 'single-choice',
      prompt: '训练误差很低而验证误差明显升高，最可能属于哪种情况？',
      options: ['过拟合', '欠拟合', '数据泄漏', '标签噪声'],
      correctOptions: ['过拟合'],
      conceptSlug: 'overfitting-regularization',
      explanation: '两者差距扩大是过拟合的典型信号，即记住了训练噪声。',
    },
    {
      id: 'overfitting-regularization-q2',
      type: 'single-choice',
      prompt: 'Ridge 回归中 alpha 从 1 增大到 100，通常会发生什么？',
      options: [
        '参数被压缩得更强，约束更强',
        '正则化变弱',
        '模型变成无监督学习',
        '训练误差一定降为 0',
      ],
      correctOptions: ['参数被压缩得更强，约束更强'],
      conceptSlug: 'overfitting-regularization',
      explanation: 'alpha 越大，权重平方惩罚越重。',
    },
    {
      id: 'overfitting-regularization-q3',
      type: 'concept-explanation',
      prompt: '用偏差与方差的说法解释正则化为什么能改善泛化。',
      referenceAnswer:
        '正则化在数据损失之外加入参数惩罚，限制模型自由度，降低模型对训练样本细节的敏感度，也就是降低方差；代价是训练集拟合变差、偏差上升。它的作用是在偏差与方差之间取得更好的平衡，从而让未见数据上的表现更稳定。',
      conceptSlug: 'overfitting-regularization',
      explanation: '回答需要同时提到方差下降与偏差上升的权衡。',
    },
  ],
  'training-prediction-generalization': [
    {
      id: 'training-prediction-generalization-q1',
      type: 'single-choice',
      prompt: '关于 fit 与 predict 的职责，哪个说法正确？',
      options: [
        'fit 学习模型状态，predict 只使用已学状态',
        'predict 会继续更新模型参数',
        'fit 只能用于神经网络',
        'predict 必须在训练集上调用',
      ],
      correctOptions: ['fit 学习模型状态，predict 只使用已学状态'],
      conceptSlug: 'training-prediction-generalization',
      explanation: '训练是改变模型内部状态，预测阶段状态冻结。',
    },
    {
      id: 'training-prediction-generalization-q2',
      type: 'true-false',
      prompt: '判断：泛化指的是模型在训练样本上的记忆程度。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'training-prediction-generalization',
      explanation: '泛化衡量的是模型对未见数据的有效性。',
    },
    {
      id: 'training-prediction-generalization-q3',
      type: 'multiple-choice',
      prompt: '哪些现象说明“训练分数高”不足以说明模型可用？',
      options: [
        '验证集分数明显更低',
        '换一批随机种子分数剧烈波动',
        '训练损失降到接近 0',
        '测试流程中测试集被反复查看并据此改方案',
      ],
      correctOptions: [
        '验证集分数明显更低',
        '换一批随机种子分数剧烈波动',
        '测试流程中测试集被反复查看并据此改方案',
      ],
      conceptSlug: 'training-prediction-generalization',
      explanation:
        '训练损失接近 0 本身只说明拟合充分，不能单独证明或否定泛化。',
    },
  ],
  'train-validation-test-split': [
    {
      id: 'train-validation-test-split-q1',
      type: 'single-choice',
      prompt: '测试集应该在什么时候使用？',
      options: [
        '所有模型选择与调参完成之后，评价一次',
        '每次调参都查看',
        '用于挑选特征',
        '只在训练集不够用时使用',
      ],
      correctOptions: ['所有模型选择与调参完成之后，评价一次'],
      conceptSlug: 'train-validation-test-split',
      explanation: '反复查看测试结果会让测试集间接参与选择，使分数过于乐观。',
    },
    {
      id: 'train-validation-test-split-q2',
      type: 'single-choice',
      prompt: '预测未来销量时，为什么不能随机划分训练集与测试集？',
      options: [
        '随机划分会让未来信息进入训练集，造成时间泄漏',
        '随机划分会减少样本量',
        '随机划分无法分层',
        '随机划分不能用于回归',
      ],
      correctOptions: ['随机划分会让未来信息进入训练集，造成时间泄漏'],
      conceptSlug: 'train-validation-test-split',
      explanation: '时间数据必须按时间顺序划分，训练集只能来自测试集之前。',
    },
    {
      id: 'train-validation-test-split-q3',
      type: 'calculation',
      prompt: '1000 条样本按 test_size=0.2 划分，测试集有多少条？',
      accept: ['200', '200条', '200 条'],
      conceptSlug: 'train-validation-test-split',
      explanation: '1000 × 0.2 = 200。',
    },
  ],
  'classification-vs-regression': [
    {
      id: 'classification-vs-regression-q1',
      type: 'single-choice',
      prompt: '“判断邮件是否为垃圾邮件”属于哪类任务？',
      options: ['分类', '回归', '聚类', '降维'],
      correctOptions: ['分类'],
      conceptSlug: 'classification-vs-regression',
      explanation: '输出是离散类别，因此是分类。',
    },
    {
      id: 'classification-vs-regression-q2',
      type: 'single-choice',
      prompt: '“预测明天的气温”属于哪类任务？',
      options: ['回归', '分类', '聚类', '排序'],
      correctOptions: ['回归'],
      conceptSlug: 'classification-vs-regression',
      explanation: '输出是有数值距离意义的连续量，因此是回归。',
    },
    {
      id: 'classification-vs-regression-q3',
      type: 'true-false',
      prompt: '判断：把类别编号当作连续数值直接做回归是合理的做法。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'classification-vs-regression',
      explanation: '类别编号之间不存在大小关系，当作连续值会引入不存在的距离。',
    },
  ],
  'machine-learning-overview': [
    {
      id: 'machine-learning-overview-q1',
      type: 'single-choice',
      prompt: '与传统手写规则程序相比，机器学习的核心差别是什么？',
      options: [
        '由算法根据数据与训练目标寻找参数',
        '不需要定义任何目标',
        '一定不需要评估',
        '只能处理图像',
      ],
      correctOptions: ['由算法根据数据与训练目标寻找参数'],
      conceptSlug: 'machine-learning-overview',
      explanation: '规则由人书写，模型参数由数据与训练目标决定。',
    },
    {
      id: 'machine-learning-overview-q2',
      type: 'multiple-choice',
      prompt: '一个可验收的机器学习任务应至少明确哪些内容？',
      options: ['输入与输出', '标签定义', '评价指标', '真实使用条件'],
      correctOptions: ['输入与输出', '标签定义', '评价指标', '真实使用条件'],
      conceptSlug: 'machine-learning-overview',
      explanation: '缺少任何一项都无法判断模型是否解决了真实问题。',
    },
    {
      id: 'machine-learning-overview-q3',
      type: 'true-false',
      prompt: '判断：只要模型在测试集上分数高，就可以直接上线并停止维护。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'machine-learning-overview',
      explanation: '上线后还需要监控输入分布与真实效果的变化。',
    },
  ],
  'dataset-shapes': [
    {
      id: 'dataset-shapes-q1',
      type: 'single-choice',
      prompt:
        'sklearn 中 X.shape = (n_samples, n_features) 的两个维度分别表示什么？',
      options: [
        '第一维是样本数，第二维是特征数',
        '第一维是特征数，第二维是样本数',
        '两维都是样本数',
        '两维都是特征数',
      ],
      correctOptions: ['第一维是样本数，第二维是特征数'],
      conceptSlug: 'dataset-shapes',
      explanation: 'X 的行为样本、列为特征，y 的长度必须等于样本数。',
    },
    {
      id: 'dataset-shapes-q2',
      type: 'true-false',
      prompt: '判断：可以对 X 和 y 分别打乱，只要两个顺序都随机就等价。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'dataset-shapes',
      explanation: 'X 的第 i 行必须与 y 的第 i 项保持配对，必须使用相同索引。',
    },
    {
      id: 'dataset-shapes-q3',
      type: 'code-output',
      prompt:
        'X = np.arange(12).reshape(3, 4)，则 X.shape 是多少？写出形如 (a, b) 的结果。',
      accept: ['(3,4)', '3,4', '3*4', '(3, 4)'],
      conceptSlug: 'dataset-shapes',
      explanation: '12 个元素分成 3 行 4 列。',
    },
  ],
  'naive-bayes': [
    {
      id: 'naive-bayes-q1',
      type: 'single-choice',
      prompt: '朴素贝叶斯中的“朴素”指什么假设？',
      options: [
        '给定类别后各特征条件独立',
        '所有类别概率相等',
        '特征必须服从正态分布',
        '样本之间必须独立同分布',
      ],
      correctOptions: ['给定类别后各特征条件独立'],
      conceptSlug: 'naive-bayes',
      explanation: '该假设让联合概率可以拆成各特征似然的乘积。',
    },
    {
      id: 'naive-bayes-q2',
      type: 'code-output',
      prompt:
        '先验为 [0.4, 0.6]，似然为 [0.3, 0.1]，归一化后的后验约是多少？（写出第一个值，保留三位小数）',
      accept: ['0.667', '0.6667', '2/3', '0.67'],
      conceptSlug: 'naive-bayes',
      explanation: '0.4×0.3=0.12，0.6×0.1=0.06，归一化后为 0.12/0.18≈0.667。',
    },
    {
      id: 'naive-bayes-q3',
      type: 'true-false',
      prompt:
        '判断：朴素贝叶斯的特征独立假设在现实中往往不成立，因此它的概率估计通常是准确校准的。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'naive-bayes',
      explanation: '假设不成立时概率校准会受影响，但仍常能给出可用的类别排序。',
    },
  ],
  knn: [
    {
      id: 'knn-q1',
      type: 'single-choice',
      prompt: 'KNN 为什么通常必须与标准化组合使用？',
      options: [
        '距离会被数值范围大的特征主导',
        'KNN 只能处理正态分布数据',
        '标准化可以减少邻居数量',
        'KNN 的参数需要标准化才能初始化',
      ],
      correctOptions: ['距离会被数值范围大的特征主导'],
      conceptSlug: 'knn',
      explanation: 'KNN 直接使用距离，未标准化时大尺度特征会主导结果。',
    },
    {
      id: 'knn-q2',
      type: 'multiple-choice',
      prompt: '关于 K 的取值，下列哪些说法正确？',
      options: [
        'K 太小对噪声敏感、方差高',
        'K 太大会过度平均局部差异',
        'K 应通过交叉验证选择',
        'K 越大模型一定越好',
      ],
      correctOptions: [
        'K 太小对噪声敏感、方差高',
        'K 太大会过度平均局部差异',
        'K 应通过交叉验证选择',
      ],
      conceptSlug: 'knn',
      explanation: 'K 是控制偏差与方差权衡的超参数。',
    },
    {
      id: 'knn-q3',
      type: 'true-false',
      prompt: '判断：KNN 的主要计算发生在预测阶段，而不是训练阶段。',
      options: ['正确', '错误'],
      correctOptions: ['正确'],
      conceptSlug: 'knn',
      explanation: 'KNN 几乎不做参数训练，预测时需要与训练样本计算距离。',
    },
  ],
  'decision-trees': [
    {
      id: 'decision-trees-q1',
      type: 'single-choice',
      prompt: '决策树选择划分的依据是什么？',
      options: [
        '使子节点不纯度下降最多',
        '使训练误差最小的阈值',
        '使特征数量最少',
        '使树深最大',
      ],
      correctOptions: ['使子节点不纯度下降最多'],
      conceptSlug: 'decision-trees',
      explanation: '划分增益等于父节点不纯度减去子节点加权不纯度。',
    },
    {
      id: 'decision-trees-q2',
      type: 'multiple-choice',
      prompt: '哪些做法可以降低单棵决策树的过拟合？',
      options: [
        '限制 max_depth',
        '提高 min_samples_leaf',
        '对树做剪枝',
        '让树一直生长到每个叶节点只有一个样本',
      ],
      correctOptions: ['限制 max_depth', '提高 min_samples_leaf', '对树做剪枝'],
      conceptSlug: 'decision-trees',
      explanation: '完全生长会让叶节点只剩极少样本，把噪声也写成规则。',
    },
    {
      id: 'decision-trees-q3',
      type: 'true-false',
      prompt: '判断：决策树通常不需要特征标准化，因为它只比较单个特征与阈值。',
      options: ['正确', '错误'],
      correctOptions: ['正确'],
      conceptSlug: 'decision-trees',
      explanation: '单调缩放不改变样本在单个特征上的排序，因此不影响划分。',
    },
  ],
  'random-forest-boosting': [
    {
      id: 'random-forest-boosting-q1',
      type: 'single-choice',
      prompt: '随机森林主要通过哪种机制改善单棵树的不足？',
      options: [
        '并行训练多棵有差异的树并投票，降低方差',
        '串行修正残差',
        '减少特征数量',
        '增加学习率',
      ],
      correctOptions: ['并行训练多棵有差异的树并投票，降低方差'],
      conceptSlug: 'random-forest-boosting',
      explanation: 'Bagging 依靠并行与样本/特征随机性降低方差。',
    },
    {
      id: 'random-forest-boosting-q2',
      type: 'single-choice',
      prompt: '梯度提升与随机森林在训练方式上的主要区别是什么？',
      options: [
        '梯度提升串行添加弱模型，逐步修正当前误差',
        '梯度提升并行训练所有树',
        '梯度提升不使用决策树',
        '梯度提升不使用学习率',
      ],
      correctOptions: ['梯度提升串行添加弱模型，逐步修正当前误差'],
      conceptSlug: 'random-forest-boosting',
      explanation: 'Boosting 每棵新树拟合前面的残差，学习率控制每步贡献。',
    },
    {
      id: 'random-forest-boosting-q3',
      type: 'true-false',
      prompt: '判断：随机森林中树的数量越多，单棵树的深度通常也越深。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'random-forest-boosting',
      explanation: '树的棵数与单棵树的深度是两个独立控制项。',
    },
  ],
  'model-evaluation': [
    {
      id: 'model-evaluation-q1',
      type: 'single-choice',
      prompt: '癌症初筛更怕漏诊，应优先关注哪个指标？',
      options: [
        'Recall（召回率）',
        'Precision（精确率）',
        'Accuracy（准确率）',
        '训练损失',
      ],
      correctOptions: ['Recall（召回率）'],
      conceptSlug: 'model-evaluation',
      explanation: '漏报对应 FN，召回率衡量真实正例被找出的比例。',
    },
    {
      id: 'model-evaluation-q2',
      type: 'single-choice',
      prompt: '垃圾邮件拦截若误删正常邮件代价很高，应优先关注哪个指标？',
      options: ['Precision（精确率）', 'Recall（召回率）', 'R²', 'MSE'],
      correctOptions: ['Precision（精确率）'],
      conceptSlug: 'model-evaluation',
      explanation: '误报对应 FP，精确率衡量被判为正的样本里有多少真正为正。',
    },
    {
      id: 'model-evaluation-q3',
      type: 'calculation',
      prompt:
        '正类占 1%，模型把所有样本都预测为负类，Accuracy 是多少？（写成百分数）',
      accept: ['99%', '0.99', '99', '99%左右'],
      conceptSlug: 'model-evaluation',
      explanation: '负类占 99%，全部预测为负时准确率约 99%，但正类召回为 0。',
    },
  ],
  'cross-validation': [
    {
      id: 'cross-validation-q1',
      type: 'single-choice',
      prompt: '使用 K 折交叉验证比较模型时，预处理参数应该在哪里拟合？',
      options: [
        '在每一折的训练部分内部拟合',
        '在全部数据上先拟合一次',
        '在测试集上拟合',
        '不需要拟合',
      ],
      correctOptions: ['在每一折的训练部分内部拟合'],
      conceptSlug: 'cross-validation',
      explanation: '在全部数据上拟合会让验证折的分布信息泄漏进训练流程。',
    },
    {
      id: 'cross-validation-q2',
      type: 'single-choice',
      prompt: '每位用户有多条记录时，应使用哪种划分方式？',
      options: [
        '按用户 ID 分组划分（GroupKFold）',
        '完全随机划分',
        '按记录行号顺序划分',
        '只划分一次',
      ],
      correctOptions: ['按用户 ID 分组划分（GroupKFold）'],
      conceptSlug: 'cross-validation',
      explanation: '同一用户同时出现在训练与验证中会让模型记住个体特征。',
    },
    {
      id: 'cross-validation-q3',
      type: 'true-false',
      prompt: '判断：交叉验证的平均分越高越好，所以不需要关注各折分数的波动。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'cross-validation',
      explanation:
        '标准差反映模型对数据划分的敏感程度，波动过大说明结果不稳定。',
    },
  ],
  'data-preprocessing': [
    {
      id: 'data-preprocessing-q1',
      type: 'single-choice',
      prompt: '标准化时正确的顺序是什么？',
      options: [
        '先划分数据，再只用训练集拟合 μ 和 σ',
        '先在全部数据上拟合，再划分',
        '在验证集上拟合，再应用到训练集',
        '每个样本各自标准化',
      ],
      correctOptions: ['先划分数据，再只用训练集拟合 μ 和 σ'],
      conceptSlug: 'data-preprocessing',
      explanation: '全数据统计量包含测试集信息，会造成数据泄漏。',
    },
    {
      id: 'data-preprocessing-q2',
      type: 'true-false',
      prompt: '判断：测试集与线上数据只能调用 transform，不能重新 fit。',
      options: ['正确', '错误'],
      correctOptions: ['正确'],
      conceptSlug: 'data-preprocessing',
      explanation: '重新 fit 会让训练与推理使用不同尺度的预处理参数。',
    },
    {
      id: 'data-preprocessing-q3',
      type: 'formula-fill',
      prompt:
        '写出用训练集均值 μ 与标准差 σ 做标准化的公式（用 x、μ、σ 表示）。',
      accept: [
        '(x-μ)/σ',
        '(x-mu)/sigma',
        "x'=(x-μ)/σ",
        'x-mu/sigma',
        'z=(x-μ)/σ',
      ],
      conceptSlug: 'data-preprocessing',
      explanation: '减去训练集均值再除以训练集标准差。',
    },
  ],
  'feature-engineering': [
    {
      id: 'feature-engineering-q1',
      type: 'single-choice',
      prompt: '构造特征时必须满足哪条硬性要求？',
      options: [
        '在真实预测时刻该信息已经可以获得',
        '必须使用测试集统计量',
        '必须是整数',
        '必须与目标高度相关且由目标计算得到',
      ],
      correctOptions: ['在真实预测时刻该信息已经可以获得'],
      conceptSlug: 'feature-engineering',
      explanation: '使用预测时尚不存在的信息就是未来信息泄漏。',
    },
    {
      id: 'feature-engineering-q2',
      type: 'single-choice',
      prompt: '为“贷款发放时预测未来是否违约”建模，哪个特征最危险？',
      options: [
        '贷款发放后 90 天的逾期次数',
        '申请时的收入',
        '申请时的负债率',
        '历史还款记录',
      ],
      correctOptions: ['贷款发放后 90 天的逾期次数'],
      conceptSlug: 'feature-engineering',
      explanation: '该特征在预测时尚未产生，却在训练数据中透露了结果。',
    },
    {
      id: 'feature-engineering-q3',
      type: 'multiple-choice',
      prompt: 'ColumnTransformer 适合解决什么问题？',
      options: [
        '对数值列与类别列分别应用不同变换',
        '把预处理与模型绑成一致流程',
        '自动标注数据',
        '替代交叉验证',
      ],
      correctOptions: [
        '对数值列与类别列分别应用不同变换',
        '把预处理与模型绑成一致流程',
      ],
      conceptSlug: 'feature-engineering',
      explanation: '它按列路由变换，并在训练与预测中保持一致。',
    },
  ],
  'logistic-regression': [
    {
      id: 'logistic-regression-q1',
      type: 'single-choice',
      prompt: '逻辑回归如何把线性得分变成概率？',
      options: [
        '通过 Sigmoid 函数压缩到 0～1',
        '通过取绝对值',
        '通过除以样本数',
        '通过 softmax 归一化',
      ],
      correctOptions: ['通过 Sigmoid 函数压缩到 0～1'],
      conceptSlug: 'logistic-regression',
      explanation: 'p(y=1|x)=σ(wᵀx+b)，σ 输出可解释为概率估计。',
    },
    {
      id: 'logistic-regression-q2',
      type: 'single-choice',
      prompt: 'sklearn 逻辑回归中 C 从 1 减小到 0.01，正则化强度如何变化？',
      options: ['变强', '变弱', '不变', '先变强后变弱'],
      correctOptions: ['变强'],
      conceptSlug: 'logistic-regression',
      explanation: 'C 是正则强度的倒数，C 变小意味着约束更强。',
    },
    {
      id: 'logistic-regression-q3',
      type: 'true-false',
      prompt: '判断：逻辑回归只适用于二分类，无法处理多分类。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'logistic-regression',
      explanation: '通过 softmax 或一对多策略可以扩展到多分类。',
    },
  ],
  'support-vector-machines': [
    {
      id: 'support-vector-machines-q1',
      type: 'single-choice',
      prompt: 'SVM 中真正决定决策边界的是哪些样本？',
      options: [
        '靠近间隔的支持向量',
        '全部训练样本',
        '被正确分类且远离边界的样本',
        '随机抽取的样本',
      ],
      correctOptions: ['靠近间隔的支持向量'],
      conceptSlug: 'support-vector-machines',
      explanation: '远离边界的样本不影响边界位置。',
    },
    {
      id: 'support-vector-machines-q2',
      type: 'single-choice',
      prompt: 'RBF 核 SVM 的 gamma 变大时通常会发生什么？',
      options: [
        '单个样本影响范围更局部，边界更曲折',
        '间隔一定变大',
        '模型退化为线性模型',
        '正则化消失',
      ],
      correctOptions: ['单个样本影响范围更局部，边界更曲折'],
      conceptSlug: 'support-vector-machines',
      explanation: 'gamma 控制核的宽度，过大会导致过拟合。',
    },
    {
      id: 'support-vector-machines-q3',
      type: 'true-false',
      prompt: '判断：SVM 对特征尺度不敏感，因此不需要标准化。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'support-vector-machines',
      explanation: 'SVM 依赖距离与间隔，尺度差异会显著改变边界。',
    },
  ],
  'pca-clustering': [
    {
      id: 'pca-clustering-q1',
      type: 'single-choice',
      prompt: '第一主成分是在所有单位方向中满足什么条件的方向？',
      options: [
        '投影方差最大',
        '投影均值最大',
        '与目标相关性最高',
        '特征数量最少',
      ],
      correctOptions: ['投影方差最大'],
      conceptSlug: 'pca-clustering',
      explanation: 'PCA 用方差最大的正交方向保留最多变化。',
    },
    {
      id: 'pca-clustering-q2',
      type: 'true-false',
      prompt: '判断：PCA 投影后分得开，说明原始数据一定存在对应的真实类别。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'pca-clustering',
      explanation: 'PCA 只保留方差，不保证投影方向与类别判别一致。',
    },
    {
      id: 'pca-clustering-q3',
      type: 'multiple-choice',
      prompt: '做 PCA 之前需要注意什么？',
      options: [
        '先统一各特征尺度',
        '先检查主成分解释的方差比例',
        '先对全部数据做标准化再划分训练测试集',
        '把类别标签作为输入特征',
      ],
      correctOptions: ['先统一各特征尺度', '先检查主成分解释的方差比例'],
      conceptSlug: 'pca-clustering',
      explanation:
        '尺度不一致会让大尺度特征主导方差方向；标准化同样只能在训练集上拟合。',
    },
  ],
  'end-to-end-ml-project': [
    {
      id: 'end-to-end-ml-project-q1',
      type: 'single-choice',
      prompt: '端到端机器学习项目中，最终测试集应该使用几次？',
      options: [
        '在方案锁定后使用一次',
        '每次调参都使用',
        '至少三次取平均',
        '不需要使用',
      ],
      correctOptions: ['在方案锁定后使用一次'],
      conceptSlug: 'end-to-end-ml-project',
      explanation: '反复使用会让测试集参与模型选择，结果不再中立。',
    },
    {
      id: 'end-to-end-ml-project-q2',
      type: 'multiple-choice',
      prompt: '保存推理产物时，除了模型权重还应保存什么？',
      options: [
        '预处理参数',
        '类别标签映射',
        '模型结构配置',
        '训练时的验证集样本',
      ],
      correctOptions: ['预处理参数', '类别标签映射', '模型结构配置'],
      conceptSlug: 'end-to-end-ml-project',
      explanation:
        '推理需要与训练一致的预处理、结构和标签映射，保存整个 Pipeline 最稳妥。',
    },
    {
      id: 'end-to-end-ml-project-q3',
      type: 'concept-explanation',
      prompt:
        '按正确顺序写出端到端项目的主要阶段，并说明测试集在第几步被使用。',
      referenceAnswer:
        '阶段顺序为：定义任务与指标 → 数据审计 → 设计划分 → 预处理与基线 → 模型比较与调参 → 最终测试 → 保存与推理输入校验 → 监控漂移。测试集在“最终测试”阶段、方案锁定之后才使用，且只使用一次。',
      conceptSlug: 'end-to-end-ml-project',
      explanation: '回答应体现测试集在末尾且只用一次。',
    },
  ],

  // ---------------------------------------------------------------- AI 基础
  'ai-overview': [
    {
      id: 'ai-overview-q1',
      type: 'multiple-choice',
      prompt: '一个 AI 系统的典型组成包括哪些环节？',
      options: ['感知与输入', '内部表示', '推理或学习', '行动与输出'],
      correctOptions: ['感知与输入', '内部表示', '推理或学习', '行动与输出'],
      conceptSlug: 'ai-overview',
      explanation: 'AI 系统把现实问题抽象为输入、表示、求解与输出。',
    },
    {
      id: 'ai-overview-q2',
      type: 'true-false',
      prompt: '判断：AI、机器学习与深度学习是三个并列、互不包含的技术。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'ai-overview',
      explanation:
        '机器学习是实现 AI 的一条路径，深度学习是机器学习的一个分支。',
    },
    {
      id: 'ai-overview-q3',
      type: 'concept-explanation',
      prompt: '解释规则系统与学习系统在“智能来源”上的区别。',
      referenceAnswer:
        '规则系统的行为来自人预先写好的条件与动作，智能体现在人的设计上；学习系统由算法从数据中拟合参数或结构，行为随训练数据与目标改变。前者的边界由人写死，后者需要数据、评价指标与泛化验证。',
      conceptSlug: 'ai-overview',
      explanation: '回答需要指出规则由人书写、参数由数据学习。',
    },
  ],
  'state-space-search': [
    {
      id: 'state-space-search-q1',
      type: 'single-choice',
      prompt: '在边代价相同的图上，广度优先搜索能保证找到什么？',
      options: [
        '步数最少的解',
        '代价最低的解',
        '最先找到的任意解',
        '最优的连续解',
      ],
      correctOptions: ['步数最少的解'],
      conceptSlug: 'state-space-search',
      explanation: 'BFS 按层扩展，因此得到最少步数路径，但不等于最低代价。',
    },
    {
      id: 'state-space-search-q2',
      type: 'single-choice',
      prompt: '搜索中 visited 集合的作用是什么？',
      options: [
        '避免在含环图中重复扩展同一状态',
        '记录动作代价',
        '保存最终路径长度',
        '排序候选动作',
      ],
      correctOptions: ['避免在含环图中重复扩展同一状态'],
      conceptSlug: 'state-space-search',
      explanation: '没有 visited 时环会导致搜索无法结束或大量重复。',
    },
    {
      id: 'state-space-search-q3',
      type: 'formula-fill',
      prompt:
        '分支因子 b、最浅解深度 d 时，BFS 的时间复杂度写成关于 b 与 d 的表达式。',
      accept: ['O(b^d)', 'b^d', 'O(b**d)', 'O(b^d) '],
      conceptSlug: 'state-space-search',
      explanation: '节点数按层指数增长，为 O(b^d)。',
    },
  ],
  'knowledge-representation': [
    {
      id: 'knowledge-representation-q1',
      type: 'single-choice',
      prompt: '语义网络用什么表达“猫是动物”这类知识？',
      options: [
        '节点表示实体、有向边表示关系',
        '一张像素矩阵',
        '一段梯度向量',
        '一个概率密度函数',
      ],
      correctOptions: ['节点表示实体、有向边表示关系'],
      conceptSlug: 'knowledge-representation',
      explanation: '节点与有向边构成可查询、可推理的图结构。',
    },
    {
      id: 'knowledge-representation-q2',
      type: 'true-false',
      prompt: '判断：把事实存进数据库就等于系统具备了完整推理能力。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'knowledge-representation',
      explanation: '存储事实只是前提，推理还需要规则或推理机。',
    },
    {
      id: 'knowledge-representation-q3',
      type: 'concept-explanation',
      prompt: '说明知识表示为什么需要同时考虑“结构”与“不确定性”。',
      referenceAnswer:
        '结构决定机器能否查询与推理，例如实体、关系、层级与继承；但现实知识常不完整、会过期、来源可信度不同，因此还需要表达置信度、时效与冲突处理，否则推理结论会显得确定却不可靠。',
      conceptSlug: 'knowledge-representation',
      explanation: '回答应同时提到可操作性结构与不确定性/时效。',
    },
  ],
  'generative-ai': [
    {
      id: 'generative-ai-q1',
      type: 'single-choice',
      prompt: '自回归生成模型如何分解整个序列的概率？',
      options: [
        '拆成逐步预测下一个元素的条件概率之积',
        '直接用一次分类得到整句',
        '对每个位置独立采样',
        '只用第一个词决定全部输出',
      ],
      correctOptions: ['拆成逐步预测下一个元素的条件概率之积'],
      conceptSlug: 'generative-ai',
      explanation: 'P(x₁…xₙ)=∏ᵢP(xᵢ|x₁…xᵢ₋₁)。',
    },
    {
      id: 'generative-ai-q2',
      type: 'true-false',
      prompt: '判断：生成文本流畅就说明其中的事实是可靠的。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'generative-ai',
      explanation: '流畅度来自分布拟合，不保证事实正确。',
    },
    {
      id: 'generative-ai-q3',
      type: 'concept-explanation',
      prompt: '解释采样策略为什么会同时影响生成的多样性与可靠性。',
      referenceAnswer:
        '采样温度或截断策略决定从概率分布中取样的随机程度：更随机会得到更多样的输出，但也更容易选到低概率的错误内容；更保守会提高稳定性却容易重复、缺乏多样性。因此需要在任务允许的错误代价下权衡。',
      conceptSlug: 'generative-ai',
      explanation: '回答需要指出多样性与可靠性之间的权衡。',
    },
  ],

  // ---------------------------------------------------------------- 数学基础
  'math-data-foundations': [
    {
      id: 'math-data-foundations-q1',
      type: 'single-choice',
      prompt: '特征矩阵 X ∈ ℝⁿˣᵈ 中 n 和 d 分别表示什么？',
      options: [
        'n 是样本数，d 是特征数',
        'n 是特征数，d 是样本数',
        '两者都是类别数',
        '两者都是标签数',
      ],
      correctOptions: ['n 是样本数，d 是特征数'],
      conceptSlug: 'math-data-foundations',
      explanation: 'X 的行是样本、列是特征。',
    },
    {
      id: 'math-data-foundations-q2',
      type: 'code-output',
      prompt:
        'X = np.array([[1., 2.], [3., 6.], [5., 10.]])，X.mean(axis=0) 的结果是什么？',
      accept: ['[3.6.]', '[3.,6.]', '[3. 6.]', '3和6'],
      conceptSlug: 'math-data-foundations',
      explanation: '按 axis=0 沿样本方向聚合，得到每列均值 3 和 6。',
    },
    {
      id: 'math-data-foundations-q3',
      type: 'formula-fill',
      prompt: '用 w、x 写出点积形式的线性得分（不含偏置 b）。',
      accept: ['w^Tx', 'wᵀx', 'Σwⱼxⱼ', 'sum(w_j*x_j)', 'wx'],
      conceptSlug: 'math-data-foundations',
      explanation: '点积把每个特征乘上对应权重后求和。',
    },
  ],
  'dot-product-weighted-sum': [
    {
      id: 'dot-product-weighted-sum-q1',
      type: 'single-choice',
      prompt: '点积运算对输入维度的要求是什么？',
      options: [
        '两个向量维度必须一致',
        '两个向量维度必须不同',
        '必须是方阵',
        '必须是整数',
      ],
      correctOptions: ['两个向量维度必须一致'],
      conceptSlug: 'dot-product-weighted-sum',
      explanation: '维度不一致无法逐项相乘。',
    },
    {
      id: 'dot-product-weighted-sum-q2',
      type: 'calculation',
      prompt: 'x=[1,2,3]，w=[2,-1,4]，b=0，求 z=wᵀx+b。',
      accept: ['12', 'z=12'],
      conceptSlug: 'dot-product-weighted-sum',
      explanation: '2×1 + (-1)×2 + 4×3 = 2 − 2 + 12 = 12。',
    },
    {
      id: 'dot-product-weighted-sum-q3',
      type: 'true-false',
      prompt: '判断：未标准化时可以直接比较不同特征权重的大小来判断重要性。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'dot-product-weighted-sum',
      explanation: '权重大小与特征尺度耦合，尺度不同就无法直接比较。',
    },
  ],
  'euclidean-distance': [
    {
      id: 'euclidean-distance-q1',
      type: 'single-choice',
      prompt: '欧氏距离在什么情况下会给出误导性的结果？',
      options: [
        '各特征量纲和数值范围差异很大时',
        '样本量很小时',
        '特征都是二值时',
        '目标是连续值时',
      ],
      correctOptions: ['各特征量纲和数值范围差异很大时'],
      conceptSlug: 'euclidean-distance',
      explanation: '大尺度特征会主导距离，因此通常需要先标准化。',
    },
    {
      id: 'euclidean-distance-q2',
      type: 'calculation',
      prompt: 'x=[1,2,3]，y=[4,6,3]，欧氏距离是多少？',
      accept: ['5'],
      conceptSlug: 'euclidean-distance',
      explanation: '√(3²+4²+0²)=5。',
    },
    {
      id: 'euclidean-distance-q3',
      type: 'formula-fill',
      prompt: '写出两个 d 维向量的欧氏距离公式。',
      accept: ['sqrt(Σ(x_j-y_j)^2)', '√Σⱼ(xⱼ-yⱼ)²', 'd(x,y)=√Σ(x_j-y_j)^2'],
      conceptSlug: 'euclidean-distance',
      explanation: '各维差值平方和的平方根。',
    },
  ],
  'mean-variance-standard-deviation': [
    {
      id: 'mean-variance-standard-deviation-q1',
      type: 'code-output',
      prompt: 'x = np.array([50., 60., 70.])，x.mean() 是多少？',
      accept: ['60', '60.0'],
      conceptSlug: 'mean-variance-standard-deviation',
      explanation: '(50+60+70)/3 = 60。',
    },
    {
      id: 'mean-variance-standard-deviation-q2',
      type: 'single-choice',
      prompt: '标准差相比方差有什么优势？',
      options: [
        '保留原始数据的单位，便于业务解释',
        '计算更简单',
        '不受异常值影响',
        '总是更小',
      ],
      correctOptions: ['保留原始数据的单位，便于业务解释'],
      conceptSlug: 'mean-variance-standard-deviation',
      explanation: '标准差是方差的平方根，单位与原始数据一致。',
    },
    {
      id: 'mean-variance-standard-deviation-q3',
      type: 'true-false',
      prompt: '判断：样本方差与总体方差使用相同的分母，因此可以互换。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'mean-variance-standard-deviation',
      explanation: '样本方差常用 n−1 做无偏修正，两者不能随意互换。',
    },
  ],
  'probability-and-thresholds': [
    {
      id: 'probability-and-thresholds-q1',
      type: 'single-choice',
      prompt: '把二分类阈值从 0.5 降到 0.3，通常会发生什么？',
      options: [
        '召回提高、误报增多',
        '召回降低、误报减少',
        '不受影响',
        '精确率一定提高',
      ],
      correctOptions: ['召回提高、误报增多'],
      conceptSlug: 'probability-and-thresholds',
      explanation: '更多样本被判为正类，因此更容易命中正例，也更容易误报。',
    },
    {
      id: 'probability-and-thresholds-q2',
      type: 'true-false',
      prompt: '判断：模型输出概率越高，预测正确的可能性就必然越大。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'probability-and-thresholds',
      explanation: '概率大不等于正确，还取决于概率是否校准。',
    },
    {
      id: 'probability-and-thresholds-q3',
      type: 'concept-explanation',
      prompt: '为什么阈值应该在验证集上选择，而不是直接在测试集上选？',
      referenceAnswer:
        '阈值是一个需要根据误报与漏报成本做出的决策参数，属于模型选择的一部分。在验证集上选择阈值、锁定后再到测试集评价一次，测试集才能保持中立；直接在测试集上调阈值会让测试结果偏向被优化过的方向，得到过于乐观的结论。',
      conceptSlug: 'probability-and-thresholds',
      explanation: '回答应说明阈值属于模型选择，测试集调阈值会造成选择偏差。',
    },
  ],
  'conditional-probability-bayes': [
    {
      id: 'conditional-probability-bayes-q1',
      type: 'formula-fill',
      prompt: '写出贝叶斯公式，用 P(C|x)、P(x|C)、P(C)、P(x) 表示。',
      accept: [
        'P(C|x)=P(x|C)P(C)/P(x)',
        'P(C|x)=P(x|C)*P(C)/P(x)',
        'P(C|x)∝P(x|C)P(C)',
      ],
      conceptSlug: 'conditional-probability-bayes',
      explanation: '后验 ∝ 似然 × 先验。',
    },
    {
      id: 'conditional-probability-bayes-q2',
      type: 'single-choice',
      prompt: 'P(A|B) 的含义是什么？',
      options: [
        '在 B 已发生的条件下 A 发生的概率',
        'A 与 B 同时发生的概率',
        'A 或 B 发生的概率',
        'B 在 A 已发生条件下的概率',
      ],
      correctOptions: ['在 B 已发生的条件下 A 发生的概率'],
      conceptSlug: 'conditional-probability-bayes',
      explanation: '条件概率把观察范围限制在 B 已发生的样本内。',
    },
    {
      id: 'conditional-probability-bayes-q3',
      type: 'true-false',
      prompt:
        '判断：比较类别时，因为 P(x) 对所有类别相同，可以直接比较 P(x|C)P(C)。',
      options: ['正确', '错误'],
      correctOptions: ['正确'],
      conceptSlug: 'conditional-probability-bayes',
      explanation: '证据项 P(x) 与类别无关，只做归一化，因此可以省略。',
    },
  ],
  'gradient-descent': [
    {
      id: 'gradient-descent-q1',
      type: 'single-choice',
      prompt: '参数更新时为什么要沿负梯度方向移动？',
      options: [
        '梯度指向损失上升最快的方向',
        '负梯度方向步长最大',
        '负梯度方向一定是全局最优',
        '梯度只与学习率有关',
      ],
      correctOptions: ['梯度指向损失上升最快的方向'],
      conceptSlug: 'gradient-descent',
      explanation: '要降低损失就要沿与梯度相反的方向更新。',
    },
    {
      id: 'gradient-descent-q2',
      type: 'formula-fill',
      prompt: '写出梯度下降的参数更新公式（用 θ、α、∇J(θ) 表示）。',
      accept: [
        'θ=θ-α∇J(θ)',
        'θ_{t+1}=θ_t-α∇J(θ_t)',
        'theta = theta - alpha * grad',
        'θ←θ-η∇J(θ)',
      ],
      conceptSlug: 'gradient-descent',
      explanation: '学习率 α 乘以梯度，沿负方向更新。',
    },
    {
      id: 'gradient-descent-q3',
      type: 'multiple-choice',
      prompt: '梯度下降可能出现哪些问题？',
      options: [
        '学习率过大导致震荡甚至发散',
        '学习率过小导致收敛很慢',
        '陷入局部极小或平台区',
        '特征尺度差异过大导致收敛困难',
      ],
      correctOptions: [
        '学习率过大导致震荡甚至发散',
        '学习率过小导致收敛很慢',
        '陷入局部极小或平台区',
        '特征尺度差异过大导致收敛困难',
      ],
      conceptSlug: 'gradient-descent',
      explanation: '梯度只提供局部信息，因此学习率与特征尺度都很关键。',
    },
  ],
  'mse-rmse': [
    {
      id: 'mse-rmse-q1',
      type: 'formula-fill',
      prompt: '写出 MSE 的公式（用 y、ŷ、n 表示）。',
      accept: ['(1/n)Σ(y-ŷ)²', 'MSE=(1/n)Σ(y_i-ŷ_i)^2', 'mean((y-yhat)^2)'],
      conceptSlug: 'mse-rmse',
      explanation: '预测误差平方的平均值。',
    },
    {
      id: 'mse-rmse-q2',
      type: 'calculation',
      prompt: 'MSE = 12.25 时 RMSE 是多少？',
      accept: ['3.5', '3.5'],
      conceptSlug: 'mse-rmse',
      explanation: 'RMSE 是 MSE 的平方根：√12.25 = 3.5。',
    },
    {
      id: 'mse-rmse-q3',
      type: 'true-false',
      prompt: '判断：可以在不同目标单位的数据集之间直接比较 MSE 的大小。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'mse-rmse',
      explanation: 'MSE 的单位是目标单位的平方，跨任务比较没有意义。',
    },
  ],
  'cross-entropy': [
    {
      id: 'cross-entropy-q1',
      type: 'single-choice',
      prompt: '分类任务使用交叉熵时，模型应该输出什么？',
      options: [
        '各类别概率（或未经 softmax 的 logits，由损失内部处理）',
        '任意实数',
        '类别编号的平方',
        '固定阈值',
      ],
      correctOptions: [
        '各类别概率（或未经 softmax 的 logits，由损失内部处理）',
      ],
      conceptSlug: 'cross-entropy',
      explanation:
        '交叉熵需要概率；若使用框架的 logits 版本损失，则不要重复做 softmax。',
    },
    {
      id: 'cross-entropy-q2',
      type: 'true-false',
      prompt: '判断：给真实类别分配很低的概率时，交叉熵损失会变得很大。',
      options: ['正确', '错误'],
      correctOptions: ['正确'],
      conceptSlug: 'cross-entropy',
      explanation: '−log p 在 p→0 时趋于无穷，因此交叉熵重罚自信的错误预测。',
    },
    {
      id: 'cross-entropy-q3',
      type: 'concept-explanation',
      prompt: '为什么两个准确率相同的模型，交叉熵可能差别很大？',
      referenceAnswer:
        '准确率只看最终类别是否取对，而交叉熵使用完整概率：答对但概率只有 0.51 会带来较大损失，答对且概率为 0.99 损失很小；自信答错则会被重罚。因此交叉熵还衡量概率质量与置信度，能区分准确率相同但概率质量不同的模型。',
      conceptSlug: 'cross-entropy',
      explanation: '回答需要指出交叉熵使用完整概率分布而非仅最终类别。',
    },
  ],
  'gini-impurity': [
    {
      id: 'gini-impurity-q1',
      type: 'calculation',
      prompt: '二分类节点中两类样本各占一半，Gini 不纯度是多少？',
      accept: ['0.5', '.5', '1/2'],
      conceptSlug: 'gini-impurity',
      explanation: '1 − (0.5² + 0.5²) = 0.5，这是二分类的最大值。',
    },
    {
      id: 'gini-impurity-q2',
      type: 'single-choice',
      prompt: '纯节点（只有一类样本）的 Gini 不纯度是多少？',
      options: ['0', '0.5', '1', '取决于样本数'],
      correctOptions: ['0'],
      conceptSlug: 'gini-impurity',
      explanation: '1 − 1² = 0。',
    },
    {
      id: 'gini-impurity-q3',
      type: 'formula-fill',
      prompt: '写出划分增益 Gain 与父节点、子节点不纯度的关系式。',
      accept: [
        'Gain=Gini(S)-Σ(n_c/n)Gini(S_c)',
        'I(parent)-Σ(n_k/n)I(child_k)',
      ],
      conceptSlug: 'gini-impurity',
      explanation: '增益等于父节点不纯度减去子节点按样本数加权的平均不纯度。',
    },
  ],
  'bias-variance-learning-curves': [
    {
      id: 'bias-variance-learning-curves-q1',
      type: 'single-choice',
      prompt: '训练与验证表现都很差，最可能是哪种问题？',
      options: [
        '高偏差（欠拟合）',
        '高方差（过拟合）',
        '数据泄漏',
        '标签比例失衡',
      ],
      correctOptions: ['高偏差（欠拟合）'],
      conceptSlug: 'bias-variance-learning-curves',
      explanation: '两边都差说明模型能力或特征不足以表达规律。',
    },
    {
      id: 'bias-variance-learning-curves-q2',
      type: 'single-choice',
      prompt: '训练分数很高但验证分数明显落后，最可能是哪种问题？',
      options: [
        '高方差（过拟合）',
        '高偏差（欠拟合）',
        '学习率太小',
        '测试集过小',
      ],
      correctOptions: ['高方差（过拟合）'],
      conceptSlug: 'bias-variance-learning-curves',
      explanation: '模型对训练样本过度敏感，换数据后表现下降。',
    },
    {
      id: 'bias-variance-learning-curves-q3',
      type: 'true-false',
      prompt: '判断：高偏差问题可以通过增加更多训练数据直接解决。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'bias-variance-learning-curves',
      explanation:
        '高偏差时需要提高模型表达能力或改进特征，增加数据通常帮助有限。',
    },
  ],

  // ---------------------------------------------------------------- 深度学习
  'artificial-neuron': [
    {
      id: 'artificial-neuron-q1',
      type: 'formula-fill',
      prompt: '写出人工神经元的输出表达式（用 w、x、b 与激活函数 f 表示）。',
      accept: ['y=f(w^Tx+b)', 'y=f(wᵀx+b)', 'y=f(wx+b)', 'f(w^Tx+b)'],
      conceptSlug: 'artificial-neuron',
      explanation: '先做仿射变换，再通过激活函数。',
    },
    {
      id: 'artificial-neuron-q2',
      type: 'single-choice',
      prompt: '偏置 b 的作用是什么？',
      options: [
        '调整整体触发门槛',
        '决定输入维度',
        '替代激活函数',
        '保存学习率',
      ],
      correctOptions: ['调整整体触发门槛'],
      conceptSlug: 'artificial-neuron',
      explanation: '偏置平移加权和，改变激活的难易程度。',
    },
    {
      id: 'artificial-neuron-q3',
      type: 'true-false',
      prompt: '判断：没有激活函数时，堆叠多层线性层仍然等价于一个线性变换。',
      options: ['正确', '错误'],
      correctOptions: ['正确'],
      conceptSlug: 'artificial-neuron',
      explanation: '线性变换的复合仍是线性变换，无法表达复杂函数。',
    },
  ],
  'activation-functions': [
    {
      id: 'activation-functions-q1',
      type: 'single-choice',
      prompt: 'ReLU 的数学形式是什么？',
      options: ['max(0, x)', '1/(1+e⁻ˣ)', 'tanh(x)', 'x²'],
      correctOptions: ['max(0, x)'],
      conceptSlug: 'activation-functions',
      explanation: 'ReLU 保留正值、截断负值。',
    },
    {
      id: 'activation-functions-q2',
      type: 'code-output',
      prompt: 'torch.relu(torch.tensor([-2., -0.5, 0., 3.])) 的结果是什么？',
      accept: ['[0.,0.,0.,3.]', '[0,0,0,3]', 'tensor([0., 0., 0., 3.])'],
      conceptSlug: 'activation-functions',
      explanation: '负输入输出 0，正输入保持不变。',
    },
    {
      id: 'activation-functions-q3',
      type: 'true-false',
      prompt: '判断：所有任务的输出层都应使用同一个激活函数。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'activation-functions',
      explanation: '输出层激活必须匹配任务类型与损失函数。',
    },
  ],
  'loss-functions': [
    {
      id: 'loss-functions-q1',
      type: 'single-choice',
      prompt: 'PyTorch 的 nn.CrossEntropyLoss 期望的输入是什么？',
      options: [
        '未经过 softmax 的原始 logits 与类别索引',
        '已 softmax 的概率与类别索引',
        'one-hot 标签与概率',
        '连续目标值',
      ],
      correctOptions: ['未经过 softmax 的原始 logits 与类别索引'],
      conceptSlug: 'loss-functions',
      explanation:
        '该损失内部完成 log-softmax，重复做 softmax 会得到错误结果。',
    },
    {
      id: 'loss-functions-q2',
      type: 'single-choice',
      prompt: '回归任务最常用的损失函数是什么？',
      options: ['均方误差 MSE', '交叉熵', 'Hinge 损失', 'KL 散度'],
      correctOptions: ['均方误差 MSE'],
      conceptSlug: 'loss-functions',
      explanation: '连续目标通常使用 MSE 或 L1 类损失。',
    },
    {
      id: 'loss-functions-q3',
      type: 'concept-explanation',
      prompt: '为什么不能只看损失值判断模型是否解决了业务问题？',
      referenceAnswer:
        '损失衡量的是模型在训练目标上的平均偏差，它受损失函数选择、样本权重和训练分布影响，并不直接对应业务关心的错误代价。例如分类问题中损失下降但少数类召回仍可能为 0。因此还需要在业务指标与分层指标上评价，并检查错误样本。',
      conceptSlug: 'loss-functions',
      explanation: '回答需要指出损失是训练目标，业务指标才反映真实需求。',
    },
  ],
  backpropagation: [
    {
      id: 'backpropagation-q1',
      type: 'single-choice',
      prompt: '反向传播依据哪条数学规则计算梯度？',
      options: ['链式法则', '贝叶斯公式', '大数定律', '中心极限定理'],
      correctOptions: ['链式法则'],
      conceptSlug: 'backpropagation',
      explanation: '逐节点把下游梯度与局部导数相乘。',
    },
    {
      id: 'backpropagation-q2',
      type: 'calculation',
      prompt: 'w=2，x=3，loss=(wx−5)²，求 w 的梯度。',
      accept: ['6', '6.0'],
      conceptSlug: 'backpropagation',
      explanation: '2(wx−5)·x = 2×1×3 = 6。',
    },
    {
      id: 'backpropagation-q3',
      type: 'true-false',
      prompt: '判断：PyTorch 每次 backward 会覆盖上一次的梯度。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'backpropagation',
      explanation: '梯度默认累加，因此训练循环通常需要 zero_grad。',
    },
  ],
  'neural-networks': [
    {
      id: 'neural-networks-q1',
      type: 'single-choice',
      prompt:
        '一个 4 维输入经 nn.Linear(4, 8) 再经 nn.Linear(8, 2) 后，输出维度是多少？',
      options: ['2', '4', '8', '16'],
      correctOptions: ['2'],
      conceptSlug: 'neural-networks',
      explanation: '最后一层决定输出维度，即 2 个得分。',
    },
    {
      id: 'neural-networks-q2',
      type: 'true-false',
      prompt: '判断：层数越多模型效果一定越好。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'neural-networks',
      explanation: '更深会带来优化与过拟合风险，需要与数据和正则化匹配。',
    },
    {
      id: 'neural-networks-q3',
      type: 'concept-explanation',
      prompt: '解释为什么网络必须包含非线性激活。',
      referenceAnswer:
        '如果每层都只做线性变换，多层复合仍然等价于单层线性变换，网络只能表示线性函数。加入非线性激活后，多层结构才能逼近复杂函数，逐层组合出边缘、纹理、语义等非线性的表示。',
      conceptSlug: 'neural-networks',
      explanation: '回答需要指出线性变换的复合仍是线性变换。',
    },
  ],
  'convolutional-neural-networks': [
    {
      id: 'convolutional-neural-networks-q1',
      type: 'calculation',
      prompt: 'Conv2d(3, 32, kernel_size=3, bias=True) 的参数量是多少？',
      accept: ['896'],
      conceptSlug: 'convolutional-neural-networks',
      explanation: '32×(3×3×3+1)=32×28=896，与输入高宽无关。',
    },
    {
      id: 'convolutional-neural-networks-q2',
      type: 'single-choice',
      prompt: '卷积层中“参数共享”带来的主要好处是什么？',
      options: [
        '参数量远小于全连接，且同一模式可在不同位置被识别',
        '完全不需要激活函数',
        '不需要池化',
        '可以忽略通道数',
      ],
      correctOptions: ['参数量远小于全连接，且同一模式可在不同位置被识别'],
      conceptSlug: 'convolutional-neural-networks',
      explanation: '同一个卷积核在整张图上滑动，因此具备平移等变性。',
    },
    {
      id: 'convolutional-neural-networks-q3',
      type: 'code-output',
      prompt:
        '输入 [1,3,32,32] 经过 Conv2d(3, 16, kernel_size=3, padding=1) 后输出形状是什么？',
      accept: ['[1,16,32,32]', '(1,16,32,32)', '1,16,32,32'],
      conceptSlug: 'convolutional-neural-networks',
      explanation: 'padding=1 且 stride=1 时高宽不变，通道变为 16。',
    },
  ],
  transformer: [
    {
      id: 'transformer-q1',
      type: 'formula-fill',
      prompt: '写出缩放点积注意力的公式（用 Q、K、V、dₖ 表示）。',
      accept: [
        'Attention(Q,K,V)=softmax(QK^T/√d_k)V',
        'softmax(QKᵀ/√dₖ)V',
        'softmax(QK^T/sqrt(d_k))V',
      ],
      conceptSlug: 'transformer',
      explanation: '分数除以维度平方根后再 softmax，最后对 V 加权求和。',
    },
    {
      id: 'transformer-q2',
      type: 'single-choice',
      prompt: '缩放点积注意力中为什么除以 √dₖ？',
      options: [
        '防止点积过大导致 softmax 饱和、梯度过小',
        '减少参数量',
        '增加序列长度',
        '替代位置编码',
      ],
      correctOptions: ['防止点积过大导致 softmax 饱和、梯度过小'],
      conceptSlug: 'transformer',
      explanation: '维度越大点积方差越大，缩放让 softmax 输入保持合理范围。',
    },
    {
      id: 'transformer-q3',
      type: 'multiple-choice',
      prompt: 'Transformer 中哪些说法正确？',
      options: [
        '自注意力中 Q、K、V 都来自同一组输入',
        '注意力权重可以完整解释模型决策',
        '需要位置编码补充顺序信息',
        '注意力分数元素数随序列长度按平方增长',
      ],
      correctOptions: [
        '自注意力中 Q、K、V 都来自同一组输入',
        '需要位置编码补充顺序信息',
        '注意力分数元素数随序列长度按平方增长',
      ],
      conceptSlug: 'transformer',
      explanation: '注意力权重只是中间量，不能当作完整解释。',
    },
  ],
  'embeddings-sequences': [
    {
      id: 'embeddings-sequences-q1',
      type: 'code-output',
      prompt:
        'ids 形状为 [1,4]，nn.Embedding(1000, 64, padding_idx=0) 的输出形状是什么？',
      accept: ['[1,4,64]', '(1,4,64)', '1,4,64'],
      conceptSlug: 'embeddings-sequences',
      explanation: '在 token id 维度后追加 embedding 维度。',
    },
    {
      id: 'embeddings-sequences-q2',
      type: 'single-choice',
      prompt: 'padding_idx 的作用是什么？',
      options: [
        '让补齐位置的向量固定为零向量且不参与梯度更新',
        '删除补齐位置',
        '自动截断长序列',
        '改变词表大小',
      ],
      correctOptions: ['让补齐位置的向量固定为零向量且不参与梯度更新'],
      conceptSlug: 'embeddings-sequences',
      explanation: '补齐 token 不应携带语义，也不应被学习。',
    },
    {
      id: 'embeddings-sequences-q3',
      type: 'true-false',
      prompt: '判断：把 token id 直接当连续数值输入网络是合理的。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'embeddings-sequences',
      explanation:
        'id 只是索引，没有大小关系，必须通过 Embedding 转成稠密向量。',
    },
  ],
  'rnn-lstm-gru': [
    {
      id: 'rnn-lstm-gru-q1',
      type: 'single-choice',
      prompt: 'LSTM 相比普通 RNN 的主要改进是什么？',
      options: [
        '用门控结构控制信息的写入与保留，缓解长期依赖问题',
        '不需要反向传播',
        '只能处理定长序列',
        '完全去掉了隐藏状态',
      ],
      correctOptions: ['用门控结构控制信息的写入与保留，缓解长期依赖问题'],
      conceptSlug: 'rnn-lstm-gru',
      explanation: '门控让梯度更容易长距离传播。',
    },
    {
      id: 'rnn-lstm-gru-q2',
      type: 'single-choice',
      prompt: '双向 RNN 为什么不适合严格的在线自回归任务？',
      options: [
        '它需要看到未来上下文',
        '它参数量太大',
        '它不能处理变长序列',
        '它没有隐藏状态',
      ],
      correctOptions: ['它需要看到未来上下文'],
      conceptSlug: 'rnn-lstm-gru',
      explanation: '自回归任务在预测当前步时无法获得未来 token。',
    },
    {
      id: 'rnn-lstm-gru-q3',
      type: 'calculation',
      prompt:
        '长度分别为 [5,3,4]、补齐长度为 5 的单向 RNN 输出 [3,5,H]，第一个样本应取哪个时间下标？（零起始）',
      accept: ['4'],
      conceptSlug: 'rnn-lstm-gru',
      explanation: '长度为 5 时最后一个有效下标是 4，即 length−1。',
    },
  ],
  'residual-networks': [
    {
      id: 'residual-networks-q1',
      type: 'single-choice',
      prompt: '残差连接为什么有助于训练很深的网络？',
      options: [
        '提供一条恒等路径，让梯度更容易回传',
        '减少参数量到零',
        '去掉了激活函数',
        '自动选择学习率',
      ],
      correctOptions: ['提供一条恒等路径，让梯度更容易回传'],
      conceptSlug: 'residual-networks',
      explanation: 'shortcut 让梯度不必穿过所有中间层。',
    },
    {
      id: 'residual-networks-q2',
      type: 'single-choice',
      prompt:
        '输入 [8,64,32,32]，主分支输出 [8,128,16,16]，shortcut 至少需要什么卷积？',
      options: [
        'Conv2d(64,128,kernel_size=1,stride=2)',
        'Conv2d(64,128,kernel_size=3,stride=1)',
        'Conv2d(128,64,kernel_size=1,stride=2)',
        '不需要任何变换',
      ],
      correctOptions: ['Conv2d(64,128,kernel_size=1,stride=2)'],
      conceptSlug: 'residual-networks',
      explanation: '需要同时把通道 64→128、高宽 32→16，才能相加。',
    },
    {
      id: 'residual-networks-q3',
      type: 'true-false',
      prompt: '判断：残差块可以直接把任意形状的主分支输出与输入相加。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'residual-networks',
      explanation: '相加要求形状一致，否则必须使用投影 shortcut。',
    },
  ],
  normalization: [
    {
      id: 'normalization-q1',
      type: 'single-choice',
      prompt: 'LayerNorm 与 BatchNorm 的关键区别是什么？',
      options: [
        'LayerNorm 在单个样本内部统计，不依赖 batch 组成',
        'LayerNorm 需要 batch 维统计',
        'LayerNorm 只能用于 CNN',
        'BatchNorm 不需要运行统计',
      ],
      correctOptions: ['LayerNorm 在单个样本内部统计，不依赖 batch 组成'],
      conceptSlug: 'normalization',
      explanation: '差异主要在于统计集合 S 包含哪些轴。',
    },
    {
      id: 'normalization-q2',
      type: 'single-choice',
      prompt: '评估阶段忘记调用 model.eval() 会导致什么问题？',
      options: [
        'BatchNorm 仍用当前 batch 统计、Dropout 仍在随机丢弃',
        '梯度被永久关闭',
        '参数被重置',
        '学习率变为 0',
      ],
      correctOptions: ['BatchNorm 仍用当前 batch 统计、Dropout 仍在随机丢弃'],
      conceptSlug: 'normalization',
      explanation: 'eval 会切换到运行统计并关闭 Dropout 随机性。',
    },
    {
      id: 'normalization-q3',
      type: 'true-false',
      prompt: '判断：输入数据标准化与网络内部归一化层是同一个概念。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'normalization',
      explanation: '前者处理输入特征，后者归一化网络中间激活。',
    },
  ],
  'optimizers-schedulers': [
    {
      id: 'optimizers-schedulers-q1',
      type: 'single-choice',
      prompt: 'AdamW 相比 Adam 的主要差别是什么？',
      options: [
        '把权重衰减与梯度更新解耦',
        '不需要学习率',
        '不使用动量',
        '只能用于 CNN',
      ],
      correctOptions: ['把权重衰减与梯度更新解耦'],
      conceptSlug: 'optimizers-schedulers',
      explanation: '解耦后权重衰减不再被自适应缩放影响。',
    },
    {
      id: 'optimizers-schedulers-q2',
      type: 'true-false',
      prompt: '判断：scheduler.step() 可以随意放在循环中的任何位置，效果相同。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'optimizers-schedulers',
      explanation: '调度粒度必须是 epoch 或 iteration，放错位置会改变总步数。',
    },
    {
      id: 'optimizers-schedulers-q3',
      type: 'single-choice',
      prompt: '训练中使用动量的目的是什么？',
      options: [
        '减少震荡、加速沿一致方向的移动',
        '完全消除学习率',
        '替代权重衰减',
        '保证找到全局最优',
      ],
      correctOptions: ['减少震荡、加速沿一致方向的移动'],
      conceptSlug: 'optimizers-schedulers',
      explanation: '动量累积历史梯度方向，平滑更新轨迹。',
    },
  ],
  'gradient-initialization': [
    {
      id: 'gradient-initialization-q1',
      type: 'single-choice',
      prompt: 'ReLU 网络通常推荐哪种初始化？',
      options: [
        'He/Kaiming 初始化',
        '全部初始化为 0',
        '全部初始化为同一个常数',
        '标准差为 100 的正态分布',
      ],
      correctOptions: ['He/Kaiming 初始化'],
      conceptSlug: 'gradient-initialization',
      explanation: 'He 初始化按 2/fan_in 控制方差，适配 ReLU。',
    },
    {
      id: 'gradient-initialization-q2',
      type: 'true-false',
      prompt: '判断：把所有权重初始化为 0 是安全的做法。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'gradient-initialization',
      explanation: '同一层神经元会得到相同梯度，无法打破对称性。',
    },
    {
      id: 'gradient-initialization-q3',
      type: 'single-choice',
      prompt: '深层网络出现梯度消失时，最可能的现象是什么？',
      options: [
        '靠近输入的层几乎不再更新',
        '输出层梯度爆炸',
        '学习率自动变大',
        '损失一定下降',
      ],
      correctOptions: ['靠近输入的层几乎不再更新'],
      conceptSlug: 'gradient-initialization',
      explanation: '梯度逐层相乘后趋近于零，浅层学不到东西。',
    },
  ],
  'dl-evaluation-imbalance': [
    {
      id: 'dl-evaluation-imbalance-q1',
      type: 'single-choice',
      prompt: '正类占 1% 时全部预测为负类，Accuracy 约为多少？',
      options: ['99%', '1%', '50%', '0%'],
      correctOptions: ['99%'],
      conceptSlug: 'dl-evaluation-imbalance',
      explanation: '负类占 99%，因此准确率很高但正类召回为 0。',
    },
    {
      id: 'dl-evaluation-imbalance-q2',
      type: 'multiple-choice',
      prompt: '评估阶段必须做哪些事情？',
      options: [
        '调用 model.eval()',
        '使用 torch.inference_mode() 关闭梯度',
        '累计混淆矩阵或每类指标',
        '继续用训练集更新参数',
      ],
      correctOptions: [
        '调用 model.eval()',
        '使用 torch.inference_mode() 关闭梯度',
        '累计混淆矩阵或每类指标',
      ],
      conceptSlug: 'dl-evaluation-imbalance',
      explanation: '评估阶段不更新参数，并需要分层指标揭示少数类问题。',
    },
    {
      id: 'dl-evaluation-imbalance-q3',
      type: 'formula-fill',
      prompt: '写出宏平均 F1 的计算方式（用 C 与 F1c 表示）。',
      accept: ['(1/C)ΣF1_c', 'F1macro=(1/C)Σ_c F1_c', 'mean(F1_c)'],
      conceptSlug: 'dl-evaluation-imbalance',
      explanation: '宏平均给每个类别相同权重。',
    },
  ],
  'data-pipeline': [
    {
      id: 'data-pipeline-q1',
      type: 'single-choice',
      prompt: 'Dataset 与 DataLoader 的职责如何划分？',
      options: [
        'Dataset 返回单样本，DataLoader 负责分批、打乱与并行读取',
        'Dataset 负责分批，DataLoader 只保存标签',
        '两者职责相同',
        'DataLoader 负责定义标签含义',
      ],
      correctOptions: [
        'Dataset 返回单样本，DataLoader 负责分批、打乱与并行读取',
      ],
      conceptSlug: 'data-pipeline',
      explanation: 'batch 维由 DataLoader 的 collate 过程添加。',
    },
    {
      id: 'data-pipeline-q2',
      type: 'multiple-choice',
      prompt: '关于 shuffle 设置，哪些说法正确？',
      options: [
        '训练集通常 shuffle=True',
        '验证集与测试集通常 shuffle=False',
        '测试集 shuffle=True 能得到更可靠的指标',
        '打乱会改变样本内容',
      ],
      correctOptions: [
        '训练集通常 shuffle=True',
        '验证集与测试集通常 shuffle=False',
      ],
      conceptSlug: 'data-pipeline',
      explanation:
        '打乱只改变顺序，不会改变样本内容；评估阶段打乱会让结果难以复现。',
    },
    {
      id: 'data-pipeline-q3',
      type: 'true-false',
      prompt:
        '判断：有学习参数的预处理（如标准化）必须在划分数据之后、只用训练集拟合。',
      options: ['正确', '错误'],
      correctOptions: ['正确'],
      conceptSlug: 'data-pipeline',
      explanation: '在全部数据上拟合会把验证/测试信息带入训练流程。',
    },
  ],
  'epoch-batch-iteration': [
    {
      id: 'epoch-batch-iteration-q1',
      type: 'calculation',
      prompt:
        '训练集 1050 条、batch size=100、drop_last=False，每个 epoch 有多少次 iteration？',
      accept: ['11'],
      conceptSlug: 'epoch-batch-iteration',
      explanation: '⌈1050/100⌉ = 11。',
    },
    {
      id: 'epoch-batch-iteration-q2',
      type: 'calculation',
      prompt: '同上但 drop_last=True，每个 epoch 有多少次 iteration？',
      accept: ['10'],
      conceptSlug: 'epoch-batch-iteration',
      explanation: '丢弃最后 50 条不完整批次后为 10 次。',
    },
    {
      id: 'epoch-batch-iteration-q3',
      type: 'single-choice',
      prompt: '一个 iteration 通常对应什么？',
      options: [
        '一次前向、反向与参数更新',
        '一次完整遍历训练集',
        '一个 epoch 的平均损失',
        '一次数据集下载',
      ],
      correctOptions: ['一次前向、反向与参数更新'],
      conceptSlug: 'epoch-batch-iteration',
      explanation: '内层循环处理一个 batch 并更新一次参数。',
    },
  ],
  'pytorch-tensors-modules': [
    {
      id: 'pytorch-tensors-modules-q1',
      type: 'calculation',
      prompt: 'nn.Linear(5, 3) 的可学习参数量是多少（含偏置）？',
      accept: ['18'],
      conceptSlug: 'pytorch-tensors-modules',
      explanation: '5×3+3 = 18。',
    },
    {
      id: 'pytorch-tensors-modules-q2',
      type: 'code-output',
      prompt:
        'layer = nn.Linear(5, 3)，x = torch.randn(8, 5)，layer(x).shape 是什么？',
      accept: ['[8,3]', '(8,3)', 'torch.Size([8, 3])', '8,3'],
      conceptSlug: 'pytorch-tensors-modules',
      explanation: '[N,din] @ [din,dout] → [N,dout]，即 [8,3]。',
    },
    {
      id: 'pytorch-tensors-modules-q3',
      type: 'true-false',
      prompt:
        '判断：nn.Module 会自动登记子模块与参数，因此 optimizer 可以直接读取 model.parameters()。',
      options: ['正确', '错误'],
      correctOptions: ['正确'],
      conceptSlug: 'pytorch-tensors-modules',
      explanation: 'Module 通过属性赋值自动注册参数与子模块。',
    },
  ],
  'model-debugging': [
    {
      id: 'model-debugging-q1',
      type: 'single-choice',
      prompt: 'Loss 长期不下降时，为什么应先尝试拟合 8～32 个样本？',
      options: [
        '容量足够的模型应能记住极小数据，失败说明是代码或数据问题',
        '小 batch 训练更快',
        '小 batch 不需要损失函数',
        '这样可以跳过验证',
      ],
      correctOptions: [
        '容量足够的模型应能记住极小数据，失败说明是代码或数据问题',
      ],
      conceptSlug: 'model-debugging',
      explanation: '极小 batch 过拟合是排除实现错误的快速检查。',
    },
    {
      id: 'model-debugging-q2',
      type: 'multiple-choice',
      prompt: '极小 batch 仍无法拟合时，应优先检查什么？',
      options: [
        '输入与标签是否对应',
        'shape/dtype 是否正确',
        '输出层与损失函数是否匹配',
        '直接换成更大的模型',
      ],
      correctOptions: [
        '输入与标签是否对应',
        'shape/dtype 是否正确',
        '输出层与损失函数是否匹配',
      ],
      conceptSlug: 'model-debugging',
      explanation: '先排查数据与损失链路，再考虑模型容量。',
    },
    {
      id: 'model-debugging-q3',
      type: 'true-false',
      prompt: '判断：参数没有被登记到 optimizer 也会导致模型完全不学习。',
      options: ['正确', '错误'],
      correctOptions: ['正确'],
      conceptSlug: 'model-debugging',
      explanation: '优化器只能更新传入的参数列表。',
    },
  ],
  'model-saving-inference': [
    {
      id: 'model-saving-inference-q1',
      type: 'single-choice',
      prompt: '推理前为什么必须调用 model.eval()？',
      options: [
        '切换到运行统计并关闭 Dropout 随机性',
        '释放显存',
        '清空梯度',
        '重置学习率',
      ],
      correctOptions: ['切换到运行统计并关闭 Dropout 随机性'],
      conceptSlug: 'model-saving-inference',
      explanation: 'eval 与 inference_mode 职责不同，评估时通常同时使用。',
    },
    {
      id: 'model-saving-inference-q2',
      type: 'multiple-choice',
      prompt: '只保存 state_dict 之后，部署推理还需要哪些信息？',
      options: [
        '模型结构配置',
        '预处理参数',
        '类别标签映射',
        '训练时的随机种子',
      ],
      correctOptions: ['模型结构配置', '预处理参数', '类别标签映射'],
      conceptSlug: 'model-saving-inference',
      explanation: '推理必须重建相同结构并复用相同预处理与标签顺序。',
    },
    {
      id: 'model-saving-inference-q3',
      type: 'true-false',
      prompt:
        '判断：训练时用一套预处理、推理时用另一套，只要模型权重相同结果就一致。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'model-saving-inference',
      explanation: '输入分布不一致会让线上效果显著偏离离线评估。',
    },
  ],
  'training-engineering': [
    {
      id: 'training-engineering-q1',
      type: 'multiple-choice',
      prompt: '可恢复训练的检查点应包含哪些内容？',
      options: [
        '模型权重',
        '优化器状态',
        '调度器状态与当前 epoch',
        '最佳验证指标',
      ],
      correctOptions: [
        '模型权重',
        '优化器状态',
        '调度器状态与当前 epoch',
        '最佳验证指标',
      ],
      conceptSlug: 'training-engineering',
      explanation: '缺少优化器或调度器状态无法真正接续训练。',
    },
    {
      id: 'training-engineering-q2',
      type: 'single-choice',
      prompt:
        '为什么通常保存“最佳验证分数”对应的权重而不是最后一个 epoch 的权重？',
      options: [
        '最后几个 epoch 可能已经过拟合',
        '最后一个 epoch 的权重无法保存',
        '最佳权重参数量更小',
        '验证分数与权重无关',
      ],
      correctOptions: ['最后几个 epoch 可能已经过拟合'],
      conceptSlug: 'training-engineering',
      explanation: '训练后期验证指标可能回落，最佳检查点更可靠。',
    },
    {
      id: 'training-engineering-q3',
      type: 'true-false',
      prompt: '判断：只要固定一个随机种子，实验结果就一定可以完整复现。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'training-engineering',
      explanation: '还需要固定数据版本、配置、库版本与硬件相关算子行为。',
    },
  ],
  'transfer-learning': [
    {
      id: 'transfer-learning-q1',
      type: 'single-choice',
      prompt: '微调时“冻结参数”的正确做法是什么？',
      options: [
        '把 requires_grad 设为 False',
        '只调用 model.eval()',
        '把学习率设为 0 后不再恢复',
        '删除这些层',
      ],
      correctOptions: ['把 requires_grad 设为 False'],
      conceptSlug: 'transfer-learning',
      explanation: '冻结与 eval 是不同操作：前者不更新参数，后者改变层行为。',
    },
    {
      id: 'transfer-learning-q2',
      type: 'single-choice',
      prompt: '数据量很少时，迁移学习通常先怎么做？',
      options: [
        '冻结骨干只训练新任务头',
        '从头训练全部参数',
        '解冻所有层并用大学习率',
        '去掉预训练权重',
      ],
      correctOptions: ['冻结骨干只训练新任务头'],
      conceptSlug: 'transfer-learning',
      explanation: '先训练任务头可以避免少量数据破坏预训练表示。',
    },
    {
      id: 'transfer-learning-q3',
      type: 'true-false',
      prompt: '判断：使用预训练权重时，预处理必须与该权重训练时保持一致。',
      options: ['正确', '错误'],
      correctOptions: ['正确'],
      conceptSlug: 'transfer-learning',
      explanation: '输入分布不匹配会让预训练特征失效。',
    },
  ],
  'detection-segmentation': [
    {
      id: 'detection-segmentation-q1',
      type: 'calculation',
      prompt:
        '真实框 A=[0,0,4,4]，预测框 B=[2,2,6,6]，IoU 是多少？（保留三位小数）',
      accept: ['0.143', '1/7', '0.142857', '0.14'],
      conceptSlug: 'detection-segmentation',
      explanation: '交集面积 4，并集面积 16+16−4=28，IoU=4/28≈0.143。',
    },
    {
      id: 'detection-segmentation-q2',
      type: 'single-choice',
      prompt: 'NMS 在目标检测中的作用是什么？',
      options: [
        '去除重叠的冗余检测框',
        '提升图像分辨率',
        '计算分类损失',
        '生成标注',
      ],
      correctOptions: ['去除重叠的冗余检测框'],
      conceptSlug: 'detection-segmentation',
      explanation: '同一目标常产生多个高重叠框，NMS 按分数与 IoU 抑制冗余。',
    },
    {
      id: 'detection-segmentation-q3',
      type: 'true-false',
      prompt: '判断：数据增强时只变换图像、不变换标注框是安全的。',
      options: ['正确', '错误'],
      correctOptions: ['错误'],
      conceptSlug: 'detection-segmentation',
      explanation: '几何变换必须同步作用于标注，否则框与内容错位。',
    },
  ],
  'deep-generative-models': [
    {
      id: 'deep-generative-models-q1',
      type: 'single-choice',
      prompt: 'VAE 的重参数化技巧解决了什么问题？',
      options: [
        '把随机性移到独立噪声，使梯度可以通过 μ 与 σ 传播',
        '减少参数量',
        '去掉编码器',
        '保证生成结果真实',
      ],
      correctOptions: ['把随机性移到独立噪声，使梯度可以通过 μ 与 σ 传播'],
      conceptSlug: 'deep-generative-models',
      explanation: 'z = μ + σ⊙ε 让采样步骤可微分。',
    },
    {
      id: 'deep-generative-models-q2',
      type: 'single-choice',
      prompt: 'GAN 的训练特点是什么？',
      options: [
        '生成器与判别器对抗，训练稳定性较难控制',
        '只优化重建误差',
        '不需要任何损失函数',
        '只能生成文本',
      ],
      correctOptions: ['生成器与判别器对抗，训练稳定性较难控制'],
      conceptSlug: 'deep-generative-models',
      explanation: '对抗目标容易出现振荡与模式崩塌。',
    },
    {
      id: 'deep-generative-models-q3',
      type: 'true-false',
      prompt: '判断：扩散模型通过学习逐步去噪来生成样本。',
      options: ['正确', '错误'],
      correctOptions: ['正确'],
      conceptSlug: 'deep-generative-models',
      explanation: '扩散模型把噪声一步步还原成数据。',
    },
  ],
};

// Many concepts do not have a curated entry yet. For those, the plan builds
// questions straight from the stored concept text (the real definition and its
// declared prerequisites) so no phase ever receives a placeholder question, and
// never a fabricated answer.
export function curatedQuestionsFor(slug: string): StageQuestionInput[] {
  return questionBank[slug] ?? [];
}
