/**
 * Generates `app/katex-fonts.css` from `katex/dist/katex.min.css`.
 *
 * KaTeX ships its `@font-face` rules with relative `url(fonts/...)` paths. Those
 * resolve against whatever directory the bundled stylesheet ends up in, which
 * differs between the dev server and the built Workers assets, so the production
 * build requested `/_next/static/css/fonts/*.woff2` and got 404 for every font.
 *
 * The generated stylesheet keeps the upstream declarations verbatim but points
 * every `url()` at the absolute `/fonts/...` path that `public/fonts` is served
 * from, and it only keeps formats whose files are actually present. Run it after
 * installing or upgrading katex:
 *
 *   node --experimental-strip-types scripts/generate-katex-fonts.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);
const katexCssPath = require.resolve('katex/dist/katex.min.css');
const katexCss = readFileSync(katexCssPath, 'utf8');
const publicFontsDir = join(projectRoot, 'public', 'fonts');
const outputPath = join(projectRoot, 'app', 'katex-fonts.css');

const EXTENSIONS = ['woff2', 'woff', 'ttf'] as const;

function publicUrlFor(fileName: string) {
  const onDisk = join(publicFontsDir, fileName);
  try {
    readFileSync(onDisk);
    return `/fonts/${fileName}`;
  } catch {
    return null;
  }
}

interface RewriteStats {
  fonts: number;
  /** Entries dropped because the file is not shipped in `public/fonts`. */
  absent: Set<string>;
  dropped: Set<string>;
  /** Font families left without any usable source. */
  emptyFamilies: Set<string>;
}

const stats: RewriteStats = {
  fonts: 0,
  absent: new Set(),
  dropped: new Set(),
  emptyFamilies: new Set(),
};

/**
 * Rewrites one `src:` value. Keeps the upstream order of formats and drops any
 * entry whose file is absent from `public/fonts`, because a missing file inside
 * a `src` list is exactly what produced the 404s for the `.woff`/`.ttf` variants
 * this project does not ship. Only WOF2 is published; every browser able to run
 * this app supports it.
 */
function rewriteSrc(srcValue: string, family: string) {
  const entries: string[] = [];
  const pattern = /url\(\s*(['"]?)(?:\.\/)?fonts\/([^'")]+)\1\s*\)\s*format\(\s*(['"]?)([a-z0-9-]+)\3\s*\)/gi;
  let matched = false;
  for (const match of srcValue.matchAll(pattern)) {
    matched = true;
    const fileName = match[2]!;
    const format = match[4]!;
    if (!EXTENSIONS.includes(format as (typeof EXTENSIONS)[number])) {
      stats.dropped.add(`${fileName} (${format})`);
      continue;
    }
    const url = publicUrlFor(fileName);
    if (!url) {
      stats.absent.add(fileName);
      continue;
    }
    entries.push(`url(${url}) format("${format}")`);
  }
  if (!matched) return null;
  if (!entries.length) {
    stats.emptyFamilies.add(family);
    return null;
  }
  stats.fonts += 1;
  return entries.join(',');
}

const rewritten = katexCss.replace(
  /@font-face\s*\{([^}]*)\}/gi,
  (whole, body: string) => {
    const family = /font-family:\s*("?)([^;"]+)\1/i.exec(body)?.[2] ?? 'unknown';
    const next = body.replace(/src:\s*([^;}]+)/i, (full, srcValue: string) => {
      const resolved = rewriteSrc(srcValue, family);
      return resolved ? `src:${resolved}` : full;
    });
    return next === body ? whole : `@font-face{${next}}`;
  },
);

if (stats.emptyFamilies.size) {
  console.error(
    `No usable font file for: ${[...stats.emptyFamilies].join(', ')}. ` +
      'Add the matching woff2 files to public/fonts and re-run.',
  );
  process.exit(1);
}
if (!stats.fonts) {
  console.error('No KaTeX @font-face rules were rewritten; aborting.');
  process.exit(1);
}

const banner = `/*
 * Generated by scripts/generate-katex-fonts.ts from katex/dist/katex.min.css.
 * Do not edit by hand: run \`npm run generate:katex-fonts\` after upgrading katex.
 * Font URLs are absolute (/fonts/...) so they resolve identically in the dev
 * server and in the built Cloudflare Workers assets.
 */
`;

writeFileSync(outputPath, `${banner}${rewritten}\n`, 'utf8');
console.log(
  `Wrote ${outputPath}: ${stats.fonts} @font-face rules rewritten to /fonts/.`,
);
if (stats.absent.size)
  console.log(
    `Dropped ${stats.absent.size} font entries whose files are not shipped (only .woff2 is published).`,
  );
if (stats.dropped.size)
  console.log(`Skipped unsupported formats: ${[...stats.dropped].join(', ')}`);
